### ISSUE TITLE
minimum players to start round dont have to be full request

### ISSUE THREAD

**Issue by stevewall85** [alkarinv/BattleArena#101]
This might be somewhere i havent seen but im using battle arena and arena spleef i have come to like thses plugins they are pretty easy to use and get going. But my question is i would like to set a minimum of 2 players and have a max of maybee 10 for spleef with a start command to start with a lower amount of players. Is there something available with in the plug i didnt see?

**Comment by alkarinv** [comment]
BattleArena/config.yml

defaultOptions.matchEnableForceStart: true <- will make the match start after a given time even if not enough people have joined.

so set that to true.. then set the nTeams: 10  for spleef.. then it should work exactly how you described!

**Comment by stevewall85** [comment]
that did it for the most part i was looking for a start cmd but i can live with the timer thanks for the help keep up the good work i love this plugin now

**Comment by alkarinv** [comment]
Oh, you can also force start with a cmd.
*/arena forcestart
