### ISSUE TITLE
Players need to be told they're trying to be added to a team...

### ISSUE THREAD

**Issue by netherfoam** [alkarinv/BattleArena#104]
<pre>1.  Join queue
2.  Be invited to arena team
3.  Receive message "You are already in the arena queue"
</pre>

If you're randomly invited to a team, you have no idea why you're being told this. Only reason I knew was because I had command spy on :)

**Comment by alkarinv** [comment]
Interesting, you are right.

**Comment by alkarinv** [comment]
Fixed on dropbox version.

http://dl.dropbox.com/u/38069770/jars/BattleArena.jar
