### ISSUE TITLE
For Some Reason It Won't Work :(

### ISSUE THREAD

**Issue by BlueSnapple** [alkarinv/BattleArena#106]
When I updated it just stopped working right. It wont let me do /arena join anymore. Please Help me.

**Comment by alkarinv** [comment]
Any errors on console? there should be some clue as to what is up.

**Comment by BlueSnapple** [comment]
No, I typed /arena join like in the last version and doesn't work. There are no errors in the console.

**Comment by alkarinv** [comment]
try the version located here.

http://dl.dropbox.com/u/38069770/jars/BattleArena.jar

tell me if that one works

**Comment by BlueSnapple** [comment]
It does the same thing. :( Whenever I do /arena join it says for me to do 
/arena <create|alter|join|leave|top...> [arguments]
and it keeps saying that every time I do /arena join. It used to work in the previous version. Can you send me a link to previous version?

**Comment by alkarinv** [comment]
there has got to be an error on startup, some clue, can you please check. 

 I don't have previous versions but the bukkit dev site has all the ones I've released... just go to the files section.

**Comment by BlueSnapple** [comment]
Ok I just switched the jar out with the old one I was using and it works now. I will just use the version I am using now since the new ones do not work. Thanks for your time. :)
