### ISSUE TITLE
Minor: Redundant space (picture)

### ISSUE THREAD

**Issue by mkromann** [alkarinv/BattleArena#109]
Minor detail but there's a space too much in this message:
http://i.imgur.com/G1inkS9.png

**Comment by alkarinv** [comment]
Yeah indeed there is.. I'll fix that in the main messages.yml, but you should go in manually and fix to get rid of it immediately, should be easy.

**Comment by alkarinv** [comment]
sorry, nevermind.. this will have to be a code fix... but it will be in the next version.
