### ISSUE TITLE
You can't enter the arena through teleports

### ISSUE THREAD

**Issue by netherfoam** [alkarinv/BattleArena#111]
Hi, Alkarinv.

Even if you seem to be MIA at the moment, here's another bug report :)

When players teleport a location in the world challenge_8, they are told in &c color:

<pre>
You can't enter the arena through teleports
</pre>

And the teleport is cancelled.

However, there is no arena at that location. Instead, in our arena world, at the same coordinates is our Quake arena. Here's the snippet from arenas.yml

<pre>
  quake:
    persistable:
      wgRegion: arena,ba-quake
    teamSize: 3+
    locations:
      '1': arena,-468.99884033203125,70.0,-145.81655883789062,-181.49995,-0.89998686
      '0': arena,-468.8315734863281,70.0,-190.01976013183594,-1.4999609,-2.3999977
    nTeams: '2'
    type: battleground
</pre>

Disabling BattleArena using a PlugMan allows the player to be teleported there. The player may teleport to any other location fine.

BattleArena 3.7.9.5
Spigot 1.4.6 R0.3

**Comment by netherfoam** [comment]
Update: There is also no worldguard region in challenge_8 at that location.

**Comment by alkarinv** [comment]
So its like the world is ignored?

Basically there is a worlguard region there in another world?

**Comment by alkarinv** [comment]
Confirmed and fixed.

Will be out with BattleArena 3.8
