### ISSUE TITLE
Multiple spawns for one team 

### ISSUE THREAD

**Issue by poochinski** [alkarinv/BattleArena#115]
I'm making a deathmatch arena with only 2 teams, not 2+, which I have changed in the config. I go to set the spawns, and type /arena alter [name] 1 & 2, and that works fine, but when I do 3 it says team 3 spawn set. Is there a different command for making more than one spawn for a team.

**Comment by alkarinv** [comment]
There isn't a command to make more team spawns... right now if you have 2 teams.. then odd spawns are team 1.. and even spawns are team 2.
