### ISSUE TITLE
This error comes up when I try to use Arena CTF. 

### ISSUE THREAD

**Issue by dramatech88** [alkarinv/BattleArena#116]
04.03 01:57:16 [Server] SEVERE at net.minecraft.server.v1_4_R1.PlayerConnection.d(PlayerConnection.java:113)
04.03 01:57:16 [Server] SEVERE at net.minecraft.server.v1_4_R1.NetworkManager.b(NetworkManager.java:290)
04.03 01:57:16 [Server] SEVERE at net.minecraft.server.v1_4_R1.Packet3Chat.handle(Packet3Chat.java:44)
04.03 01:57:16 [Server] SEVERE at net.minecraft.server.v1_4_R1.PlayerConnection.a(PlayerConnection.java:853)
04.03 01:57:16 [Server] SEVERE at net.minecraft.server.v1_4_R1.PlayerConnection.chat(PlayerConnection.java:898)
04.03 01:57:16 [Server] SEVERE at net.minecraft.server.v1_4_R1.PlayerConnection.handleCommand(PlayerConnection.java:980)
04.03 01:57:16 [Server] SEVERE at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCommand(CraftServer.java:514)
04.03 01:57:16 [Server] SEVERE at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
04.03 01:57:16 [Server] SEVERE at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
04.03 01:57:16 [Server] SEVERE at mc.alk.arena.executors.BaseExecutor.onCommand(BaseExecutor.java:239)
04.03 01:57:16 [Server] SEVERE at java.lang.reflect.Method.invoke(Method.java:601)
04.03 01:57:16 [Server] SEVERE at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04.03 01:57:16 [Server] SEVERE at sun.reflect.GeneratedMethodAccessor1265.invoke(Unknown Source)
04.03 01:57:16 [Server] SEVERE at mc.alk.arena.executors.BAExecutor.join(BAExecutor.java:146)
04.03 01:57:16 [Server] SEVERE at mc.alk.arena.executors.BAExecutor.join(BAExecutor.java:231)
04.03 01:57:16 [Server] SEVERE at mc.alk.arena.controllers.BattleArenaController.addToQue(BattleArenaController.java:217)
04.03 01:57:16 [Server] SEVERE at mc.alk.arena.objects.queues.ArenaMatchQueue.add(ArenaMatchQueue.java:88)
04.03 01:57:16 [Server] SEVERE at mc.alk.arena.objects.queues.ArenaMatchQueue.addToQueue(ArenaMatchQueue.java:118)
04.03 01:57:16 [Server] SEVERE at mc.alk.arena.objects.queues.ArenaMatchQueue.notifyIfNeeded(ArenaMatchQueue.java:194)
04.03 01:57:16 [Server] SEVERE at mc.alk.arena.objects.queues.ArenaMatchQueue.findMatch(ArenaMatchQueue.java:299)
04.03 01:57:16 [Server] SEVERE at mc.alk.arena.objects.queues.ArenaMatchQueue.findMatch(ArenaMatchQueue.java:398)
04.03 01:57:16 [Server] SEVERE at mc.alk.arena.objects.queues.ArenaMatchQueue.getMatchAndRemove(ArenaMatchQueue.java:417)
04.03 01:57:16 [Server] SEVERE at mc.alk.arena.competition.match.ArenaMatch.<init>(ArenaMatch.java:72)
04.03 01:57:16 [Server] SEVERE at mc.alk.arena.competition.match.Match.<init>(Match.java:153)
04.03 01:57:16 [Server] SEVERE at mc.alk.arena.competition.match.Match.addVictoryConditions(Match.java:756)
04.03 01:57:16 [Server] SEVERE at mc.alk.arena.objects.victoryconditions.VictoryType.createVictoryCondition(VictoryType.java:66)
04.03 01:57:16 [Server] SEVERE at java.lang.Class.getConstructor(Class.java:1674)
04.03 01:57:16 [Server] SEVERE at java.lang.Class.getConstructor0(Class.java:2721)
04.03 01:57:16 [Server] SEVERE java.lang.NoSuchMethodException: mc.alk.ctf.FlagVictory.<init>(mc.alk.arena.competition.match.Match)

**Comment by alkarinv** [comment]
I had some issues with VictoryConditions and the CTF.

The most recent version of BattleArena and ArenaCTF fix it though.

Let me know!

**Comment by dramatech88** [comment]
I have tried that. When I downloaded both of them I let it recreate the configs and start blank. It still said not enough teams in queue. Took out the victory condition and it worked great. However, when someone dies they spawn out of the game and the game ends once all players are dead. Nothing in the console shows errors this time or I would post them for you. I have tested it three times now with even writing flagvictory or victoryflag in it. Nothing works other than blank.

**Comment by alkarinv** [comment]
Get me your ip, and try to hop onto #battleplugins on IRC so I can talk to you about it in person!

We'll work it out

**Comment by dramatech88** [comment]
s3.hosthorde.com:25571 I shall be around tomorrow so I'll check in often. If you reply to this that your on IRC I can get an email. Thanks

**Comment by alkarinv** [comment]
I believe we worked this out today!

let me know if I should reopen
