### ISSUE TITLE
[Bug] Ready block continues to work after leaving the queue

### ISSUE THREAD

**Issue by AlexLeporiday** [alkarinv/BattleArena#117]
1. Join arena with /arena join
2. Leave arena queue with /arena leave
3. Punch/Break any block that is the same type as the 'ready' block.

Issue:
You receive the ready message and cannot break the block. If you join the arena and complete a match successfully then you can punch the block and break it as normal.
If you join and leave the arena queue you cannot break blocks. Relogging doesn't help, reloading the plugin doesn't help.

Something isn't releasing correctly..

**Comment by darrenstraight** [comment]
I had this same problem... funny enough I wasnt using this feature though... I had "enablePlayerReadyBlock: false" but it still seemed to be active! My solution was remove plugin, change the used block to 19 (sponge as we dont use it) and then reinstall plugin. Of course if you use the ready block... not sure what you can do.

**Comment by alkarinv** [comment]
Alright this one I'm nearly convinced I got rid of with the most recent version on Bukkit.  3.7.9.9.9+

Let me know though if it hasn't fixed it!
