### ISSUE TITLE
faction and BA

### ISSUE THREAD

**Issue by ronewird** [alkarinv/BattleArena#118]
It give me some error in console for no power less

And the config file don`t use my /f home disable setting...

And when a player left (for quit) he leave the bot (an anti left program) in the arena...

The only solution is multiverse?

**Comment by alkarinv** [comment]
Hey man, sorry it took so long.

What is the error ?  I need to know the actual stack trace.. best if you pastebin it.

You need to disable both factions, f

What is the anti left plugin?

**Comment by ronewird** [comment]
ok i have resolved the issue.
I have simple put all the arena in warzone with no power less option.
For the bot plugin at the moment i silmple remove it becouse is not working very well and i`m waiting for an update of another one called dragonantipvpleave to implement on my server

**Comment by ronewird** [comment]
i  have forget.

Fsction overwhelm any setting and any config. But with worldguard regions i have disable the /f home command of faction and the /f warp command of faction plus.

And wirh rhe friendly fire and no power less options i have fix the issue simple putting the arena on the warzone and warld guard region,

I have replace on the other part of the map the warzone with a fake faction named pvp zone, set as pacefull and permanent with pvp on. With friendly fire disable.

Is a little bit complicated but it work XD.

**Comment by alkarinv** [comment]
As long as it works!!

But if you ever see the faction power loss error let me know! I would like to see it
