### ISSUE TITLE
Skirmish & Creative Mode

### ISSUE THREAD

**Issue by WTFvckBro** [alkarinv/BattleArena#122]
I'm looking through the config file right now for Skirmish and I see the [preReqs] and I'm trying to make it so that you have to be in Survival Mode in order to join the queue or engage in a duel. Is there an option for that? If so, may I please know? If not, I suggest it be added so that users can't spawn things in the server through creative mode. 

I have CreativeControl and that makes it so that items obtained through Creative is not transferable to their Survival inventory or their chests. I'd like to keep it that way but with Skirmish, people join with their creative inventory and then the items in their creative inventory transfer to survival. Sorry if I doesn't make sense. I'm trying to make it as clear as possible.

**Comment by alkarinv** [comment]
The version I released today has a fix for this.  You can download a dev version here
http://dl.dropbox.com/u/38069770/jars/BattleArena.jar

Or wait for Bukkit to clear it.

but it allows for the option
preReqs.options: [gamemode=Survival] 

I'm going to assume this is a MultiInv issue? or some other plugin, let me know!

**Comment by WTFvckBro** [comment]
Oh, thank you! I've been refreshing your bukkit page waiting for your reply but I didn't bother looking here.

This is a creative control issue. I'm trying to make it so that players on my server aren't able to spawn things in from creative so that the server will have a balanced economy and won't have thousands upon thousands of diamonds.

I'm Omgitsdmt from your bukkit page.

**Comment by alkarinv** [comment]
Almost all BattleArena's works from craftbukkit 1.2.5 onwards
