### ISSUE TITLE
Auto Force Start not working

### ISSUE THREAD

**Issue by stevewall85** [alkarinv/BattleArena#123]
I just redid all my plugs along with my new map and now i cant get the Auto force start to work for the pvp arena i dont get any errors and i can join queue and manually force start and then the rest of the game works fine. 
http://pastebin.com/xi21tkv1   - ba config
http://pastebin.com/YdDjV3Sk  - arenas.yml
http://pastebin.com/8y8zBAyb  - arena config

This server is running CraftBukkit version git-Bukkit-1.4.7-R1.0-62-g40cbc3d-b2704jnks (MC: 1.5.1) (Implementing API version 1.5.1-R0.1-SNAPSHOT)

for the time being i have set a cmd block with the arena forcestart cmd and the plugin works great

**Comment by alkarinv** [comment]
Hey Steve, I'll check this out.  But was busy over the weekend.  Hopefully will have a fix by wed or so.

**Comment by stevewall85** [comment]
sweet take ur time like i said i have a cmd block set up to start it

**Comment by alkarinv** [comment]
This should be fixed in the most recent version 3.8.5+

Reopen if its not!
