### ISSUE TITLE
CTF Messages

### ISSUE THREAD

**Issue by FarmerKaine** [alkarinv/BattleArena#125]
I know its another plugin, but why doesn't the ArenaCTF throw up "starting in..." messages like the base ones built in here?  I can't do a /ctf auto either...  I can only /ctf join...  Is this just a perm issue?  And if so, what are the perm lines I need to pop into place?

**Comment by alkarinv** [comment]
Its because I change the CTF to be a default joinType of Queue.

If you want to make it a "JoinPhase" again.. just change or add the line
{{{
    joinType: JoinPhase
}}}
Inside of the CaptureTheFlagConfig.yml

**Comment by FarmerKaine** [comment]
I have one of the 1.5.1 Bukkit dev builds...  does that matter perhaps?

It's about 12 builds old...  (2 days approx, heh)

**Comment by FarmerKaine** [comment]
Hello sir...

I have the WgResetRegion stuff figured out sorta...

There is a couple things...
1.  The size DOES matter, in number of blocks.  I took my eliptical arena,
   expanded it clouds to bedrock and it would not add the region correctly...
   However if I just expanded it up 12 and down 5, it would select it just
   fine.
2.  I was using the wrong syntax...  I was using 'addregion' and it
   absolutely requires it to be 'addRegion'...  I have verified this several
   times with tests.
3.  My arena is now working perfectly.  Thanks for the plugin, I appreciate
   it.

I have a "newish" type issue..

When I have a CTF and an FFA event both added to the BAScheduler, and I
have an 1800 second (30 minutes) time between events...  Why do they both
run 30 seconds apart from each other upon start of the schedule...and wh
does it continue to do this until I stop them?  Every 30 minutes, BOTh run.

ANy help would rock.

Brian

On Fri, Mar 29, 2013 at 9:23 PM, Brian Schweitzer <brianschweitzer@gmail.com

> wrote:
> 
> I have one of the 1.5.1 Bukkit dev builds...  does that matter perhaps?
> 
> It's about 12 builds old...  (2 days approx, heh)
>

**Comment by alkarinv** [comment]
1) Yeah, I was trying with smaller regions, things seemed to be working.  I don't know what worldguard is doing .. but its obviously strange with large sizes.
2) That shouldnt be happening. A bug that is definitely on me. 
3) !!!!!! :)

Both run???

Can you paste here what is inside of the BattleArena/saves/scheduledEvents.yml

Hopefully I can figure it out from there.

sorry about the issues.
