### ISSUE TITLE
Error msg in console whenever a player joins

### ISSUE THREAD

**Issue by watar** [alkarinv/BattleArena#126]
http://pastebin.com/540sgLJH

Everytime a players joins the arena this shows up in console/log.
The match seems to work and finish ok but would be great to find the cause of the error msgs.

**Comment by alkarinv** [comment]
Hey, so it looks like the HeroChat channel you specified is not there.

So make the HeroChat channel and this should be fixed.  Not sure how it got to be null though, was pretty sure I checked that on startup.

**Comment by alkarinv** [comment]
oh, its either that or maybe your messages.yml got messed up somehow.

Regardless next version won't through this error regardless.

**Comment by watar** [comment]
I've set up the config as follows:
http://pastebin.com/EaPf3AK2

the herochat channel PVP seems to work as it should otherwise. Joining, chatting... I get messages from BattleArena announcing match starts, wins... just joining that gives errors
Haven't made any changes to messages.yml

**Comment by alkarinv** [comment]
Try deleting the messages.yml and doing a reload/restart.  If that doesnt work you can use this.

Dev version with fix

http://dl.dropbox.com/u/38069770/jars/BattleArena.jar

can you pastebin me your config.yml.. would like to see it

**Comment by watar** [comment]
After update to dev build and recreating messages.yml the errors disappeared.
Thanks for your help :)

**Comment by alkarinv** [comment]
np!
