### ISSUE TITLE
Not losing power on death while in an arena (Factions)

### ISSUE THREAD

**Issue by joebladon** [alkarinv/BattleArena#13]
It would be great if players didn't lose power when they die in an arena. It's fine for the smaller fighter but in a battleground players are re-spawning and dying a lot which can lower their power drastically. This is seeming to put players off from taking part in that arena type.

**Comment by alkarinv** [comment]
You can make areas a Faction Warzone, that means they can fight all they want w/o losing power.

I might try to put in some faction support, but that is the way to fix this right now.

**Comment by joebladon** [comment]
Ok thank you, i'll use that solution for now.

**Comment by alkarinv** [comment]
Hey Joebladon, So I looked at the source code for Factions and they have no way for me to modify whether a player loses power on Death.  I'll be asking them to put some sort of hook for me to change it, but for now it is literally impossible unless I modify their code directly.

Just wanted to let you know
