### ISSUE TITLE
Default Class and WaitRoom/Join

### ISSUE THREAD

**Issue by zrocweb** [alkarinv/BattleArena#132]
Hey. 2 Part question pf a Battleground arena:

First Part:  
Have it set up so when they join it takes them to a waitroom to be able to select their class.  When they join it does not take them to the wait room until the match prestarts.  I've tried to put the teleportWaitRoom in different areas but same result. Maybe I'm doing something wrong...  Is it because its a queue?  I guess my problem is the waiting part.  So if I was a player on the server and wanted to join this arena I understand that I have wait for 'x' amount of players and/or queue time to elapse before it could start.  But the problems is again waiting. Cause once I get into the wait room there needs to be sufficient time to allow the players to select their class.  And the only option to control this is globally (I think) via the 'secondsTilMatch' from the config.  The problem with that being global is that it affects all arenas where time is not a factor where here it is imperative.  Is there any way to change that where it won't affect globally?  Or perhaps again am I missing something....  Sorry for all the "issues" submission, just trying to get some clarity on things I can find in the wiki.

Second Part:
When they finally get into the waitroom and select their class, and the match begins, they receive the default class in addition to the class they just selected.  If I take out the default class and the player does not select a class (stupid, yes I know), they are not given anything to fight with...

Here is my setup:

Battelground.yml:
Battleground:
    enabled: true
    joinType: Queue
    database: bg
    prefix: "&c[Battleground]&e"
    victoryCondition: highestKills
    matchTime: 270
    nTeams: 2+
    teamSize: 1+
    defaults:
        options: [woolTeams]
    preReqs:
        options: [clearInventory]
    onEnter:
        options: [storeAll]
    onLeave:
        options: [restoreAll]
    onJoin:
        options: [pvpOff, alwaysJoin]
    onPrestart:
        options: [pvpOff, teleportWaitRoom]
    onStart:
        options: [teleportIn, blockBreakOff, wgNoLeave, wgNoEnter, pvpOn]
        doCommands:
            - player fly stop
    onComplete:
        options: [teleportOut, wgResetRegion, wgClearRegion]
    onSpawn:
        options: [enchants, health=20, hunger=20, deEnchant, giveItems]
        items:
            - bread: 3
        enchants:
            - speed:3:640
        giveClass:
            default: gladiator  
    onDeath:
        options: [respawn, clearInventory]
    winner:
        options: [enchants, health=20, hunger=20, money=250, experience=350]
        enchants:
            - speed:1:900
            - resistance:1:900

Arenas.yml (just the battleground arena section):

arenas:
  grim:
    persistable:
      wgRegion: barena,ba-grim
    teamSize: 1+
    locations:
      '3': barena,-257.2065734863281,69.0,439.95172119140625,138.9625,39.348442
      '2': barena,-337.63861083984375,69.0,439.7489929199219,226.09595,20.505058
      '1': barena,-337.5901794433594,69.0,359.44659423828125,316.36694,35.28184
      '0': barena,-257.25299072265625,69.0,359.4870910644531,58.918182,17.887964
    nTeams: 2+
    type: Battleground
    spawns:
      '17':
        time: 0 125 0
        spawn: POTION:16457 1
        loc: barena,-297.43341064453125,69.0,352.29998779296875,-178.26997,67.73426
      '15':
        time: 0 125 0
        spawn: POTION:16457 1
        loc: barena,-297.583251953125,69.0,446.70001220703125,3.3188646,90.0
      '16':
        time: 0 125 0
        spawn: POTION:16457 1
        loc: barena,-250.4832305908203,69.0,399.6141662597656,-89.56926,82.67207
      '13':
        time: 0 125 0
        spawn: POTION:16396 1
        loc: barena,-321.5459289550781,83.0,423.7689514160156,353.45172,89.55708
      '14':
        time: 0 125 0
        spawn: POTION:16457 1
        loc: barena,-344.4800109863281,69.0,399.45880126953125,-4.0493255,84.52403
      '11':
        time: 0 125 0
        spawn: POTION:16396 1
        loc: barena,-273.476318359375,83.0,375.6190185546875,180.9997,90.0
      '12':
        time: 0 125 0
        spawn: POTION:16396 1
        loc: barena,-321.4322814941406,83.0,375.52117919921875,96.08368,84.04097
      '3':
        time: 0 45 0
        spawn: POTION:2 1
        loc: barena,-285.6933288574219,70.0,365.41015625,88.55362,86.215195
      '2':
        time: 0 45 0
        spawn: POTION:2 1
        loc: barena,-263.51055908203125,70.0,387.5030517578125,94.51248,90.0
      '10':
        time: 0 125 0
        spawn: POTION:16396 1
        loc: barena,-273.77972412109375,83.0,423.5696716308594,271.11,87.14129
      '7':
        time: 0 45 0
        spawn: POTION:2 1
        loc: barena,-309.4061584472656,70.0,433.5024719238281,268.89783,90.0
      '6':
        time: 0 45 0
        spawn: POTION:2 1
        loc: barena,-331.54119873046875,70.0,411.64300537109375,275.01776,86.939964
      '5':
        time: 0 45 0
        spawn: POTION:2 1
        loc: barena,-331.5316467285156,70.0,387.9726257324219,4.8456726,90.0
      '4':
        time: 0 45 0
        spawn: POTION:2 1
        loc: barena,-309.429443359375,70.0,365.4394836425781,1.5439453,75.947975
      '9':
        time: 0 45 0
        spawn: POTION:2 1
        loc: barena,-263.29150390625,70.0,411.3346252441406,188.3306,82.79282
      '8':
        time: 0 45 0
        spawn: POTION:2 1
        loc: barena,-285.41607666015625,70.0,433.16912841796875,178.26454,88.42971
    waitRoomLocations:
      '3': barena,-297.3554992675781,105.0,395.03887939453125,3.5590281,25.98093
      '2': barena,-292.7464599609375,105.0,399.6981201171875,97.05111,20.263494
      '1': barena,-297.6089172363281,105.0,404.1659851074219,184.54395,18.532158
      '0': barena,-301.7835693359375,105.0,399.4726867675781,271.59387,16.398188

**Comment by alkarinv** [comment]
I'm going to be adding a "courtyard" and "lobby".

Problem is Waitrooms are per arena, so until I choose an arena they can't be teleported in.

Lobbies will be per game type.  There will only be 1 courtyard.  those will be what you want.

**Comment by zrocweb** [comment]
Ok. What is the purpose of the Courtyard?

Also, what about the default class being given in addition to a selected class. Is that a bug or did I do something wrong?

**Comment by alkarinv** [comment]
so , there can be 1 waitroom for every arena.

There can only be 1 lobby for every game.  (so every arena for that game type can use that same lobby)

There is only 1 courtyard for all of battleArena.  so no matter what game you are playing, it's the same courtyard

**Comment by zrocweb** [comment]
Just to clarify you say 1 wait room for every arena?  So if I have 3 deathmatch arenas and 2 of the 3 have wait rooms the 2 that have will spawn in the respecitve wait room.  What about the 3rd.  Will just spawn and respective player spawn index

**Comment by alkarinv** [comment]
the 3rd won't be used if you have the "teleportWaitRoom" option.  It will consider the arena to be "invalid" and won't ever be available until you set the waitroom.  If you take out the teleportwaitroom option then all of them will work.
