### ISSUE TITLE
Disguise / undisguise

### ISSUE THREAD

**Issue by zrocweb** [alkarinv/BattleArena#135]
Do these still exist as valid options for all stages?  I tried and it returns them as invalid.

**Comment by alkarinv** [comment]
They should be, if they aren't I'll mark them as a bug.

1) disguiseAll=<name>: disguise all players with the given value

2) undisguise: undisguise players

**Comment by zrocweb** [comment]
Ok I tried them.. this is what I had for my onSpawn options :[..., ...., disguiseAll=Iron_Golem]

Is that not right? Or do I have to use an mob id?

**Comment by alkarinv** [comment]
try something like creeper.  If that doesn't work, then definitely a bug

**Comment by Malachiel87** [comment]
10:49:47 CONSOLE: [INFO] Couldn't parse Option DISGUISEALL value=creeper

**Comment by alkarinv** [comment]
I fixed the code to handle "DisguiseAll" but the value is technically "DisguiseAllAs", but in future versions both will work.

**Comment by Malachiel87** [comment]
it don't disguise, 0 errors in console :|
