### ISSUE TITLE
Multiple DeathMatch Events?

### ISSUE THREAD

**Issue by zrocweb** [alkarinv/BattleArena#136]
This may be a stupid question but I can't find anything in the wiki explaining it. so sorry.

I re-configured my one battleground arena to be a death match arena.  I have both scheduled and they are both listed in the bas.  How does this work now.  is it one major event hold those two separate events one after another??  I see u can't join a specifc dm event using the dm join <arena>

**Comment by zrocweb** [comment]
Is there a way, perhaps in the future (I know you are busy with this baby.. and should be proud of it.. its awesome) that you can allow to join more than one event.  so for instance if you have like I do, two or more DM events, allow a player to join one of them with having to play the first event.

**Comment by alkarinv** [comment]
so they will run after each other in a loop now.  Since both probably have an open phase, players can just keep joining.

**Comment by zrocweb** [comment]
yes. correct. but ever since I did that as well as put in respawnWithClass, everyone only gets one kill and there is no respawn.....????

**Comment by zrocweb** [comment]
There is definately a bug with the respawnWithClass option.  If I take it out and put respawn it respawns. otherwise it just ends the match

EDIT: Hold that thought... I jsut changed to respawn and it still does is only one kill and no respawn.. wtf... Any suggestions?

**Comment by zrocweb** [comment]
Ok I just changed a few things around.  Either I'm doing something wrong or I'm sorry to report a bug for you.

I took out option 'teleportWaitRoom' from the onJoin stage and just replaced it with teleportIn.  Respawns take place on death now if is a option in the onDeath stage.  

I opened a new issue so you can track these easier rather than this huge thread of of messages..

**Comment by alkarinv** [comment]
can you pastebin me the config?

I think theres probably a fix in there.

**Comment by zrocweb** [comment]
Ok Here are all the pastebin links:

BA Config: http://pastebin.com/Z3HWbLsg
BattleGround: http://pastebin.com/nvNggy1Z
DeathMatch: http://pastebin.com/2JgiRGUB
Arenas: http://pastebin.com/dzPRarev

as I stated earlier, I removed the teleportWaitRoom from my one arena's config as it was not respawning with it in.

**Comment by alkarinv** [comment]
Deathmatch: http://pastebin.com/BMfu3gGX
BattleGround: http://pastebin.com/gb64FVb9

You have 2 teleportIn inside of Deathmatch, so that will teleport them twice to the spawn.  

Everything else looks fine, maybe you can give me your ip so I can check it out?  Would have to be later today?

**Comment by zrocweb** [comment]
Yeah. I had to put the first teleportIn on join cause it was not respawing after a kill if I just left them hang out where ever they joined from until the match started.. So I had to place it there and let them roam around the arena (not preferred)

My IP is:198.12.123.52  Let me know when u are gonna pop on timeline if u think you can give me one and I will make sure I am there!

**Comment by alkarinv** [comment]
Why not just take the first teleportIn out, then let them teleportIn in onStart, or onPrestart?

anyway, i can get on about 5-6 EST.

**Comment by zrocweb** [comment]
What I and was onJoin: [teleportWaitRoom, ..., ..., ....]  due to the waitRoom issue, I removed it altogether and just had the teleportIn, in the onStart.  The same thing was happening.  They would get killed and kicked out of the arena.

Ok will look for you around that time.. Will be here!! Thanks!!

**Comment by zrocweb** [comment]
Weird thing... I receive the 3.8.6 update today and just put that online.
I created a custom arena config (TDM) and then create an arena for it from an existing arena.

I place the spawnWaitRoom  in the onJoin and it works not after being killed.

Additionally, I noticed the first time I played it it either ended early or I just didn't notice the time go by so quickly, but it did not announce the end of the game nor did it give the winner of the matches (player two) it's winnings. but it gave both players the losers items.  which idicates to me that both players were pushed out of the match somehow.

I am testing on regular modes node. perhaps this is being cause by my TDM custom config.

**Comment by zrocweb** [comment]
Again, weird.  I just started a DeathMatch game (with spawnWaitRoom).  Shot and killed one time and match was over. How did it work in my custom TDM but not in this.  Ohhhhh wait.. its cause DeathMatch is a Phase thats right.. I'm gonna try to change DeathMatch from phase to Queue and see what happens...

**Comment by zrocweb** [comment]
Ok definately someothing with the custom arenaconfig.... this time no wait room spawn, but match played out entirely and winner receive winning msg and items......  However I did not exchange kills this time. I focused on one player get all the kills... so will have to see if the exchange is part of the glitch or whatever... Also, I have the TDM arena setup as arenaClass: Paintball.  If this helps.

**Comment by zrocweb** [comment]
ok.. just keeps getting weirder and weirder.  Replayed in custom TDM match.  no waitroom (is set up to go there) spawn, but match was played out and winner received msg and items...

I then play regular dm match, no waitroom (is set up to go there) spawn and one kill, end of match for dead player.

I changed my TDM custom arena to the DeathMatch class.  waitroom spawned to waitroom. match played out and winner rcv'd msg and items.  WEIRD!!! no rhyme or reason.....
