### ISSUE TITLE
5 Issues detected

### ISSUE THREAD

**Issue by zrocweb** [alkarinv/BattleArena#137]
5 Issues:
- respawnWithClass - potential bug - does not respawn with class and does not force respawn
- teleportWaitRoom - if placed in onJoin stage does not allow [respawn] option in onDeath stage in all arenas
- when using signs and selecting a class, player is given the class but when spawned into the match, is also give a default class which needs to be in the config for that arean otherwise if the player does not select a class he will not have any weapons to attack/defend.  I would think the default class should only be give to a player that has not selected a class.
- using pvpOff in onJoin stage while waiting for match to begin does and does not work.  Its weird.  If I hit a player with my hand (no weapon) one time, nothing happens. But if I continue to swing it will cause harm and then if u put a weapon in hand it will really cause harm.
- blockBreakOff and blockPlaceOff are not working in onJoin stage when teleportIn to the arena prior to match starting.  Seems to work okay if placed in onStart stage though.

If I'm doing something wrong, please tell me....  to recap what I'm doing:

For my Deathmatch arena (had 2 now only 1 - put it back to battleground for now). I had teleportWaitRoom and was using classes in the waitroom for player selection.  Upon a player death in the match, the player would get thrown out of the match and would end when all players are dead, like lastManStanding, but victoryCondition is highestKills.  Once I took teleportWaitRoom out of onJoin staged and replaced with teleportIn, all seemed to work like it should, except could not select class as there was no waitroom for class selection. SO had to assign a default class.

EDIT:

After a little more testing.. The teleportWaitRoom placed in the onJoin stage is currently only affecting the non-queue arena types (deathmatch, etc..).  It's working fine with Battleground arena.  Testing with Arena and others now...

The blockBreakOff and blockPlaceOff may be do to my world guard global region for that area.  I have to check it again.  I have a two wg regions for each of my arenas. one is to control the mob spawning across the entire (wide) area of the arena region (outside, inside, etc..).  Then I have an inner region just for BA for the clearing of drops and resetting the region back to it normal state should anything accidentally get broken, etc...

**Comment by alkarinv** [comment]
1) respawnWithClass: I think thats a config issue, let me see which one you are using

2) same thing, can I see your configs for FFA, dm.  I'll see if I can recreate that locally

3) Yeah, that just sounds like a bug, once given a class any other classes should replace that.  Or not replace... hmm

4) That is strange.. so onJoin for Queue based? or JoinPhase?

5) I bet its the same issue as #4, give me some clues there and I can get both fixed.

**Comment by zrocweb** [comment]
Sent u my pastebin configs in the other thread.
