### ISSUE TITLE
Not an Issue;- Question

### ISSUE THREAD

**Issue by zrocweb** [alkarinv/BattleArena#139]
Is there anything in BA that will allow an arena to go with unlimited time (yes I know that is an option and can be set) and then while in unlimited time, something that is tested for say a game has been completed via a command block or something of that nature.  I say this in terms of an large battleground type map with objectives, like CTF, etc...  I'm not looking for CTF, I just used that as an example.  I have a large map I made that is very interactive for the players that require them to do things to their opponents bases prior to winning a match. But it would require unlimited time but would need to trigger the end of match to BA when the game has been actually completed.  Did this come out right?

**Comment by alkarinv** [comment]
So you can always set the winner through a command block like.
- /arena winner <player name>

That will make them win. But I can't really have stages within stages right now :( though thats something I've thought a lot about.  Substages that each could be an entire phase

<pre>
Skirmish:
    matchTime: -1
</pre>

**Comment by zrocweb** [comment]
Ok good to know. I will try that and see if I can get it to work.. Cool

**Comment by zrocweb** [comment]
One question: did any of the configs changes with 3.8.6? Cause I just threw it in there and didn't delete any of the configs. 

----- Original Message -----

**Comment by alkarinv** [comment]
None of the configs changed with this release.  It just has updates and fixes
