### ISSUE TITLE
Creative bug

### ISSUE THREAD

**Issue by Adondriel** [alkarinv/BattleArena#14]
While in creative mode, if you join /arena join and you die, what ever item you had in your creative inventory you will spawn back with.

My server has the arenas set up in a separate world.
(using multiverse)
I did not see any errors.

**Comment by alkarinv** [comment]
What version of BattleArena are you running?

Players should be respawning back where they are joined.

**Comment by Adondriel** [comment]
I am running 3.6.7(by the plugin/yml) but i feel like i just updated it yesterday. Yes they respawn back to the main spawn, but with whatever item they had in creative inventory when they joined.

**Comment by Adondriel** [comment]
I'll be sure to get the newest version and have my players test it. But my server has a creative world where they have creative mode, so i dont want people to abuse that.

**Comment by alkarinv** [comment]
Its probably a different problem then.  Players should be going back to exactly where they joined from.. not to spawn.

Can you give me your server ip so I can check it out?  PM me on bukkit with your info.

**Comment by alkarinv** [comment]
Also, is it every time they die, or do they have to "exit to title screen" then come back? 

If it's the exit to title screen its an issue with multiverse log in bug (but I should be able to make a workaround).  Just want to verify

**Comment by Adondriel** [comment]
I'm pretty sure it is everytime they die, ill go ask them.

**Comment by Adondriel** [comment]
oh no they do go back to where they started... i think, ill ask them that too lol

**Comment by alkarinv** [comment]
I'm going to assume this bug is fixed now that I've made changes and haven't heard any reports of it again.

if it's not fixed just reopen this ticket!
