### ISSUE TITLE
/arena reload   : Possibly duplicating / triplicating class loading

### ISSUE THREAD

**Issue by zrocweb** [alkarinv/BattleArena#140]
Alk,

I have been noticing an extensive amount of the BA log msgs inconsole as well as server log during in-game /arena reload  (primary reload ingame due to my testing of whats been going on...).  What I've noticed is that it looks like when you issue a reload in-game it's registering each class at least twice, sometimes more than 2 times and possibly could be the reason for the server overload (separate issue I submitted).  Not sure on that yet, still tracking....

But I've attached a normal server log extract of BA as well as a in-game or console reload:

Server Restart: http://pastebin.com/xXePg8vf
Issue Reload: http://pastebin.com/WMAx4YCJ

**Comment by alkarinv** [comment]
I've noticed that too but havent put in the fix for it yet. It isn't a serious issue as multiple class/arena/game reloads don't actually create new ones, they just replace the previous.  So there aren't 3 versions running around, just one.

**Comment by zrocweb** [comment]
gotcha
