### ISSUE TITLE
randomRespawn and respawnWithClass?

### ISSUE THREAD

**Issue by zrocweb** [alkarinv/BattleArena#141]
Can both of these be an option for the onDeath Stage or just one.  I would like the player to respawn at a random player spawn point as well as with their selected class!

**Comment by alkarinv** [comment]
Yes, they can be used together!

**Comment by zrocweb** [comment]
ok. I have not tried yet but will give it a go.    I know there is still that bug with the respawnWithClass but not sure if it still exist or not now that things are running the way they should be. I will report back after more testing..
