### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zrocweb** [alkarinv/BattleArena#142]
Enabled / Disable Arenas: 

I was working on some of my arenas this morning and I had 15+ players online.  During my edits to the arenas a few players joined in.  Needless to say I tried to disable the arena I was working on, both in-game as well as through editing the respective arenas config file to set it to disabled.  Neither worked?

Arena Info:  The itemSpawns value shown in the arena info message does not reflect the number of item spawns.  It looks like its the same as the player spawns.

**Comment by alkarinv** [comment]
should be
- /arena disable
- /skirmish disable
  or
- /arena disable all

that isnt working?

**Comment by zrocweb** [comment]
negative.  If I type arena, dm, bg, skirmish, etc..  disable it does not disable the arena(s).  same with enable.  I manually set it to disabled and re-uploaded the file.  One, I was still allowed to to join the arena and two, could not re-enable it in-game or console. 

EDIT:  Hey did u di u get my emails last night.  The BG crashes was being cause by something in the itemSpawns.. I removed all the spawns and recreated them and all is well!  DM and BG!!  With Scoreboard and without!

**Comment by alkarinv** [comment]
Yeah, got that email, will be looking at that.

I can't get the disable to not work.
- /arena disable
- /arena join
  "The Arena is currently disabled"
  "Enabled pb, sspleef, Spleef, Colosseum, DeathMatch, tourney, espleef, FreeForAll, ctf, pk, sk, oitc, Duel, Battleground"
- /arena enable
- /arena join
  and I join just fine

**Comment by zrocweb** [comment]
ok I will try it again.  What if you try bg disable or dm disable?  what do u get

**Comment by alkarinv** [comment]
Same thing for all commands.  They all seem to work for me :(

**Comment by zrocweb** [comment]
Ok don't understand why it didn't work before.. Worked this time... At least for current session. which leads me to my next question. After disabling one or all of the arenas it does not look like it's actually updating the enabled flag in the specific arena config file.  So I assume this is just for the current up-time of the server and will reset upon a restart.

**Comment by alkarinv** [comment]
so, the config file enabled: is a little misleading... they are all enabled right now.  I kept that in because I want to be able to alter the configs in game, in which case enabled will flip to false.  but I havent written the save function for the configs.  (Mainly b/c it will save the yaml file all weird and will get rid of comments)

**Comment by zrocweb** [comment]
all is good!!
