### ISSUE TITLE
Players Die and Prematureally get kicked from match

### ISSUE THREAD

**Issue by zrocweb** [alkarinv/BattleArena#144]
Trying to keep these separate for you to track easier.  This goes back to previous issue that we closed, but it still a slight bug:

When using the teleportWaitRoom option in any of the stages, matches will sometime end prematurely, especially if a player dies and does not respawn immediately. 

EDIT: I think it might have something to do with DeathChest. If I don't break the tombstone of the dead player, it will respawn the dead player like it should. But if I break the tombstone before he respawns, that dead player is kicked from the match.

**Comment by zrocweb** [comment]
Ok. tested with three in the game in a DM match.  Seems like if a player gets killed and does not respawn (user clicks the respawn button on their gui), the match ends right away.... BUT NOT ALL THE TIME

**Comment by alkarinv** [comment]
Players have 15 seconds after they die to rejoin the match.  If they don't I consider them to have "left" the game.  If them leaving the game leaves only 1 team remaining then the match ends.

**Comment by zrocweb** [comment]
ahh. didn't know that good to know.. Will have to make mention of that in the pre-lobbies... 

----- Original Message -----

**Comment by zrocweb** [comment]
Also, did see one thing regarding a player leaving a match, actually left the server too. The entire match ended. Not sure if it was a fluke or what but figured I would bring it to your attention

**Comment by alkarinv** [comment]
I have a fix for this now. 
3.8.6.2.

https://dl.dropboxusercontent.com/u/38069770/jars/BattleArena.jar

Let me know if that fixes the issue!

**Comment by zrocweb** [comment]
I will try it out. What is the fix?  Do they still have that 15 secs.??? 

Thanks man!

**Comment by alkarinv** [comment]
They still have 15 seconds.. I should make an option for that though.
