### ISSUE TITLE
Tourneys Not Working

### ISSUE THREAD

**Issue by SteveCookTU** [alkarinv/BattleArena#147]
When I start a tourney, it will say the round will begin in 20 seconds but it never TPs anyone.

**Comment by alkarinv** [comment]
can you pastebin your arenas.yml and the game config of the tourney you are trying to run?

it might be that there are no arenas that can fit that game? possibility.

**Comment by SteveCookTU** [comment]
Arena.yml:
http://pastebin.com/WTww8Wi7
FreeForAll.yml:
http://pastebin.com/5wWgg59p

**Comment by alkarinv** [comment]
oh! thats my bad. Right now you can only run tourneys on games that have a queue.  So thats why its getting stuck.  But you shouldnt need to know that.

**Comment by SteveCookTU** [comment]
So what should I do?
Change the the type of entry or whatever its called?
Cause it didn't work with skirmish either (We originally had a skirmish arena)

**Comment by alkarinv** [comment]
So try doing it with Skirmish, as long as you have one arena it should work.

If that doesnt work, let me know your ip.

ingame: alkarin_v

I'll need "arena.admin" perms to figure anything out

**Comment by SteveCookTU** [comment]
ok I will try it out and get back to you!

**Comment by alkarinv** [comment]
Did this work?

**Comment by SteveCookTU** [comment]
No it didn't. :( I really need the help. Also, it acts as if the tourney never started once it says that the round will start in 20 seconds.

**Comment by alkarinv** [comment]
What's your ip?

**Comment by SteveCookTU** [comment]
192.210.234.5:25865

**Comment by alkarinv** [comment]
Looks like 3.8.7+ fixes this issue.. going to close ! :)
