### ISSUE TITLE
Espleef auto not working.

### ISSUE THREAD

**Issue by Masterofjumping** [alkarinv/BattleArena#149]
I have not been able to use "/espleef auto". It just gives the unknown command message. 

When testing I used "/ffa auto" and it worked so this is just the spleef one not working. As well "/spleef auto" also does not work.

I am on the latest versions of both battlearena and spleef arena.

Hope it is just me being slightly hopeless, if you need more information just ask.

**Comment by alkarinv** [comment]
So now that you can create "custom" games just by making a new config, i thought that the ESpleefConfig.yml was redundant and took it out.

Put this

https://gist.github.com/alkarinv/5421693

into your ArenaSpleef folder and it should work just fine.

Probably use this too

http://dev.bukkit.org/media/files/695/538/BattleArena.jar

**Comment by Masterofjumping** [comment]
Thanks, I just thought that I could use the Espleef config from previously and it would take it as a custom event but now I realise you need to have a different config.

**Comment by alkarinv** [comment]
Yeah, not completely the same but similar.  let me know if it doesnt work!

**Comment by Masterofjumping** [comment]
It seems that auto is not working at all for some things. I cannot use "/pb auto" or "/paintball auto" as it just says unknown command.

The same is still happening with "/spleef auto" and "/espleef auto".

**Comment by alkarinv** [comment]
so /espleef auto, should work as it's a join phase

Spleef and Pb are by default joinType: Queue, which are not "startable", you can always change them, but if you do so you'll have to do a complete restart.

**Comment by Masterofjumping** [comment]
Thanks, the Pb works.

Espleef still does not work but it is not too important for now.
