### ISSUE TITLE
Tourneys Not Working Again :(

### ISSUE THREAD

**Issue by SteveCookTU** [alkarinv/BattleArena#150]
So earlier I posted something about tourneys and someone came on and fixed it. Now, they aren't working again! I tried this with Skirmish and FFA

**Comment by SteveCookTU** [comment]
apparently there is no arena that can fix certain parameters that the tourney wants. Even though they are altered and set in the config to what the tourney wants.

**Comment by alkarinv** [comment]
gah, so it should just be like 2 teams and a fixed number of players.  Im kind of in and out tonight, but tomorrow I can probably hop on.

**Comment by SteveCookTU** [comment]
Nvm Got it working! Apparently the arena type was set to Arena XD

**Comment by alkarinv** [comment]
oh! yay!
