### ISSUE TITLE
Dueling Not Timing Correctly

### ISSUE THREAD

**Issue by SteveCookTU** [alkarinv/BattleArena#151]
If I want to duel someone with skirmish, it makes the match end in less then a second! I would really appreciate the help!

**Comment by alkarinv** [comment]
herm, pastebin your skirmish config... but it might be a bug... if it is a bug, i'll be off and on tonight, otherwise it will have to be tomorrow

**Comment by SteveCookTU** [comment]
NVM Omg I think im stupid

**Comment by alkarinv** [comment]
lol, what was it?

Also, not going to be on today for like another 10-12 hours. :(
