### ISSUE TITLE
Tourneys Not Working Again :(

### ISSUE THREAD

**Issue by SteveCookTU** [alkarinv/BattleArena#153]
In the even of a tourney, the second set of rounds from the victor of both starting rounds does not start and make the two people verse

**Comment by SteveCookTU** [comment]
It works when there is an uneven number of players

**Comment by alkarinv** [comment]
ok, will try to fix this tonight/tomorrow .. going to be gone all today :(

**Comment by SteveCookTU** [comment]
I also have a ticket on BattleTracker

**Comment by alkarinv** [comment]
I guess you do have battletracker.

Whats your ip?

**Comment by SteveCookTU** [comment]
192.210.234.5:25865

**Comment by SteveCookTU** [comment]
anything fixed yet?

**Comment by alkarinv** [comment]
I tried with your skirmish config, and arenas.  And it seems to be working for me, so at this point I'm really confused as to what the real issue is... You can try the newest version... but I'm doubtful.  I need to think of a new tact to find out why its not working.

Latest bukkit link
http://dev.bukkit.org/media/files/696/248/BattleArena.jar

**Comment by SteveCookTU** [comment]
Ok
I will try to use this and see if it works. Maybe it's one of our plugins?

**Comment by alkarinv** [comment]
I mean thats possible, but.... its more likely my bad.  I just can't think of a plugin that would stop tournaments from working but not normal arenas.

**Comment by SteveCookTU** [comment]
Want me to tell u my plugins?

**Comment by alkarinv** [comment]
sure, I guess you might as well

**Comment by SteveCookTU** [comment]
WorldEdit, NoCheatPlus, BukkitCompat, BattleTracker, Buycraft, Vault, Multiverse-Core, PermissionsEx, Playerheads, Wither, CombatTag, ItemChanger, WorldGuard, PvPTimer, LazyShop, iConomy, Custom Plugin (idk what this is XD), AntiAd, ModifyWorld, Votifier, SuperSpleef, Enchanter, mcMMO, MobArena, Essentials, EssentialsSpawn, Multiverse-Portals, Multiverse-Inventories, ChestShop, EssentialsChat, Factions, and of course, BattleArena

**Comment by SteveCookTU** [comment]
ItemChanger and LazyShop are made by me

**Comment by SteveCookTU** [comment]
Oh the Custom Plugin is also something I made where when someone makes a sign that says "ffa create", it creates an FFA match

**Comment by alkarinv** [comment]
BattleArena/config.yml

allowPlayerCreation: true

allows people to start a JoinPhase event just by joining.

**Comment by SteveCookTU** [comment]
XD thats easier let me take the plugin out and see if it affected anything!

**Comment by SteveCookTU** [comment]
probably not though

**Comment by SteveCookTU** [comment]
what does it mean by silent in the player options for twhen they open it?

**Comment by SteveCookTU** [comment]
nvm

**Comment by SteveCookTU** [comment]
ok also we have another problem, it is silent when user creates it but I turned silent off and the time is still 3 minutes even though i set it to 60 seconds

**Comment by SteveCookTU** [comment]
Did not work :/

**Comment by SteveCookTU** [comment]
Any news yet?

**Comment by alkarinv** [comment]
sorry man, I'll have to get back to the drawing board over the weekend... swamped till Saturday :(
