### ISSUE TITLE
AutoUpdater

### ISSUE THREAD

**Issue by zrocweb** [alkarinv/BattleArena#157]
I just an FYI.  I'm now getting two files of the same update.  One version is going to /plugins/updates and the same file version is now going to /plugins/battlearena/updates/

Also, I placed the new version and restarted the server but it still thought my current version (3.8.7.3) was older and re-downloaded...  

I know you have bigger fish to fry, so just letting you know!!!

**Comment by alkarinv** [comment]
No, that is pretty big fish to me.  I can't take a look for several hours, but I'll definitely fix this. And it's not like the tourney bug, which is more difficult...
