### ISSUE TITLE
Respawn With Class

### ISSUE THREAD

**Issue by Syfers96** [alkarinv/BattleArena#158]
I can select my class . Play with it . But when I die I do not respawn with .

Look my Configuration .

DeathMatch:
    enabled: true
    joinType: JoinPhase
    victoryCondition: highestKills
    database: dm
    rated: true
    prefix: "&8[DeathMatch]&e"
    nTeams: 2+
    teamSize: 1
    announcements: ### Override the match victory announcement as the event has one too
        onVictory:  [ dontannounce ] 
    defaults:
        options: [woolTeams]
    preReqs:
        options: [clearInventory]
    onEnter:
        options: [storeAll, blockBreakOff]
    onLeave:
        options: [restoreAll]
    onJoin:
        options: [teleportWaitRoom, pvpOff, hunger=20, blockBreakOff]
    onOpen:
        options: [pvpOff]
    onStart:
        options: [pvpOn, teleportIn, hunger=20, respawnWithClass]  
    onComplete:
        options: [teleportOut]
    onSpawn:
        options: [health=20, hunger=20, respawnWithClass]
    onDeath:
        options: [respawn, clearInventory]
    winner:
        options: [enchants, money=1,experience=300, health=20, hunger=20]

HELP ME ?

**Comment by alkarinv** [comment]
Hey Stryfer, sorry I've been in the middle of finals.  I will make sure this works on next release... should be very soon.

**Comment by alkarinv** [comment]
Well this has been around for a while, but I know this is fixed in BattleArena 3.9.6+.
