### ISSUE TITLE
[Pull Request] Add lore option to item config

### ISSUE THREAD

**Issue by netherfoam** [alkarinv/BattleArena#159]
Here's a parse function for parsing lore, it would be awesome if you could add it to your item parsing! I've explained on the comments section of BattleArena on devbukkit, but basically I want to be able to tag items with custom lore.

<pre>
    public static void testLore(){
        parseLore("stone_sword: sharp:1 1 lore:\"Epic Sword of Doom;&6Elite Item&5\" kb:2");
        parseLore("stone_sword: sharp:1 1 lore: \"Epic Sword of Doom;&gElite Item&5\" kb:2");
        parseLore(""); //No output
        parseLore("stone_sword: sharp:1 1 kb:2"); //No output
        parseLore("stone_sword: sharp:1 1 lore: \"\" kb:2");
    }
    static boolean DEBUG = true;

    private static final Pattern LORE_PATTERN = Pattern.compile("lore: ?\".*\"");
    public static LinkedList<String> parseLore(String str){
        try{
            Matcher matcher = LORE_PATTERN.matcher(str);
            if(matcher.find()){
                int start = matcher.start(); //This only takes the first match
                int end = matcher.end(); 
                
                //Remove the "Lore: " part
                //Remove the quotes
                //Possible issue: If you want quotes in your lore...?
                String part = str.substring(start, end).replaceFirst("lore: ?", "").replaceAll("\"", ""); //Strip Lore: and quotes.
                //Replace color codes
                part = ChatColor.translateAlternateColorCodes('&', part);
                //Now we can split it.
                String[] lines = part.split(";");
                //DEBUG
                if(DEBUG) System.out.println(Arrays.toString(lines));
                //Create a new list
                LinkedList<String> lore = new LinkedList<String>();
                //Add all the sections to the list
                for(String s : lines) lore.add(s);
                //Success!
                return lore;
            }
        }
        catch(Exception e){
            e.printStackTrace(); //Damn.
        }
        return null;
    }
</pre>

**Comment by alkarinv** [comment]
I like it! 

Just go ahead and change it! will add.

**Comment by netherfoam** [comment]
Awesome, I will start work on this in a few hours.

**Comment by netherfoam** [comment]
Pull request sent.
