### ISSUE TITLE
Losing gear when leaving the arena

### ISSUE THREAD

**Issue by joebladon** [alkarinv/BattleArena#16]
So the bug occurs when you die in a arena. You get teleported back to where you were and have your items restored. But if you then type /arena leave before the fight you were in has ended your restored items get cleared.

**Comment by alkarinv** [comment]
Alright, that definitely sounds like a bug.  I'll check that out and try to get back to you.  Today is hectic though, and the weekend is bad as well, but I'll try to get on this.

**Comment by alkarinv** [comment]
Fixed.  Will be released in version 3.6.8.5+
