### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by B3fuddled** [alkarinv/BattleArena#164]
Running Bukkit 1.5.2 R0.1 / Java 7 64-bit
Installed BattleArena & ArenaPaintball & BattleTracker
Restarted Server.. no errors

Created a Paintball Arena, and was able to start a game.  Restarted Server and similar errors appeared for both ArenaPaintball & BattleArena.  Tried to create a defaultConfig.yml in path E:\Bukkit-server\default_files\competitions\ but it did not fix the problem.

[SEVERE] ArenaPaintball PaintballConfConfig.yml could not be loaded!
[SEVERE] E:\Bukkit-server\default_files\competitions\defaultConfig.yml
[SEVERE] java.lang.NullPointerException
[SEVERE]    at mc.alk.arena.controllers.APIRegistrationController._registerCompetition(APIRegistrationController.java:209)
[SEVERE]    at mc.alk.arena.controllers.APIRegistrationController.registerCompetition(APIRegistrationController.java:172)
[SEVERE]    at mc.alk.arena.controllers.APIRegistrationController$DelayedRegistrationHandler.run(APIRegistrationController.java:70)
[SEVERE]    at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:53)
[SEVERE]    at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
[SEVERE]    at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:513)
[SEVERE]    at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
[SEVERE]    at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
[SEVERE]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
[SEVERE]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
[SEVERE] java.lang.NullPointerException
[SEVERE]    at mc.alk.arena.serializers.ConfigSerializer.getArenaType(ConfigSerializer.java:260)
[SEVERE]    at mc.alk.arena.controllers.APIRegistrationController._registerCompetition(APIRegistrationController.java:220)
[SEVERE]    at mc.alk.arena.controllers.APIRegistrationController.registerCompetition(APIRegistrationController.java:172)
[SEVERE]    at mc.alk.arena.controllers.APIRegistrationController$DelayedRegistrationHandler.run(APIRegistrationController.java:70)
[SEVERE]    at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:53)
[SEVERE]    at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
[SEVERE]    at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:513)
[SEVERE]    at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
[SEVERE]    at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
[SEVERE]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
[SEVERE]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

[SEVERE] BattleArena defaultConfConfig.yml could not be loaded!
[SEVERE] E:\Bukkit-server\default_files\competitions\defaultConfig.yml
SEVERE] java.lang.NullPointerException
[SEVERE]    at mc.alk.arena.controllers.APIRegistrationController._registerCompetition(APIRegistrationController.java:209)
[SEVERE]    at mc.alk.arena.controllers.APIRegistrationController.registerCompetition(APIRegistrationController.java:172)
[SEVERE]    at mc.alk.arena.controllers.APIRegistrationController$DelayedRegistrationHandler.run(APIRegistrationController.java:70)
[SEVERE]    at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:53)
[SEVERE]    at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
[SEVERE]    at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:513)
[SEVERE]    at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
[SEVERE]    at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
[SEVERE]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
[SEVERE]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

**Comment by B3fuddled** [comment]
Hmm.. I think I may have found what is causing this.  When I edited a few of the yml files, my text editor created a yml.bak file also, which I hadn't deleted (eg: config.yml.bak and ArenaConfig.yml.bak).

It looks like the plugin loads these .bak files too (it looks for  ".yml" anywhere in the filename?).  When these superfluous files were deleted, my error messages also disappeared.

It appears that this holds true for the ArenaPaintball plugin as well.

**Comment by alkarinv** [comment]
Sorry, it's finals time for school. That's definitely the error, I've made a filter to filter out the extensions that don't match.  That will be out in the new version I will release soon.
