### ISSUE TITLE
SEVERE Error

### ISSUE THREAD

**Issue by Masterofjumping** [alkarinv/BattleArena#165]
When using a /<Event> auto command to start an event it is giving me this following error.

This is happening after updating server & battlearena to latest versions. I though it was something to do with the message config so I replaced it but it has not helped.

10.05 07:38:12 [Server] SEVERE at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
10.05 07:38:12 [Server] SEVERE at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
10.05 07:38:12 [Server] SEVERE at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:581)
10.05 07:38:12 [Server] SEVERE at net.minecraft.server.v1_5_R3.DedicatedServerConnection.b(SourceFile:30)
10.05 07:38:12 [Server] SEVERE at net.minecraft.server.v1_5_R3.ServerConnection.b(SourceFile:35)
10.05 07:38:12 [Server] SEVERE at net.minecraft.server.v1_5_R3.PlayerConnection.d(PlayerConnection.java:109)
10.05 07:38:12 [Server] SEVERE at net.minecraft.server.v1_5_R3.NetworkManager.b(NetworkManager.java:292)
10.05 07:38:12 [Server] SEVERE at net.minecraft.server.v1_5_R3.Packet3Chat.handle(Packet3Chat.java:44)
10.05 07:38:12 [Server] SEVERE at net.minecraft.server.v1_5_R3.PlayerConnection.a(PlayerConnection.java:840)
10.05 07:38:12 [Server] SEVERE at net.minecraft.server.v1_5_R3.PlayerConnection.chat(PlayerConnection.java:883)
10.05 07:38:12 [Server] SEVERE at net.minecraft.server.v1_5_R3.PlayerConnection.handleCommand(PlayerConnection.java:965)
10.05 07:38:12 [Server] SEVERE at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchCommand(CraftServer.java:523)
10.05 07:38:12 [Server] SEVERE at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
10.05 07:38:12 [Server] SEVERE at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
10.05 07:38:12 [Server] SEVERE at mc.alk.arena.executors.BaseExecutor.onCommand(BaseExecutor.java:252)
10.05 07:38:12 [Server] SEVERE at java.lang.reflect.Method.invoke(Method.java:601)
10.05 07:38:12 [Server] SEVERE at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10.05 07:38:12 [Server] SEVERE at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
10.05 07:38:12 [Server] SEVERE at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10.05 07:38:12 [Server] SEVERE at mc.alk.arena.executors.EventExecutor.eventCancel(EventExecutor.java:70)
10.05 07:38:12 [Server] SEVERE at mc.alk.arena.executors.EventExecutor.cancelEvent(EventExecutor.java:94)
10.05 07:38:12 [Server] SEVERE at mc.alk.arena.controllers.BAEventController.cancelEvent(BAEventController.java:197)
10.05 07:38:12 [Server] SEVERE at mc.alk.arena.competition.events.ReservedArenaEvent.cancelEvent(ReservedArenaEvent.java:147)
10.05 07:38:12 [Server] SEVERE at mc.alk.arena.competition.events.Event.cancelEvent(Event.java:169)
10.05 07:38:12 [Server] SEVERE at mc.alk.arena.competition.events.Event.eventCancelled(Event.java:181)
10.05 07:38:12 [Server] SEVERE at mc.alk.arena.controllers.messaging.ReservedArenaEventMessager.sendEventCancelled(ReservedArenaEventMessager.java:26)
10.05 07:38:12 [Server] SEVERE at mc.alk.arena.controllers.messaging.EventMessager.getChannel(EventMessager.java:26)
10.05 07:38:12 [Server] SEVERE at mc.alk.arena.objects.messaging.AnnouncementOptions.getDefaultChannel(AnnouncementOptions.java:104)
10.05 07:38:12 [Server] SEVERE java.lang.NullPointerException
10.05 07:38:12 [Multicraft] Skipped 65 lines due to rate limit (60/s)
10.05 07:38:07 [Server] SEVERE at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
10.05 07:38:07 [Server] SEVERE at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:581)
10.05 07:38:07 [Server] SEVERE at net.minecraft.server.v1_5_R3.DedicatedServerConnection.b(SourceFile:30)
10.05 07:38:07 [Server] SEVERE at net.minecraft.server.v1_5_R3.ServerConnection.b(SourceFile:35)
10.05 07:38:07 [Server] SEVERE at net.minecraft.server.v1_5_R3.PlayerConnection.d(PlayerConnection.java:109)
10.05 07:38:07 [Server] SEVERE at net.minecraft.server.v1_5_R3.NetworkManager.b(NetworkManager.java:292)
10.05 07:38:07 [Server] SEVERE at net.minecraft.server.v1_5_R3.Packet3Chat.handle(Packet3Chat.java:44)
10.05 07:38:07 [Server] SEVERE at net.minecraft.server.v1_5_R3.PlayerConnection.a(PlayerConnection.java:840)
10.05 07:38:07 [Server] SEVERE at net.minecraft.server.v1_5_R3.PlayerConnection.chat(PlayerConnection.java:883)
10.05 07:38:07 [Server] SEVERE at net.minecraft.server.v1_5_R3.PlayerConnection.handleCommand(PlayerConnection.java:965)
10.05 07:38:07 [Server] SEVERE at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchCommand(CraftServer.java:523)
10.05 07:38:07 [Server] SEVERE at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
10.05 07:38:07 [Server] SEVERE at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
10.05 07:38:07 [Server] SEVERE at mc.alk.arena.executors.BaseExecutor.onCommand(BaseExecutor.java:252)
10.05 07:38:07 [Server] SEVERE at java.lang.reflect.Method.invoke(Method.java:601)
10.05 07:38:07 [Server] SEVERE at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10.05 07:38:07 [Server] SEVERE at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
10.05 07:38:07 [Server] SEVERE at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10.05 07:38:07 [Server] SEVERE at mc.alk.arena.executors.ReservedArenaEventExecutor.open(ReservedArenaEventExecutor.java:41)
10.05 07:38:07 [Server] SEVERE at mc.alk.arena.executors.ReservedArenaEventExecutor.openIt(ReservedArenaEventExecutor.java:73)
10.05 07:38:07 [Server] SEVERE at mc.alk.arena.executors.ReservedArenaEventExecutor.openEvent(ReservedArenaEventExecutor.java:107)
10.05 07:38:07 [Server] SEVERE at mc.alk.arena.competition.events.ReservedArenaEvent.autoEvent(ReservedArenaEvent.java:45)
10.05 07:38:07 [Server] SEVERE at mc.alk.arena.competition.events.ReservedArenaEvent.openEvent(ReservedArenaEvent.java:41)
10.05 07:38:07 [Server] SEVERE at mc.alk.arena.competition.events.ReservedArenaEvent.openEvent(ReservedArenaEvent.java:85)
10.05 07:38:07 [Server] SEVERE at mc.alk.arena.competition.events.Event.openEvent(Event.java:109)
10.05 07:38:07 [Server] SEVERE at mc.alk.arena.controllers.messaging.EventMessager.sendEventOpenMsg(EventMessager.java:48)
10.05 07:38:07 [Server] SEVERE at mc.alk.arena.controllers.messaging.EventMessager.getChannel(EventMessager.java:26)
10.05 07:38:07 [Server] SEVERE at mc.alk.arena.objects.messaging.AnnouncementOptions.getDefaultChannel(AnnouncementOptions.java:104)
10.05 07:38:07 [Server] SEVERE java.lang.NullPointerException

**Comment by alkarinv** [comment]
So that error will happen if the plugin can't load the default announcement options on startup.  Was there any error when you started the server?

**Comment by Masterofjumping** [comment]
This error happens whenever I attempt to auto any game. The game will run but the announcement do not work. On start-up there is no errors that I can see but we have a very large number of plugins and it is not possible to clearly see how plugins each start.

**Comment by alkarinv** [comment]
Could you pastebin me your BattleArena/config.yml? that should be plenty to find the error

**Comment by Masterofjumping** [comment]
Here is a pastbin file of the config - http://pastebin.com/HkD3EZUQ

If is definitely not working properly. Whenever I attempt to fix it by removing the duplicate spaces and text it reverts to this upon restart. Then on the next restart another copy of the top is added. So every time the server restarts it duplicates everything in the config file.

**Comment by alkarinv** [comment]
That is unbelievably screwed up.  Try this

https://dl.dropboxusercontent.com/u/38069770/jars/BattleArena.jar

Newest version.  Delete that config.. install.  and start.

Really sorry MasterofJumping :(

**Comment by Masterofjumping** [comment]
This has fixed all problems. Thanks for the help. =)

**Comment by alkarinv** [comment]
Glad that fixed it, sorry for the problems :)
