### ISSUE TITLE
how can i make a 1v1 arena

### ISSUE THREAD

**Issue by dacrap123** [alkarinv/BattleArena#166]
how do i make a 1v1 arena set up i need help on how to make the config for it.

**Comment by alkarinv** [comment]
Pick the game you want to make 1v1, say skirmish.

BattleArena/competitions/SkirmishConfig.yml

change, nTeams: 1

<pre>
    nTeams: 1
</pre>

Also the new release allows you to change this in game, will be releasing shortly.  I'll put up details how to do it when I release.
