### ISSUE TITLE
inventory problem 

### ISSUE THREAD

**Issue by Dakotacrans** [alkarinv/BattleArena#17]
ok so there is a problem when people on my server are done playing and the match is over  there inventory gets cleared but there armor slot does not.

**Comment by alkarinv** [comment]
That is bizarre.  Are there any errors on the console? Unfortunately I'm gone most of the weekend but I'll try to get in a fix.

**Comment by Dakotacrans** [comment]
ok

**Comment by alkarinv** [comment]
Can you get me any other info?  like an error on console or anything?

I've been trying to make this problem happen but can't.

**Comment by Dakotacrans** [comment]
I' looked for it i could not find it. what basically happens is there
inventory is cleared but there armor does not get cleared.

**Comment by alkarinv** [comment]
Can you get me the address of your server, I'd like to come on and test this myself.  Would hopefully give me some sort of clue whats going on.  I've heard of other inventory issues, but this one is unique.

**Comment by Dakotacrans** [comment]
Sorry for the long response time, I found out what caused it it turned out
to be a compatibility error with the keepitems plugin

**Comment by alkarinv** [comment]
Excellent! so is it fixed?  If so tell me you how you did it so I can tell other people with keepitems what to do.

If it's not fixed let me know and I'm sure I can find a workaround, ( i already do for multiverse, multiverse-inventories, MultiInv)

Until then I'll mark this as closed, reopen it if it's still not fixed!

**Comment by Dakotacrans** [comment]
I uninstalled the plugin keepitems plugin. Basically that plugin allows
players to keep there items when they die, and when they died in the arena
it some how cleared there inventory but not there armor slots.
