### ISSUE TITLE
This player can not be challenged / Multiverse

### ISSUE THREAD

**Issue by Crowlix** [alkarinv/BattleArena#170]
Hello kind sir(s),

Recently I tried making a duel arena in another world. I'm using the Multiverse plugin for this.
However, when I try to challenge someone it gives me the messge "This player can not be challenged". I tried researching this, but Google gave me no solid answers.

Have I misconfigured something or did I just overlook something really obvious?

Kind regards

Crowlix

**Comment by alkarinv** [comment]
Oh, i have a perm that I put in because admins were getting constant duel requests.

"arena.duel.exempt"

So if you have the \* perm, it probably is including this perm, which makes them not be duelable.

Sorry for the late response!
