### ISSUE TITLE
Arena queue messed up? =/ Arena - Battle Arena and Spleef =/

### ISSUE THREAD

**Issue by SupaYoshi** [alkarinv/BattleArena#171]
<SupaYoshi> Heyaaaa
<SupaYoshi> I ahd problems with people being unable to leave and join ;)
<SupaYoshi> out of the arena
<SupaYoshi> they played previously :P
<SupaYoshi> Yeah
<SupaYoshi> i got issues with joining leaving.
<SupaYoshi> There is noone currently in the arena ;)
<SupaYoshi> and when I type /arena join it tells me that i need to elave first
<SupaYoshi> and then it tells me when i do /arena leave im not in a queue
<SupaYoshi> also happens to spleef
<SupaYoshi> =/
<SupaYoshi> canceling all arena events works...
<SupaYoshi> to fix it =/
<SupaYoshi> But this wasnt in the older versions
<SupaYoshi> http://pastebin.com/WTXJHXXD - Spleef config http://pastebin.com/5x4tEZvB - Arena config

**Comment by SupaYoshi** [comment]
Note: this bug isnt always to everyone... its weird. and some people can still join, /arena reload fixes it? :O

**Comment by SupaYoshi** [comment]
2013-05-19 12:49:11 [INFO] [BattleArena] Loading BattleArena v3.8.8.1.1

**Comment by SupaYoshi** [comment]
EdIT: has something to do with the joining and leaving of players online while in queue =/

**Comment by alkarinv** [comment]
Lol, can you grab me on irc?

**Comment by SupaYoshi** [comment]
Em yeah I tried that, but your never around there! =/ I been in the channel the whole day, and yesterday too, but please fix this, itts really annoying =/

**Comment by SupaYoshi** [comment]
Where are you!!1

**Comment by alkarinv** [comment]
Hey! around :( sorry, i'm now officially done with finals, so I'll be much more responsive

**Comment by alkarinv** [comment]
Hey Yoshi, hoping you are all good now.  I think these problems are all resolved so I'm going to close this up.
