### ISSUE TITLE
Classes not working 

### ISSUE THREAD

**Issue by CalebEatsPie** [alkarinv/BattleArena#172]
Tell me if I am doing something wrong but none of these classes are working, The sign won't be created

version: 1.1

<pre>
### You can add new classes here
classes:
    gladiator:
        displayName: "&4gladiator" ### Used for signs
        items:
            - iron_sword
            - iron_helm: 1
            - iron_chest: 1
            - iron_leggings: 1
            - iron_boots: 1
        enchants:
            - speed:1:1
    wizard:
        displayName: "&3Wizard" ### Used for signs
        items:
            - 373:16428: 10
            - 373:16421: 12
            - 373:16450: 5
            - 373:8264: 7
    knight:
        displayName: "&fKnight" ### Used for signs
        items:
            - gold_chest: 1
            - gold_helm: 1
            - gold_leggings: 1
            - gold_boots: 1
            - stone_sword: 1
            - steak: 8         
    premium:
        displayName: "&0premium" ### Used for signs
        items:
            - iron_chest: 1
            - iron_helm: 1
            - iron_leggings: 1
            - iron_boots: 1
            - diamond_sword: 1
            - steak: 8
            - 373:8264: 1
    donator:
        displayName: "&eDonator" ### Used for signs
        items:
            - iron_chest: 1
            - iron_helm: 1
            - iron_leggings: 1
            - iron_boots: 1
            - wooden_sword: 1
            - steak: 8
            - bow: power:3: flame:1: 1
            - arrow: 192
    donator+:
        displayName: "&6Donator+" ### Used for signs
        items:
            - diamond_chest: 1
            - leather_helm: 1
            - gold_leggings: 1
            - iron_boots: 1
            - diamond_sword: 1
            - steak: 8
            - bow: power:1: 1
            - arrow: 64
    vip:
        displayName: "&aVIP" ### Used for signs
        items:
            - diamond_chest: 1
            - diamond_helm: 1
            - diamond_leggings: 1
            - diamond_boots: 1
            - diamond_sword: 1
            - steak: 8
            - bow: power:2: 1
            - arrow: 64
    vip+:
        displayName: "&9VIP+" ### Used for signs
        items:
            - diamond_chest: protection:2: 1
            - diamond_helm: protection:2: 1
            - diamond_leggings: protection:2: 1
            - diamond_boots: protection:2: 1
            - diamond_sword: sharpness:2: 1
            - steak: 8
            - bow: power:2: 1
            - arrow: 64
</pre>

**Comment by alkarinv** [comment]
So it tells you the errors on startup.  In this case you have a whole bunch of enchants that are messing up.  You need to take out the last ":" after the enchant strength

Example: You have this

<pre>
 - diamond_sword: sharpness:2: 1  <- notice sharpness:2: has one too many colons
</pre>

change to

<pre>
 - diamond_sword: sharpness:2 1
</pre>

**Comment by CalebEatsPie** [comment]
I did that, now I get the error Couldnt find arenaClass gladiator

**Comment by CalebEatsPie** [comment]
And heres the updated classes too

<pre>
version: 1.1
### You can add new classes here
classes:
    gladiator:
        displayName: "&4Gladiator" ### Used for signs
        items:
            - iron_sword 1
            - iron_helm: 1
            - iron_chest: 1
            - iron_leggings: 1
            - iron_boots: 1
    archer:
        displayName: "&2Archer" ### Used for signs
        items:
            - stone_sword: 1
            - bow: 1
            - arrow: 32
            - leather_helm: 1
            - iron_chest: 1
            - leather_leggings: 1
            - leather_boots: 1
    wizard:
        displayName: "&3Wizard" ### Used for signs
        items:
            - 373:16428: 10
            - 373:16421: 12
            - 373:16450: 5
            - 373:8264: 7
    knight:
        displayName: "&fKnight" ### Used for signs
        items:
            - gold_chest: 1
            - gold_helm: 1
            - gold_leggings: 1
            - gold_boots: 1
            - stone_sword: 1
            - steak: 8
    knight:
        displayName: "&fKnight" ### Used for signs
        items:
            - gold_chest: 1
            - gold_helm: 1
            - gold_leggings: 1
            - gold_boots: 1
            - stone_sword: 1
            - steak: 8
    premium:
        displayName: "&0premium" ### Used for signs
        items:
            - iron_chest: 1
            - iron_helm: 1
            - iron_leggings: 1
            - iron_boots: 1
            - diamond_sword: 1
            - steak: 8
            - 373:8264: 1
    donator:
        displayName: "&eDonator" ### Used for signs
        items:
            - iron_chest: 1
            - iron_helm: 1
            - iron_leggings: 1
            - iron_boots: 1
            - wooden_sword: 1
            - steak: 8
            - bow: power: 3: flame:1 1
            - arrow: 192
    donator+:
        displayName: "&6Donator+" ### Used for signs
        items:
            - diamond_chest: 1
            - leather_helm: 1
            - gold_leggings: 1
            - iron_boots: 1
            - diamond_sword: 1
            - steak: 8
            - bow: power:1 1
            - arrow: 64
    vip:
        displayName: "&aVIP" ### Used for signs
        items:
            - diamond_chest: 1
            - diamond_helm: 1
            - diamond_leggings: 1
            - diamond_boots: 1
            - diamond_sword: 1
            - steak: 8
            - bow: power:2 1
            - arrow: 64
    vip+:
        displayName: "&9VIP+" ### Used for signs
        items:
            - diamond_chest: protection:2 1
            - diamond_helm: protection:2 1
            - diamond_leggings: protection:2 1
            - diamond_boots: protection:2 1
            - diamond_sword: sharpness:2 1
            - steak: 8
            - bow: power:2 1
            - arrow: 64
</pre>

**Comment by alkarinv** [comment]
Check out the errors on the console.

<pre>
in 'string', line 65, column 25:
                - bow: power: 3: flame:1 1
</pre>

should be

<pre>
                - bow: power:3 flame:1 1
</pre>

Couldn't see any errors besides that and it loaded just fine afterwards.

**Comment by leponder** [comment]
I am having a similar problem with classes, the signs work but during CTF matches players can't change classes anymore.

**Comment by alkarinv** [comment]
Leponder, all those problems should now be gone with version 3.9.6.7+
