### ISSUE TITLE
Events taking too long, lagging server out

### ISSUE THREAD

**Issue by Tux2** [alkarinv/BattleArena#173]
Hi,
I'm posting this on behalf of one of my customer's that doesn't have a Github account. I just checked her timings for her server and found that your plugin has some really rough spots in the report.

BattleArena v3.8.8.1.1
    PluginEnableEvent Time: 188982 Count: 3 Avg: 62994
    PlayerJoinEvent Time: 2379066 Count: 153 Avg: 15549
    PlayerInteractEvent Time: 209345320 Count: 82540 Avg: 2536
    PlayerInteractEvent Time: 720324044 Count: 76088 Avg: 9466
    PlayerCommandPreprocessEvent Time: 12499315 Count: 1426 Avg: 8765
    PlayerTeleportEvent Time: 1523652434 Count: 12100 Avg: 125921
    PlayerTeleportEvent Time: 54296540 Count: 12100 Avg: 4487
    PlayerTeleportEvent Time: 102757305 Count: 11858 Avg: 8665
    PlayerQuitEvent Time: 1540404 Count: 143 Avg: 10772
    PlayerQuitEvent Time: 150039749 Count: 135 Avg: 1111405
    SignChangeEvent Time: 2517519 Count: 40 Avg: 62937
    PlayerRespawnEvent Time: 459866908 Count: 213 Avg: 2158999
    PlayerKickEvent Time: 87110 Count: 7 Avg: 12444
    TeamJoinedQueueEvent (and others) Time: 1014590 Count: 3706 Avg: 273
    TeamJoinedQueueEvent (and others) Time: 17514557 Count: 3706 Avg: 4726
    TeamJoinedQueueEvent (and others) Time: 19510188 Count: 3706 Avg: 5264
    TeamJoinedQueueEvent (and others) Time: 17168866 Count: 3706 Avg: 4632
    TeamJoinedQueueEvent (and others) Time: 6247579 Count: 3706 Avg: 1685
    TeamJoinedQueueEvent (and others) Time: 1713270 Count: 3706 Avg: 462
    PlayerReceiveNameTagEvent Time: 23589855 Count: 3674 Avg: 6420
    Total time 3326253601 (3s)

Most noteably the PlayerRespawnEvent's average is taking so long it's taking more than 1 tick to process! If you need any help getting the time down just reply, as I've had experience getting timings down to almost nothing.

**Comment by alkarinv** [comment]
That's definitely not as efficient as I want it to be.  It's been a while since I've done some serious profiling so I'll do that and find out why the respawn is being so inefficient.  I also don't like the PlayerTeleportEvent, that one is actually the worst at 1.5 s.

Also the player PlayerRespawnEvent is taking 2ms, so it's actually taking 2.5x less than a tick to process. Not defending that's a good time, but it's a lot better than over a tick :)

I'll definitely get to this immediately, I like all of my plugins to be very efficient.  

After how much time was this taken?  3s is usually not very much in the scheme of plugins.

**Comment by alkarinv** [comment]
Also feel free to pull in the other person if you want, I can help them out directly to make sure the revisions I get to them fix the problem.

**Comment by alkarinv** [comment]
Tux, what profiler are you using to get those figures?  I really like this glowing interface.  http://aikar.co/timings.php?url=5692718

**Comment by Tux2** [comment]
I'm using the default profiler provided in bukkit. I then used that website to get it to look like that.

**Comment by alkarinv** [comment]
gotcha.

https://dl.dropboxusercontent.com/u/38069770/jars/BattleArena.jar

Could you try the new dev version.. Should have speed improvements for both PlayerInteractEvents and PlayerRespawnEvents.  I've done profiling and both appear faster, but my test server obviously doesnt have much traffic.

**Comment by alkarinv** [comment]
So the most recent reports from that server are the following

<pre>
From today BattleArena v3.8.8.2 PluginEnableEvent Time: 132597 Count: 4 Avg: 33149
 PlayerJoinEvent Time: 3592548 Count: 115 Avg: 31239
 PlayerInteractEvent Time: 581070385 Count: 65401 Avg: 8884
 PlayerInteractEvent Time: 317790 Count: 101 Avg: 3146
 PlayerTeleportEvent Time: 96422364 Count: 2741 Avg: 35177
 PlayerTeleportEvent Time: 15668325 Count: 2741 Avg: 5716
 PlayerTeleportEvent Time: 4506 Count: 3 Avg: 1502
 PlayerCommandPreprocessEvent Time: 7492 Count: 3 Avg: 2497
 PlayerQuitEvent Time: 5475444 Count: 101 Avg: 54212
 SignChangeEvent Time: 3289337 Count: 52 Avg: 63256
 PlayerRespawnEvent Time: 48080365 Count: 666 Avg: 72192
 PlayerKickEvent Time: 82974 Count: 8 Avg: 10371
 TeamJoinedQueueEvent (and others) Time: 923181 Count: 3432 Avg: 268
 TeamJoinedQueueEvent (and others) Time: 11035229 Count: 3432 Avg: 3215
 TeamJoinedQueueEvent (and others) Time: 12015909 Count: 3432 Avg: 3501
 TeamJoinedQueueEvent (and others) Time: 5840639 Count: 3432 Avg: 1701
 TeamJoinedQueueEvent (and others) Time: 9596598 Count: 3432 Avg: 2796
 TeamJoinedQueueEvent (and others) Time: 1664215 Count: 3432 Avg: 484
 PlayerReceiveNameTagEvent Time: 41901825 Count: 4954 Avg: 8458
 Total time 837121723 (0s)
</pre>

So I'm going to go ahead and close this as it looks like my improvements worked, the PlayerRespawnEvent is now 29 times faster than it was . I'll keep an eye out for further improvements as I keep coding.

Reopen if the problem happens again!
