### ISSUE TITLE
Error (console) when someone enter in queue

### ISSUE THREAD

**Issue by mateusd24** [alkarinv/BattleArena#175]
when someone enter in queue to skirmish (i only use skirmish mode) console spam some messages, and when try to leave /arena leave doesn't works (and spam errors)
for example, have 2 player on game (1x1) and when someone (or more players) enter at queue spam this error on console:

http://pastebin.com/iEJynx9x
 i use v3.8.8.1.5.1
this is my configs:
http://www.mediafire.com/?28a1ooaakrdr178
obs: i use duelarena(in configs) but the same as skirmish)
Thx
ahhh one question: 
for 1x1 i need to use this configs isn't it?
    victoryCondition: LastManStanding
    nTeams: 2
    teamSize: 1

**Comment by alkarinv** [comment]
Ok, so this should now be fixed. 3.8.8.1.5.3+

https://dl.dropboxusercontent.com/u/38069770/jars/BattleArena.jar

If that doesnt work then just reopen with the new error! but it should be good.  This is going to be the next release to bukkit

**Comment by mateusd24** [comment]
error fixed, thx so much xD
