### ISSUE TITLE
How can i remove this thing?

### ISSUE THREAD

**Issue by mateusd24** [alkarinv/BattleArena#176]
Hi how can i remove this [1250] and the (0:0) Follow the image:
![2013-05-27_20 52 10](https://f.cloud.github.com/assets/4521517/570103/e4fb43ba-c72a-11e2-88de-a3e44d136839.png)
Thx

**Comment by alkarinv** [comment]
You can go into the BattleArena/messages.yml

In there you will see "teamShort" and "teamLong", you can remove the rating there.

If you want the rating to mean something instead you can use my plugin BattleTracker

**Comment by mateusd24** [comment]
ahh, thx so much ^^
