### ISSUE TITLE
Arena Spleef superpick issue

### ISSUE THREAD

**Issue by stevewall85** [alkarinv/BattleArena#177]
I might just be stupid on this one but i have fully reinstalled the arena spleef plugin and i cannot for the life of me to get the superpick to enable for instabreak. 

Arena Spleef 1.4.1
Ba 3.8.8.1.6
Spigot 1.5.2 build 855

spleefconfig  - http://pastebin.com/UU021LpZ
config - http://pastebin.com/BuvsDzdb
arenas - http://pastebin.com/BHQew7Fa
I will post config and arena setup when i can but host having ddos issues and i cant get to my files at the moment. But superpick is enabled for the diamond_spade itemdb 277. I have gone through the wiki and cant find anything about the superpick and nothing showing it to add an option anywhere. So any help is appreciated and as soon as i can get to my files i will paste them in for you to chk out . thanks!

**Comment by alkarinv** [comment]
Those look great for me.  did you do /spleef reload? to make sure its reloaded.  If so, well then get me your ip and hop onto irc so we can work this out.

**Comment by stevewall85** [comment]
alright i will be on later tonight in a couple of hours and i will hop on irc i also have teamspeak if you wanna talk that way

**Comment by stevewall85** [comment]
thanks for the help on the matter the default change worked. hopefully i can find the real issue  but till then thanks !
