### ISSUE TITLE
Problem with queue

### ISSUE THREAD

**Issue by Kinters** [alkarinv/BattleArena#178]
There's an issue when players are joining queue to spleef or arena.When you heve onther fight plugin with choosing classes by signs, players can join the queue go to anotother arena (ex.mobarena and pvparena ) chose class and then they are teleporting back to spleef arena, and in the end of fight plugin restore their inventory from choosen class ! Is there any way to block commands when you are in queue?

**Comment by chulderman** [comment]
See this - http://battleplugins.com/w/index.php/BA_Config

use options.disabledQueueCommands
