### ISSUE TITLE
[Request] "dropItemOn" option

### ISSUE THREAD

**Issue by ZeegCL** [alkarinv/BattleArena#180]
Hi! I was testing the plugin "SurvivalArena" which uses the BattleArena API, but after a few games I noticed that the items were not dropped by the players on death.

Can you add the option "dropItemOn" to force items to drop?

**Comment by chulderman** [comment]
I haven't used SurvivalArena, however other BattleArena games DO drop items on death unless you specify otherwise. Maybe check SurvivalArena first.

**Comment by alkarinv** [comment]
Sorry for the long response. Just check to see that dropItemOff is not specified.
