### ISSUE TITLE
custom arena with config.yml

### ISSUE THREAD

**Issue by leo1232** [alkarinv/BattleArena#182]
Hello,
I would like to create a custom arena with a new "config.yml" I named the "BattleDigitalConfig.yml" file, but the command "/ bd" is unknown to the server I do not know what to do here is the config that I 've created 
http://pastebin.com/KJnSTdhz

**Comment by alkarinv** [comment]
Hi Leo, sorry for the long response.  I have done a bunch of fixes and the newest BattleArena should have this fixed up.  Reopen if it's not.
