### ISSUE TITLE
Commands are not being blocked. 

### ISSUE THREAD

**Issue by Murdox1221** [alkarinv/BattleArena#186]
Firstly I love this plugin and use it on my Factions server, however Im currently using it on an islandworld based server, the issue is the commands like ./is home and the tp commands from that plug-in still work and allow players to leave during that match. Would it be at all possible to block these commands, or have the option to? When I add them in the config.YML they are not blocked. even after ./arena reload. 
Thank you
Murdox 1221

**Comment by alkarinv** [comment]
This has been forever, sorry for the long response.  If this is still a problem let me know, otherwise for now I'm going to close this.
