### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by DeadIntermediate** [alkarinv/BattleArena#187]
I get these errors in console. What does it meant? A Bug?

http://pastebin.com/i27Yqz4U

**Comment by alkarinv** [comment]
It looks like a bug.  One I've never seen before too.

can you pastebin the config of the game that is doing this please?

**Comment by DeadIntermediate** [comment]
http://pastebin.com/W1CrizqD

**Comment by alkarinv** [comment]
It's been a long time, but should be resolved in recent versions.
