### ISSUE TITLE
/colosseum create not working

### ISSUE THREAD

**Issue by MaxCoffeebreath** [alkarinv/BattleArena#188]
The command /colosseum returns as an invalid command (other variations such as /co and /col return the same so unable to create colosseum arenas.

**Comment by alkarinv** [comment]
if thats the case, its probably a bad CollosseumConfig.yml

you might want to try deleting that and doing a restart.

I bet that fixes the problem but let me know if it doesnt!

**Comment by MaxCoffeebreath** [comment]
Yep, that were it.  Thanks much.

**Comment by alkarinv** [comment]
excellent!
