### ISSUE TITLE
More players in arena

### ISSUE THREAD

**Issue by fifi98** [alkarinv/BattleArena#190]
Sometime in my arena there are 4 or 6 players. Arena is configured for 2 players... So they all type /arena join and are in arena...

Using version 3.9.1.3

**Comment by alkarinv** [comment]
Hey, can you try this version

https://dl.dropboxusercontent.com/u/38069770/jars/BattleArena.jar

Its a bit updated, and I tried to fix that specific problem.  Honestly though I'm not sure if I did as I can't recreate the issue.

So if you can give me any more details that would be great :)

**Comment by fifi98** [comment]
Okay, thanks for the reply. I will report back!

**Comment by fifi98** [comment]
Yay, problem is fixed, thank you very much for the new version! :)

**Comment by alkarinv** [comment]
great!

**Comment by LiamVereecken** [comment]
Yup it worked
