### ISSUE TITLE
Command

### ISSUE THREAD

**Issue by fifi98** [alkarinv/BattleArena#191]
Sometime when a player types /arena join, it won't happen anything. Then he must again type command /arena join and he will be in quie...

Using version 3.9.1.3

**Comment by alkarinv** [comment]
Herm, try this one.  3.9.1.5.3

https://dl.dropboxusercontent.com/u/38069770/jars/BattleArena.jar

But I'll keep my eye out for this.

**Comment by fifi98** [comment]
Okay, thanks for the reply. I will report back!

**Comment by fifi98** [comment]
Yay, problem is fixed, thank you very much for the new version! :)
