### ISSUE TITLE
BA and same Faction

### ISSUE THREAD

**Issue by olivier1209** [alkarinv/BattleArena#192]
Hello,

Here is what I'm facing : in an FFA , Colosseum , or any other arena , if I fight against one of my faction members I can see the message : "you can't hurt your factions team mates" , or something like that. This is a quite inconvenient since most of our players are part of a faction , and sometimes want to PvP..
Could you advise on that please.

Many thanks
Olivier

**Comment by alkarinv** [comment]
I think the way people have been doing it is by making a "warzone" in the arena area.  Other than that, I'll try to see if Factions allows me to do something, but probably not.

**Comment by LiamVereecken** [comment]
I had the problem too but I fixed it. If the arenas are in an other world than your faction world you could set the option worldsIgnorePvp to that world. If it's in the same world claim the arena in warzone and do 
/f flag warzone friendlyfire yes
