### ISSUE TITLE
Suggestion for ingame command handling

### ISSUE THREAD

**Issue by kymotsujason** [alkarinv/BattleArena#195]
I've been using BattleArena for a while now, its been great and all but I feel like its missing a feature.
That feature would be disabling all commands but BattleArena commands while ingame.

The 'disabledcommands' option is very inconvenient when you have a lot of plugins.
Would it be possible to add a simple option to disable all commands but BattleArena's command ingame?

The plugin MobArena has a system similar to this if you need an example.

**Comment by alkarinv** [comment]
Yeah, I understand that, I'll see if I can add that in the next release.
