### ISSUE TITLE
After first match, can't start a new or use reload command

### ISSUE THREAD

**Issue by WezzLee91** [alkarinv/BattleArena#197]
After the first game after a server restart, no one can use the /bg join command, and I can't use /bg reload, saying that "Can't reload while match is on or players in the queue." However no one is in the queue and even after I run /arena cancel all, it persists.

We are on 1.2.5 Tekkit server, with v3.9.3.3.1

**Comment by alkarinv** [comment]
Hey WezzLee, could you try the latest version.  And hopefully this is fixed now.  

https://www.dropbox.com/sh/q9jgg8yrpzh3ofy/eka416vnas/jars/BattleArena.jar

cheers!
