### ISSUE TITLE
No Infinite Lives in DM Arena

### ISSUE THREAD

**Issue by NameThatFollows** [alkarinv/BattleArena#199]
The victoryCondition is set to HighestKills and the match is 7 minutes long. 

Each player, however, only has one life and the players don't respawn. The last man standing is the only one that gets the prize at the end.

**Comment by alkarinv** [comment]
So try this.

./dm setoption nlives infinite

I made a change to how the lives work.  So from now on you can set the number of lives for any victory condition

./arena setoption nlives 5
