### ISSUE TITLE
Queue join and match start. Once works but after 1 match doesn't no more. Reload needed to work again...

### ISSUE THREAD

**Issue by iForFi** [alkarinv/BattleArena#210]
Hi.
My problem is that after 1 match of a arena the arena doesn't work no more. Meaning doesn't work is that even if there are 4/4 or 8/8 players it doesn't start. Even more players can join example. 6/4 and nothing. At the first time after reload it is ok and works good. But after 1 match in that arena the arena doesn't work no more. I don't want to reload my serwer each few minutes.
Please help fast.
Thank you.

**Comment by iForFi** [comment]
BTW. My ArenaComp.. config
Arena:
  name: Arena
  command: Arena
  prefix: '&f[&6Arena&f]&e'
  gameSize:
    nTeams: 2+
    teamSize: 1+
  nLives: '4'
  victoryCondition: HIGHESTKILLS
  times: {}
  tracking:
    rated: true
    useTrackerMessages: false
  arenaType: Arena
  arenaClass: Arena
  nConcurrentCompetitions: infinite
  defaults:
    options:
    - alwaysTeamNames
  onEnter:
    options:
    - storeExperience
    - storeItems
    - storeHealth
    - storeHunger
    - storeMagic
    - clearInventory
    - clearExperience
    - deEnchant
    - flightOff
  onLeave:
    options:
    - restoreExperience
    - restoreItems
    - restoreHealth
    - restoreHunger
    - restoreMagic
    - clearInventory
    - deEnchant
  onStart:
    options:
    - teleportIn
    - pvpOn
    - blockBreakOff
  onComplete:
    options:
    - teleportOut
  onSpawn:
    giveClass:
      default: gladiator
    options:
    - health=20.0
    - hunger=20
  onDeath:
    options:
    - clearInventory
    - respawn
  winner:
    options:
    - health=20.0
    - hunger=20

**Comment by iForFi** [comment]
Can someone help? Please.

**Comment by tara81** [comment]
I have this problem too, I just told alkarin and he is working on it .  Did you get errors in console on server bootup like I did about scoreboard API or any errors at all ?

**Comment by tara81** [comment]
You should pastebin all of your loadup errors here, because that is how alkarin can fix it

**Comment by alkarinv** [comment]
Should be fixed in the newest version.

3.9.4.6.6+ !
