### ISSUE TITLE
GiveItems

### ISSUE THREAD

**Issue by lollollol3355** [alkarinv/BattleArena#211]
For some reason, when players select a class, they also receive all the items that
giveItems would give along with the items their supposed to receive.
For example, a player selects gladiator and gets the diamond armor and sword, but
he also receives the leather armor, arrows, TNT, bread, sword, and bow that giveItems gives. I don't even have giveItems in one of the options, and yet it still doesn't ignore giveItems.
Also, when players die, they don't respawn in the arena for some reason. The match 
ends in a lastmanstanding fashion.

DeathMatch:
    enabled: true
    joinType: JoinPhase
    victoryCondition: highestKills
    database: dm
    rated: true
    prefix: "&8[DeathMatch]&e"
    nTeams: 2+
    teamSize: 1
    announcements: ### Override the match victory announcement as the event has one too
        onVictory:  [ dontannounce ] 
    defaults:
        options: []
    preReqs:
        options: [clearInventory]
    onEnter:
        options: [storeAll]
    onLeave:
        options: [restoreAll]
    onJoin:
        options: [teleportWaitroom]
    onOpen:
        options: [pvpOff]
    onStart:
        options: [pvpOn, teleportIn, blockBreakOff]
    onComplete:
        options: [teleportOut, blockBreakOn]
    onSpawn:
        options: [enchants, health=20, hunger=20]
        items: # ignored if options doesnt have "giveItems"
            - iron_sword: 1
            - bow: 1
            - tnt: 3
            - arrow: 32
            - leather_helm: 1
            - leather_chest: 1
            - leather_leggings: 1
            - leather_boot: 1
            - bread: 5
    onDeath:
        options: [Respawn, clearInventory]
    winner:
        options: [enchants, money=300, experience=500, health=20, hunger=20]
    losers:
        options: [money=50, experience=50, health=20, hunger=20]

**Comment by iForFi** [comment]
Just delete all this:
- iron_sword: 1
- bow: 1
- tnt: 3
- arrow: 32
- leather_helm: 1
- leather_chest: 1
- leather_leggings: 1
- leather_boot: 1
- bread: 5
  And leave only
- bread: 5
  and it should be good :D.
  BTW.
  I prefer using an Arena compatition not an DeathMatch.
  Just set in arena the:
  victoryCondition: LASTMANSTANDING
  to
  victoryCondition: highestKills
