### ISSUE TITLE
Pets

### ISSUE THREAD

**Issue by Shaitan1805** [alkarinv/BattleArena#212]
Hey,

first of all, srry for my bad english.

I want to make a class which have a tamed wolf. When I write a class like this:
myclass:
displayName: "Class"
items:
       - wood_sword: 1
mobs:
      wolf: prot:5 1

then the class got a wild wolf. 

How can I make the class get a tamed wolf? Would you please add the wiki all mobs can get added?

greetz
Shaitan

**Comment by Hezitation** [comment]
you would have too do tamed_wolf.

**Comment by alkarinv** [comment]
It's been a while, but this should now be fixed.

http://ci.battleplugins.com
