### ISSUE TITLE
Matches don't start...

### ISSUE THREAD

**Issue by LiamVereecken** [alkarinv/BattleArena#214]
Hey guys, once again I have issues.... When I and an other player do /bg join dome, it says You joined the BattleGround queue. Match starts in 59 seconds with at least 2 players. In my config.yml it says:
    matchEnableForceStart: true
    matchForceStartTime: 60
But after 60 seconds nothing happens :P
config.yml: http://pastebin.com/G6PnBDWJ
Battlegroundconfig.yml: http://pastebin.com/AN95a4ax
I hope someone can fix this soon :P I own a minigames server and I don't even have working minigames :(

**Comment by iForFi** [comment]
I had this tooo. Deleted the folder and the plugin and installed again. Fixed this :).

**Comment by LiamVereecken** [comment]
Yea I just updated the plugin to the newest version (again :P) and it worked

**Comment by alkarinv** [comment]
I released a bunch of new versions recently that hopefully will seal this issue for good.

3.9.4.6.6+ should hopefully work
http://dev.bukkit.org/media/files/733/484/BattleArena.jar
