### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by lollollol3355** [alkarinv/BattleArena#215]
Whenever someone quits/disconnects in a middle of any match, this appears in console. I'm wondering if this is a conflict to one of my other plugins, or this is a bug with BattleArena. Does this bug do nothing, and is just a nuisance in console?

12:24:17 PM
 Arenas]<: 
tawanminer> I'mma go play on another server

12:24:25 PM
 Arenas]<: 
tawanminer> Bye

12:24:27 PM
 CONSOLE: 
[INFO] Connection reset

12:24:27 PM
 CONSOLE: 
tawanminer has left.

12:24:27 PM
 CONSOLE: 
[INFO] tawanminer lost connection: disconnect.quitting

12:24:27 PM
 CONSOLE: 
[SEVERE] [BA:Error] method=public void mc.alk.arena.competition.match.ArenaMatch.onPlayerQuit(org.bukkit.event.player.PlayerQuitEvent), types.length=1, p=CraftPlayer{name=tawanminer}, listener=[ArenaMatch : [MEM onPlayerQuit, PlayerQuitEvent p=MONITOR onEnter:onLeave playerMethod=public final org.bukkit.entity.Player org.bukkit.event.player.PlayerEvent.getPlayer()]]

12:24:27 PM
 CONSOLE: 
[SEVERE] java.lang.reflect.InvocationTargetException 

12:24:27 PM
 CONSOLE: 
[SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

12:24:27 PM
 CONSOLE: 
[SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

12:24:27 PM
 CONSOLE: 
[SEVERE] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

12:24:27 PM
 CONSOLE: 
[SEVERE] at java.lang.reflect.Method.invoke(Unknown Source)

12:24:27 PM
 CONSOLE: 
[SEVERE] at mc.alk.arena.listeners.custom.SpecificPlayerEventListener.doMethods(SpecificPlayerEventListener.java:202)

12:24:27 PM
 CONSOLE: 
[SEVERE] at mc.alk.arena.listeners.custom.SpecificPlayerEventListener.callListeners(SpecificPlayerEventListener.java:171)

12:24:27 PM
 CONSOLE: 
[SEVERE] at mc.alk.arena.listeners.custom.SpecificPlayerEventListener.invokeEvent(SpecificPlayerEventListener.java:164)

12:24:27 PM
 CONSOLE: 
[SEVERE] at mc.alk.arena.listeners.custom.BukkitEventListener$1.execute(BukkitEventListener.java:45)

12:24:27 PM
 CONSOLE: 
[SEVERE] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

12:24:27 PM
 CONSOLE: 
[SEVERE] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)

12:24:27 PM
 CONSOLE: 
[SEVERE] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)

12:24:27 PM
 CONSOLE: 
[SEVERE] at net.minecraft.server.v1_6_R2.PlayerList.disconnect(PlayerList.java:258)

12:24:27 PM
 CONSOLE: 
[SEVERE] at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:688)

12:24:27 PM
 CONSOLE: 
[SEVERE] at net.minecraft.server.v1_6_R2.NetworkManager.b(NetworkManager.java:302)

12:24:27 PM
 CONSOLE: 
[SEVERE] at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:116)

12:24:27 PM
 CONSOLE: 
[SEVERE] at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)

12:24:27 PM
 CONSOLE: 
[SEVERE] at net.minecraft.server.v1_6_R2.DedicatedServerConnection.b(SourceFile:30)

12:24:27 PM
 CONSOLE: 
[SEVERE] at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:590)

12:24:27 PM
 CONSOLE: 
[SEVERE] at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)

12:24:27 PM
 CONSOLE: 
[SEVERE] at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)

12:24:27 PM
 CONSOLE: 
[SEVERE] at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)

12:24:27 PM
 CONSOLE: 
[SEVERE] at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)

12:24:27 PM
 CONSOLE: 
[SEVERE] Caused by: java.lang.IllegalStateException: Cannot set scoreboard for invalid CraftPlayer

12:24:27 PM
 CONSOLE: 
[SEVERE] at org.bukkit.craftbukkit.v1_6_R2.entity.CraftPlayer.setScoreboard(CraftPlayer.java:1007)

12:24:27 PM
 CONSOLE: 
[SEVERE] at mc.alk.arena.objects.scoreboard.BukkitScoreboard.removedFromTeam(BukkitScoreboard.java:260)

12:24:27 PM
 CONSOLE: 
[SEVERE] at mc.alk.arena.objects.scoreboard.BukkitScoreboard.leaving(BukkitScoreboard.java:221)

12:24:27 PM
 CONSOLE: 
[SEVERE] at mc.alk.arena.competition.match.Match.onPreQuit(Match.java:1024)

12:24:27 PM
 CONSOLE: 
[SEVERE] at mc.alk.arena.controllers.TeleportLocationController.movePlayer(TeleportLocationController.java:88)

12:24:27 PM
 CONSOLE: 
[SEVERE] at mc.alk.arena.controllers.TeleportLocationController.teleportOut(TeleportLocationController.java:66)

12:24:27 PM
 CONSOLE: 
[SEVERE] at mc.alk.arena.competition.match.PerformTransition.transition(PerformTransition.java:239)

12:24:27 PM
 CONSOLE: 
[SEVERE] at mc.alk.arena.competition.match.PerformTransition.transition(PerformTransition.java:100)

12:24:27 PM
 CONSOLE: 
[SEVERE] at mc.alk.arena.competition.match.Match.privateQuitting(Match.java:1017)

12:24:27 PM
 CONSOLE: 
[SEVERE] at mc.alk.arena.competition.match.Match.onLeave(Match.java:943)

12:24:27 PM
 CONSOLE: 
[SEVERE] at mc.alk.arena.competition.match.ArenaMatch.onPlayerQuit(ArenaMatch.java:85)

12:24:27 PM
 CONSOLE: 
[SEVERE] ... 22 more

12:24:27 PM
 CONSOLE: 
[INFO] etawanminer left the game.

**Comment by alkarinv** [comment]
Well I just released some new versions, maybe they fixed this error.  But it looks like maybe I'm trying to give scoreboards to people that are no longer online, which causes this.

If the new versions dont fix this should be easy to resolve.

**Comment by lollollol3355** [comment]
Yay, it's fixed! Thank you~~
