### ISSUE TITLE
Teleporting to a null location error

### ISSUE THREAD

**Issue by jmarler** [alkarinv/BattleArena#216]
When players join PVP arenas, we get the following dumped into the server log:

```
[SEVERE] [BA Error] Teleporting to a null location!  teleportTo=false
[SEVERE] [BA Error] teleporting player=Ginger_tommy to null true
```

Please see full error dump at:

http://pastebin.com/kbr0X6Lp

**Comment by alkarinv** [comment]
Hey Jmarier, so I just released a bunch of new versions with fixes for things like this

3.9.4.6.6+ should have the fixes.

http://dev.bukkit.org/media/files/733/484/BattleArena.jar

If you're still around could you try that out?

cheers,
alkarin

**Comment by jmarler** [comment]
I will give it a shot.  Thanks for the update!
