### ISSUE TITLE
deEnchant not working correctly

### ISSUE THREAD

**Issue by iForFi** [alkarinv/BattleArena#217]
Hi.
I have a problem that deEnchant doesn't work corretly.
First i had the default config and after the battle the effects where still back and people could run on diffrent places with em. I decided to give in onComplete, onDeath, onWinner... nearly all give th deEnchant option. Doesn't seem to work :(...
Any suggestions?

**Comment by alkarinv** [comment]
Fixed in the more recent versions.  3.9.4.6.6+ !
