### ISSUE TITLE
Arena Paintball - trouble with pvp override

### ISSUE THREAD

**Issue by TheLecturer** [alkarinv/BattleArena#219]
Hi.

I run a non-PVP server and would like to know if it is possible to have Arena Paintball working?  I had guessed by the transition setting "pvpOn : set PvP damage to be on (overrides most other plugins). Friendly fire is off " that this would be possible, but I cannot seem to get it to work.
- I have pvp = true in server.properties.
- This is over-ridden by a Multiverse setting which sets pvp to false on a per world basis.
- BattleArena installed and working fine as I already have Arena Spleef (though not requiring pvp)
- With this setup, Arena Paintball does not work (snowballs pass harmlessly).

If I change the pvp setting in Multiverse to "true", then Arena Paintball works. However I don't want pvp on for the whole world.

I also tried creating a region and adding it to the Arena Paintball arena with "/arena alter <arena name> addregion" - this added the region to WorldGuard with flag "pvp:allow" and priority 11, but made no difference.

Is what I am trying to do possible? Or have I misunderstood the option "pvpOn : set PvP damage to be on (overrides most other plugins). Friendly fire is off"  ?

Thanks very much.

Versions:
CraftBukkit version git-Spigot-1091 (MC: 1.6.2)
[BattleTracker] Loading BattleTracker v2.5.5.1
[Multiverse-Core] Loading Multiverse-Core v2.5-b641
[WorldGuard] Loading WorldGuard v5.8
[BattleArena] Loading BattleArena v3.9.4.6.3
[ArenaPaintball] Loading ArenaPaintball v1.1.3
ArenaSpleef] Loading ArenaSpleef v1.4.6

Other plugins in use:

[bPermissions] Loading bPermissions v2.10.7
[HerobrineAI] Loading HerobrineAI v3.2.0
[NoCheatPlus] Loading NoCheatPlus v3.10.2-RC-sMD5NET-b620
[WorldEdit] Loading WorldEdit v5.5.7
[AutoShutdown] Loading AutoShutdown v3.2.1-1.5.1
[BetterJetpacks] Loading BetterJetpacks v1.0.1
[Vault] Loading Vault v1.2.27-b349
[PlayerHeads] Loading PlayerHeads v3.4-jenkins-PlayerHeads-1-30-gbb967f6
[LogBlock] Loading LogBlock v1.70
[MobileAdmin] Loading MobileAdmin v3.2.5
[TreeAssist] Loading TreeAssist v5.4.2
[dynmap] Loading dynmap v1.9-831
[HorseCraftables] Loading HorseCraftables v3.1.2
[AutoRanker] Loading AutoRanker v0.3.0
[ExtraHardMode] Loading ExtraHardMode v3.3.3
[EpicBossRecoded] Loading EpicBossRecoded v1.3.2
[TreasureChest] Loading TreasureChest v8.4.4
[OpenInv] Loading OpenInv v2.0.8
[DailyLog] Loading DailyLog v1.5R2
[PopulationDensity] Loading PopulationDensity v3.8
[VariableTriggers] Loading VariableTriggers v1.2.6
[GriefPrevention] Loading GriefPrevention v7.7
[MobArena] Loading MobArena v0.95.5
[afkTerminator] Loading afkTerminator v1.5.3
[PwnFilter] Loading PwnFilter v3.1.1
[Essentials] Loading Essentials vPre2.12.1.6
[WorldBorder] Loading WorldBorder v1.7.5
[QuickShop] Loading QuickShop v4.4
[Citizens] Loading Citizens v2.0.9-SNAPSHOT (build 966)
[CreeperHeal] Loading CreeperHeal v6.6.1
[ChessCraft] Loading ChessCraft v2.3.4
[NaturalHorses] Loading NaturalHorses v1.0.7
[Multiverse-Portals] Loading Multiverse-Portals v2.4-b548
[Multiverse-Inventories] Loading Multiverse-Inventories v2.5-b335
[Multiverse-SignPortals] Loading Multiverse-SignPortals v2.4-b523
[VanishNoPacket] Loading VanishNoPacket v3.18.2
[Multiverse-NetherPortals] Loading Multiverse-NetherPortals v2.4-b530
[Enjin Minecraft Plugin] Loading Enjin Minecraft Plugin v2.4.9-bukkit
[Dynmap-GriefPrevention] Loading Dynmap-GriefPrevention v0.60
[HomeSpawnPlus] Loading HomeSpawnPlus v1.7.7
[EssentialsChat] Loading EssentialsChat vPre2.12.1.6

**Comment by alkarinv** [comment]
So I think unfortunately there isnt much I can do when you have multiverse setting the world PvP to false.  Basically that is like setting pvp=false in the config for that world.  When that happens no damage events happen :(

Most people that want to have no pvp except for in select places use WorldGuard, though I don't know exactly how to set that up.

**Comment by TheLecturer** [comment]
Thanks for your reply - managed to work it out after sleeping on it :-)  Solution below in case you want to add to documentation, and you were right, it is WorldGuard which controls it.

So - to enable Arena Paintball in a non-PVP world with Multiverse and WorldGuard:-

```
/server.properties
  pvp=true

/plugins/Multiverse-Core/worlds.yml
  worlds:
    myworld:
      pvp: 'true'

/plugins/WorldGuard/worlds/myworld/regions.yml
regions:
    __global__:
        type: global
        priority: 0
        flags: {pvp: deny}
        owners: {}
        members: {}
    ba-paintball:
        type: cuboid
        min: {x: -1817.0, y: 66.0, z: 2545.0}
        max: {x: -1766.0, y: 110.0, z: 2586.0}
        priority: 11
        flags: {pvp: allow}
        owners: {}
        members: {}
```

The "ba-paintball" region definition in the WorldGuard region.yml file is not required, strictly speaking - the paintball game works without it - however the players get spammed with "This is a no-PVP area" (or some such) even though the snowballs cause damage. Adding the region using your "/arena alter arenaname addregion" command removes this message and makes for a cleaner game.

Thanks!
