### ISSUE TITLE
[SEVERE] Couldn't parse options ENCHANTMENTS

### ISSUE THREAD

**Issue by Smtih** [alkarinv/BattleArena#220]
I get this error after a clean install using BattleArena v3.9.4.6.6

---

12/09/2013 1:47:35 PM [INFO] [BattleArena] Enabling BattleArena v3.9.4.6.6
12/09/2013 1:47:35 PM [INFO] [BattleArena] v3.9.4.6.6 enabling!
12/09/2013 1:47:35 PM [INFO] [BattleArena] BattleTracker not detected, not tracking wins
12/09/2013 1:47:35 PM [INFO] [BattleArena] Multiverse-Core detected. Implementing teleport/gamemode workarounds
12/09/2013 1:47:35 PM [INFO] [BattleArena] WorldEdit detected.
12/09/2013 1:47:35 PM [INFO] [BattleArena] WorldGuard detected. WorldGuard regions can now be used
12/09/2013 1:47:35 PM [INFO] [BattleArena] found economy plugin Vault. [Default]
12/09/2013 1:47:35 PM [INFO] [BattleArena] no additional Arena modules
12/09/2013 1:47:35 PM [INFO] [BattleArena] registering classes: gladiator, archer, monk
12/09/2013 1:47:35 PM [INFO] [BattleArena] Loaded Skirmish params
12/09/2013 1:47:35 PM [INFO] [BattleArena] has no arenas, cs section =
12/09/2013 1:47:35 PM [SEVERE] Couldn't parse Option ENCHANTS value=null
12/09/2013 1:47:35 PM [SEVERE] Couldn't parse Option ENCHANTS value=null
12/09/2013 1:47:35 PM [INFO] [BattleArena] Loaded FreeForAll params
12/09/2013 1:47:35 PM [INFO] [BattleArena] has no arenas, cs section =
12/09/2013 1:47:35 PM [INFO] [BattleArena] Loaded Arena params
12/09/2013 1:47:35 PM [INFO] [BattleArena] has no arenas, cs section =
12/09/2013 1:47:35 PM [SEVERE] Couldn't parse Option ENCHANTS value=null
12/09/2013 1:47:35 PM [SEVERE] Couldn't parse Option ENCHANTS value=null
12/09/2013 1:47:35 PM [INFO] [BattleArena] Loaded DeathMatch params
12/09/2013 1:47:35 PM [INFO] [BattleArena] has no arenas, cs section =
12/09/2013 1:47:35 PM [SEVERE] Couldn't parse Option ENCHANTS value=null
12/09/2013 1:47:35 PM [SEVERE] Couldn't parse Option ENCHANTS value=null
12/09/2013 1:47:35 PM [INFO] [BattleArena] Loaded Colosseum params
12/09/2013 1:47:35 PM [INFO] [BattleArena] has no arenas, cs section =
12/09/2013 1:47:35 PM [SEVERE] Couldn't parse Option ENCHANTS value=null
12/09/2013 1:47:35 PM [SEVERE] Couldn't parse Option ENCHANTS value=null
12/09/2013 1:47:35 PM [INFO] [BattleArena] Loaded Battleground params
12/09/2013 1:47:35 PM [INFO] [BattleArena] has no arenas, cs section =
12/09/2013 1:47:35 PM [INFO] [BattleArena] Loaded Duel params
12/09/2013 1:47:35 PM [INFO] [BattleArena] has no arenas, cs section =
12/09/2013 1:47:35 PM [INFO] [BattleArena] Loaded Tourney params
12/09/2013 1:47:35 PM [INFO] [BattleArena] v3.9.4.6.6 enabled!

**Comment by SamuraiRat** [comment]
I get the same error message - [SEVERE] Couldn't parse Option ENCHANTS value=null

**Comment by alkarinv** [comment]
Thanks for the report

This was mainly a visual error that was more annoying than anything.  Fixed in BattleArena 3.9.4.8+.

**Comment by SamuraiRat** [comment]
Thanks

Date: Sun, 22 Sep 2013 22:56:08 -0700
