### ISSUE TITLE
[Bug] Duel Join Jack vs Jack WTF? Same Player VS Same Player

### ISSUE THREAD

**Issue by iForFi** [alkarinv/BattleArena#221]
Hi.
I have a problem with duel arenas. Sometimes it happens that exmaple Jack tries to go pvp duel with John but somehow it becomes Jack vs Jack. I use signs for joining.
Duel
join
ArenaName

**Comment by alkarinv** [comment]
Thanks!
Fixed in BattleArena v3.9.4.8+
