### ISSUE TITLE
Respawn With Class isn't working

### ISSUE THREAD

**Issue by lollollol3355** [alkarinv/BattleArena#222]
Players can select a class. Play with it. But when they die, they never spawn with the class. They simply spawn with nothing. Help?
I have respawnWithClass in the onSpawn thing. Why aren't players spawning with their classes after they die?

DeathMatch:
  name: DeathMatch
  command: DeathMatch
  prefix: '&8[DeathMatch]&e'
  gameSize:
    nTeams: 2+
    teamSize: '1'
  nLives: infinite
  victoryCondition: HIGHESTKILLS
  times: {}
  tracking:
    database: dm
    rated: true
    useTrackerMessages: false
  arenaType: DeathMatch
  arenaClass: Arena
  announcements:
    ONVICTORY:
    - DONTANNOUNCE
  eventAnnouncements: {}
  defaults:
    options: []
  onEnter:
    options:
    - STOREALL
  onLeave:
    options:
    - RESTOREALL
  preReqs:
    options:
    - clearInventory
  onJoin:
    options:
    - teleportWaitRoom
    - noTeleport
    - woolTeams
    - itemDropOff
    - blockPlaceOff
  onOpen:
    options:
    - pvpOff
  onStart:
    options:
    - teleportIn
    - pvpOn
    - blockBreakOff
    - wgNoLeave
    - itemDropOff
    - blockPlaceOff
  onComplete:
    options:
    - teleportOut
    - clearInventory
    - blockBreakOn
    - deEnchant
    - wgClearRegion
    - wgResetRegion
    - blockPlaceOn
  onSpawn:
    options:
    - healthp=100
    - hunger=20
    - respawnWithClass
  onDeath:
    options:
    - clearInventory
    - randomRespawn
  winner:
    enchants: []
    options:
    - health=20.0
    - hunger=20
    - experience=200
    - money=500

**Comment by alkarinv** [comment]
Hey Lol, I've checked this like 3 times, it's actually working for me. What version of battlearena do you have?

**Comment by lollollol3355** [comment]
Nevermind, after I deleted the entire battlearena file, it regenerated and I was able to paste the config file I had before. Then the RespawnWithClass thing worked. Thanks for trying to help :)

**Comment by lollollol3355** [comment]
Uhhh, nevermind, it worked for a hour... and then players began not spawning with their classes anymore.
I'm using the latest version. Version 3.9.4.9.

**Comment by alkarinv** [comment]
Hey loll, so this problem is definitely resolved now.  So I'm going to close this.  Sorry for letting it hang so long.
