### ISSUE TITLE
Spamming errors on death

### ISSUE THREAD

**Issue by Stacelin** [alkarinv/BattleArena#224]
Not sure entirely why. But we're using the most recent build on Dev.Bukkit.  
I've also been having issues with players joining the arenas. It'll say 0/2 on the signs no matter if they join the queue or not. and then the queue doesn't start.. :/  I'm not sure if it's all connected or not. But here's the error we're getting when players die in the arena:

2:01:37 PM  CONSOLE:
[SEVERE] java.lang.NullPointerException
2:01:37 PM  CONSOLE:
[SEVERE] at mc.alk.arena.controllers.messaging.MatchMessageImpl.sendOnIntervalMsg(MatchMessageImpl.java:154)
2:01:37 PM  CONSOLE:
[SEVERE] at mc.alk.arena.controllers.messaging.MatchMessager.sendOnIntervalMsg(MatchMessager.java:63)
2:01:37 PM  CONSOLE:
[SEVERE] at mc.alk.arena.competition.match.Match.intervalTick(Match.java:1420)
2:01:37 PM  CONSOLE:
[SEVERE] at mc.alk.arena.objects.victoryconditions.TimeLimit.intervalTick(TimeLimit.java:50)
2:01:37 PM  CONSOLE:
[SEVERE] at mc.alk.arena.util.Countdown.run(Countdown.java:52)
2:01:37 PM  CONSOLE:
[SEVERE] at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftTask.run(CraftTask.java:67)
2:01:37 PM  CONSOLE:
[SEVERE] at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
2:01:37 PM  CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.t(MinecraftServer.java:520)
2:01:37 PM  CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.DedicatedServer.t(DedicatedServer.java:240)
2:01:37 PM  CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.s(MinecraftServer.java:483)
2:01:37 PM  CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:415)
2:01:37 PM  CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)

Thanks for your time!

**Comment by alkarinv** [comment]
Sorry for not getting back to you on this, this problem should be gone on the most recent versions.
