### ISSUE TITLE
Cant choose class

### ISSUE THREAD

**Issue by Hezitation** [alkarinv/BattleArena#225]
So I have all my classes set up and everything else works. I got my arena set up and I got my join sign and leave signs. When I put up my classes they look right but I cant right click or left click them to pick a class. The sign is the right color with the [ ] around them. The only thing I did in config was make my own classes and they work but I cant click on them. Does there need to be at least two people in a room to pick a class?

**Comment by ZizzyZizzy** [comment]
They only work in a certain phase of the Battle. For my deathmatch server, just do /dm join will tp me to the waitroom and activate the signs.

**Comment by alkarinv** [comment]
Sorry for not getting to you on this.  You can only use them while "in" the arena.
