### ISSUE TITLE
fly off cmd configs not working

### ISSUE THREAD

**Issue by stevewall85** [alkarinv/BattleArena#228]
Im not sure if more ba related or another plug but i looked at the stageoptions 
Skirmish:
    onEnter:
        options: []
        doCommands:
            - console deop player # will run the command 'deop player' from the console, where player becomes the player name
            - player fly off # will run the command 'fly off' as the player

I added the fly part to the onenter and when a player joins with fly they do not get fly off which they have perms for. I also have set the stage option flightoff  and to no avail. I have noticed theres a mention of running the cmd from console versus the player but i couldnt figure it out. So anyhelp would be appreciated.

world guard report - http://pastebin.com/ZcTvHUFH  
http://pastebin.com/s59mqPVJ spleef arena config

**Comment by alkarinv** [comment]
Hi steve, sorry to leave this hanging. I'm pretty sure these more recent BattleArena versions fix this problem.  I did some fixes for flying.
