### ISSUE TITLE
Arena doesn't send me to waitroom! 

### ISSUE THREAD

**Issue by Basklem** [alkarinv/BattleArena#229]
And before you ask, yes I did see the other issue like this, but that did not work for me.. I'm using ffa, and I join and after the amount of time just sends me into the arena...

Config: http://www.mediafire.com/?g84p6ixskb7ot2o

Arena: http://www.mediafire.com/?9xzzq29rze199md

**Comment by stutiguias** [comment]
same here

**Comment by alkarinv** [comment]
Hi Both, sorry to leave this hanging for so long.  Pretty sure the newest version of BattleArena fixes this problem. Just reopen if it hasn't.
