### ISSUE TITLE
Bug or problem?

### ISSUE THREAD

**Issue by creptor** [alkarinv/BattleArena#231]
I have a problem with battle arena (and spleef)

The region save for game doesn't work (layer save too), I know it should create an schematic to save the "layer" but it isn't working....
I have this problem on monday so I don't have the log, but I can give it to you if you tell me to.

So the problem is because I don't have JAVA 7 or because it's a bug?

-if it needs JAVA 7 to work then, that is the problem :(

**Comment by ZizzyZizzy** [comment]
I've messed around with this and it works perfectly. The docs weren't very clear, so maybe this will help:
1. Cancel and disable all arenas. /arena cancel all, and /arena disable all
2. If you have an existing region defined in your arena, DELETE it. Make sure you note the outer boundary coordinates first.
3. Either use the wand, or use //pos1 x,y,z and //pos2 x,y,z with the previous boundaries to select your region.
4. Update the arena, add items to dispensers and containers, fix whatever needs to be fixed. Signs are irrelevant, as WorldEdit does not save sign text. We put bedrock around everything on the outside to make sure players couldn't fall to their death.
5. Use the arena commands to add that region. On my server that is /dm alter pvp1 addRegion
6. Re-enable the arena, join and test.

You should also note that there are default region flags in the config file. We allow TNT and other explosions, but not mob spawning. It makes for a lot of fun, but be sure the spawn points are created with bedrock to keep people from nuking the spawn points to troll respawning players.

**Comment by creptor** [comment]
I had found the problem...

The arena game name was "#2" and the World Edit schematic sistem does not allow the simbol "#"
