### ISSUE TITLE
Match starts when 0 more players join...

### ISSUE THREAD

**Issue by Benjozork** [alkarinv/BattleArena#233]
Hi,
When I try to play paintball with a 4 teams arena, (we are 2 players, i've set nTeams to 2+ and teamsize to 1+) we wait 59 sec, but it says "Match starts immediatly when 0 more players join (2/infinite)". 
Thanks for your reply,

**Comment by alkarinv** [comment]
Hey Benjozork, this should be fixed in the newer versions of BattleArena.  Going to close this but you can reopen if it's still going on.
