### ISSUE TITLE
Items Drop on Death No Matter What Configuration

### ISSUE THREAD

**Issue by RFSMassacre** [alkarinv/BattleArena#235]
I've been at this for hours with my staff and we can't get items to not drop in Deathmatch. We added "clearInventory" onDeath and players still drop their items. It ruins the entire gameplay of Deathmatch.

Is there anything I can do fix this?

Here's the config file: http://pastebin.com/UfEq9wgE

**Comment by alkarinv** [comment]
That looks right to me, this should be working though on the new versions.  If this is still broken you can reopen this!
