### ISSUE TITLE
doCommand

### ISSUE THREAD

**Issue by nightfire187** [alkarinv/BattleArena#242]
Um this seems to be working differently now.
When a player get the reward it says "You do not have permission to use that command". Witch is enjin plugin saying it. But this is a first.

winner:
    options: [health=20, hunger=20]
    doCommands:
        - console sync console Hub enjin addpoints player 1

It works when a Op or admin wins but win normal players win it gives the no perms.
When i used it that way before it worked fine and sent the command through the console.

**Comment by alkarinv** [comment]
So it should still send it through the console, I haven't changed that code.

the first word is console, so that means the rest of that command should be typed as if it was done on the console
so what does this command say?

/sync console Hub enjin addpoints <player name> 1

**Comment by nightfire187** [comment]
/sync console Hub enjin addpoints 1 = Unknown Command

Ok so i went with a simpler command to see if that may be the issue. 
These are my results.
- console op player = No Permission
- console /op player = Unknown Command

Both messaged the player and only Currey20[1536](29:0) defeated night_fire_187[1063](0:24)!  printed in the console.

I tested this in both custom and default game types. And ArenaPaintball

**Comment by alkarinv** [comment]
ok, I've fixed the problem I believe.

http://ci.battleplugins.com/

That should have a BattleArena version with the fix!

Thanks for bringing this to me nightfire

**Comment by nightfire187** [comment]
Sweet thank you very much!!! Works great now.
