### ISSUE TITLE
Scoreboard disappear with waitroomClosedWhileRunning: false

### ISSUE THREAD

**Issue by kjburr** [alkarinv/BattleArena#244]
If someone joins a game with waitroomClosedWhileRunning: false and the alwaysJoin option, the scoreboard will disappear when they enter the game.  Is it supposed to be this way and is it something that can be fixed?  Thank you for your time!

**Comment by alkarinv** [comment]
Hey Kjburr, I'll be debugging this, I'm currently in the midst of some changes though but thanks for bringing this to me.

**Comment by kjburr** [comment]
I wasn't sure whether it was an actual bug or not, but it did seem like it.  Thanks alkarinv!

**Comment by alkarinv** [comment]
Ok, I think I've fixed these scoreboard problems with the most recent versions, going to close this.  Open it back up if you have the newest version and it is still going on!
