### ISSUE TITLE
Already in arena bug.

### ISSUE THREAD

**Issue by nickdodd25** [alkarinv/BattleArena#245]
Hi there i have been having an issue with either this or it could be tied into the paintball plugin. 

But my issue is if a player joins a paintball arena they then click the paintball leave sign while in the waiting room they will leave the arena but if they try to join any other arenas weather its spleef or paintball they cant as the plugin says "You need to leave first type /arena leave" Then when you type arena leave it says you are not in an arena.

Also to add to this i have paintball set up where once the teams are filled it then counts down from 10 and when they leave during this time is when the bug happens. 

Not sure how much better i could explain it but i keep having issues with this and i then need to /arena reload for the player to to be allowed to join again. 

Thanks
Nick

**Comment by alkarinv** [comment]
Hey Nick, what version is this? ./ba version

Anyway, I think I have fixed this problem.  Here is my dev page where you can get the most recent version.

http://ci.battleplugins.com/

I would like to release this version to bukkit so please let me know of any problems and I'll try to fix asap.

**Comment by nickdodd25** [comment]
[15:06:37 INFO]([BattleArena_v3.9.5.7]): Default  BattleArena  3.9.5.7
[15:06:37 INFO]([BattleArena_v3.9.5.7]): Paintball  ArenaPaintball  1.2.0
[15:06:37 INFO]([BattleArena_v3.9.5.7]): Spleef  ArenaSpleef  1.4.7.1

And ill let you know in a few hours when my server picks back up. 

Thanks
Nick

**Comment by nickdodd25** [comment]
Just tested this by myself by forcestarting the game with one person in it and then leaving and the issue is there yet but once the game counts down and stops after it detects no one in it yet then i get removed from the queue and works like a charm then. 

Thanks
Nick

**Comment by alkarinv** [comment]
So what are the exact steps, just join then leave?

**Comment by alkarinv** [comment]
Oh, and please use the BattleArena I linked to you.
http://ci.battleplugins.com/job/BattleArena/

That has the version with the potential fix

**Comment by nickdodd25** [comment]
i did the versions were from before i installed the new one.

Also if you would like me to show you the issue i'm on my server now? Then you would see exactly what i mean

**Comment by nickdodd25** [comment]
The steps are...

Join arena
Forcestart the arena(paintball in my case)
Then as its counting down leave the arena
The bug occurs then but once the countdown is done the bug goes away with this new version...not sure how else i could explain this.

**Comment by alkarinv** [comment]
Ok, have another version at that same link. Also, what's your ip in case that doesn't fix everything?

**Comment by nickdodd25** [comment]
mg.teamshrimp.com and ill install the updated one quick

**Comment by nickdodd25** [comment]
The issue is there but it does fix its self when the game ends. I believe its happening because i have a count down once teams are picked and default that count i believe was really low. 
Either secondsTillMatch secondsTillBegin forgot what one it was.

**Comment by alkarinv** [comment]
Ok, I believe this is now fixed, you can get it from the ci page!

**Comment by nickdodd25** [comment]
Ok sounds good ill try it in the morning as i just got done with work. ill keep you posted.

**Comment by nickdodd25** [comment]
The issue is fixed thanks alot!!

**Comment by alkarinv** [comment]
great!
