### ISSUE TITLE
Players keep wool team heads

### ISSUE THREAD

**Issue by netherfoam** [alkarinv/BattleArena#25]
You know my config setup with myworlds, arena world, challenge_7 world and multiinv so ill skip that.

Players when they leave the battleground, are keeping their 'wool' teams on their head. So
1. queue for bg in challenge_7 world
2. get tp'ed to bg in arena world, receive wool head
3. /bg leave, teleported to challenge_7 world
4. you strangely have your armour and inventory like you should from challenge_7 world but also have your wool head still.

Small dupe, also a potential pain if you have a diamond helm and it gets replaced by a block of wool.

Unrelated bug,  logging out doesnt throw errors now but the player isn't removed from the battleground after being teleported to their previous location.  e.g.
1. /bg join
2. bg starts
3. disconnect
4. connect
5. your where you are before the bg started
6. do /bg join
7. receive error message 'your still in a bg' -> But you're not "physically" in the bg arena anymore

**Comment by netherfoam** [comment]
Ohh, and thanks for putting up with the bug reports! This plugin seems to be exactly what our server needs. :)

**Comment by netherfoam** [comment]
Config here http://pastebin.com/QSB82KQv
bukkit b2380
BA v3.6.8.2

**Comment by netherfoam** [comment]
....Also, when I'm getting tp'ed out of an arena after a match, it seems that my bottom half is being tp'ed into a block.  Not sure if this happens because of lag or not, but could you possibly try make it a block higher when you tp people out of the bg when it ends? Just i use NCP which means it doesnt like me hopping in blocks at all..

**Comment by alkarinv** [comment]
I think I'll just put in a tp offset.  It's not an issue on the majority of servers,  but depending on the client and the server sometimes that can happen.

The wool head won't replace a diamond helm, so they shouldn't lose inventory out of it, but we don't want the free wool!  I'll look at it

**Comment by alkarinv** [comment]
Should have a fix for this now.  Will be releasing this in BattleArena_v3.6.8.6+.

Hopefully that will work and I can close this.

**Comment by netherfoam** [comment]
Looking forward to using this in bg's bigger than 1v1 :-)

**Comment by netherfoam** [comment]
If you get a working version, upload it to github and I'll compile it? :-)

**Comment by alkarinv** [comment]
It's updated on Github, I also put it up on Bukkit!

Tell me if that fixes the issue!

**Comment by netherfoam** [comment]
Okay I've compiled from github, and it still seems to still be happening in the last build.

When I do /bg leave or relog, its not removing my wool and still thinks i'm "participating" in the battleground

**Comment by netherfoam** [comment]
Just tried the one on bukkit - still having the issue :(

**Comment by alkarinv** [comment]
ugh, alright.  Definitely not fixed :(

**Comment by alkarinv** [comment]
Alright, get me your Skype name, or server, or you can come into battleplugins irc channel irc.esper.net.

I think we can resolve this but I'm at a loss because I can no longer make it happen.

**Comment by netherfoam** [comment]
Yeah sure, what timezone are you from? Im in gmt /utc +  10

Server is maxgamer.org, skype is netherfoam. Ill post when i have spare time though. (Uni/work)

**Comment by alkarinv** [comment]
Didn't see you on.  I guess I'll catch you tomorrow.. I'll be busy with Uni too, but will make time!

**Comment by netherfoam** [comment]
Yeah. I'll be on from now til say 4 hours in the future sometime.

**Comment by netherfoam** [comment]
uman.java:595)
12:22:09 [SEVERE]       at net.minecraft.server.EntityPlayer.damageEntity(EntityPlayer.java:353)
12:22:09 [SEVERE]       at net.minecraft.server.EntityHuman.attack(EntityHuman.java:762)
12:22:09 [SEVERE]       at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:1019)
12:22:09 [SEVERE]       at net.minecraftserverhook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:160)
12:22:09 [SEVERE]       at net.minecraft.server.Packet7UseEntity.handle(SourceFile:36)
12:22:09 [SEVERE]       at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
12:22:09 [SEVERE]       at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
12:22:09 [SEVERE]       at net.minecraft.server.ServerConnection.b(SourceFile:35)
12:22:09 [SEVERE]       at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
12:22:09 [SEVERE]       at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:577)
12:22:09 [SEVERE]       at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
12:22:09 [SEVERE]       at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:473)
12:22:09 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:405)
12:22:09 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
12:22:09 [SEVERE] Caused by: java.lang.NullPointerException
12:22:09 [SEVERE]       at mc.alk.arena.objects.teams.Team.getNDeaths(Team.java:157)
12:22:09 [SEVERE]       at mc.alk.arena.objects.victoryconditions.NDeaths.handleDeath(NDeaths.java:18)
12:22:09 [SEVERE]       at mc.alk.arena.objects.victoryconditions.PvPCount.playerDeathEvent(PvPCount.java:25)
12:22:09 [SEVERE]       ... 29 more
12:22:09 [INFO] [Arena] anton[0](0:0) 

In the latest version, using almost the default arena config (well...)

I don't think it caused any issues, but maybe something to look into :-)

**Comment by alkarinv** [comment]
That definitely could be an issue, I'm not quite sure how that can even happen, but I put in a possible fix for it right now(hard to tell b/c i really don't know how it could occur in the first place).

I think I need to literally need to just copy your plugins folder to find this bug with the wool heads.  I just recently tried with MultiInv, bg in a different world, and still can't make this happen, I swear there must be some plugin where it and Battlearena don't play nicely...

Thanks for your patience man! appreciate it.

**Comment by netherfoam** [comment]
Well, I'm online now.  play.maxgamer.org:25571

Ill jump on skype, or irc now if you like.

It seems like the error is caused when a game of 1v1 ends - its not a 'x lives' or TDM game, maybe thats why the issue?

**Comment by netherfoam** [comment]
Nvm, I need my sleep.

Meanwhile, heres my config
http://pastebin.com/sSf0QPmN

Battleground is in arena world, which is always loaded and players queue from a different world "challenge_7". The inventories are split between the two worlds with multiinv, and notably if I give myself multiinv.exempt perm (so multiinv doesnt affect me) ,  still keep my wool head.

Probably see you on the weekend sometime then.

**Comment by alkarinv** [comment]
Yeah, I need to head to school anyway, i'll talk to you later!

**Comment by alkarinv** [comment]
not sure i'm adding the right netherfoam, alkarinv is my Skype name.

**Comment by netherfoam** [comment]
Yeah i got the add :)

**Comment by netherfoam** [comment]
Okay :| So I edited my config and added [clearInventory] as a prereq, but I wasn't required to have an empty inventory in either the arena world or the default one, and removed from the config the two restoreItems and saveItems I had.  it did appear to me that restoreItems was giving them their wool heads back after fiddling with the config.

Also clearInventory is giving them their items back after the match... O.o Seems desired, but not expected.

Looks like it works now :S

**Comment by netherfoam** [comment]
...Except for the leaving/joining "you're still in a battleground" issue - Is it possible you could add a queue system when someone logs out, and fix that 'still in a battleground' issue? 

E.g. Player A B C & D are in a 2v2.  Player D disconnects, so player E who is in the battleground queue gets teleported into the battleground to replace player D?

**Comment by alkarinv** [comment]
Well glad that it works now!  But I really need to change the name from clearInventory to something that makes sense... this is what it should be.
- preReqs: options: [clearInventory] ->  [storeAll, clearInventory]
- onComplete: options: [clearInventory] -> [clearInventory, restoreAll]

That is really how it should be, I just need to write a parser that will update everyones config's correctly.

I'll put in a fix for the leave but still in a battleground.  If I can I'll try and replace the missing teammate with someone from the queue, but that depends on how easy it is to swap someone out, it's also might be a bit unnerving since they wouldn't get much warning.

**Comment by netherfoam** [comment]
Sounds good ^_^ Thanks again for coding this very good plugin :D

I'll get the queue fix ASAP, but til then I'll be running it anyway :)
