### ISSUE TITLE
Disable all commands in arenas

### ISSUE THREAD

**Issue by SteveCookTU** [alkarinv/BattleArena#250]
I was hoping for a way to disable all commands in an arena.

**Comment by SteveCookTU** [comment]
Also this is an enhancement but I don't usually post issues on github. Therefor I do not know how to label.

**Comment by alkarinv** [comment]
I agree this would be nice, I'll try and add this soon.

**Comment by alkarinv** [comment]
Now available in the version of BattleArena just released to bukkit.  Also available at http://ci.battleplugins.com
