### ISSUE TITLE
Compilation Failure

### ISSUE THREAD

**Issue by Bestle** [alkarinv/BattleArena#251]
I am trying to compile BattleArena from source but it always fails.

Error I get:
http://pastebin.com/LZ86LBgf

**Comment by alkarinv** [comment]
Seems like I didn't have that BattleTracker version up on the BattlePlugins repository.  I updated the BattleArena pom in the version I just released right now 3.9.6.5.5+.  Could you pull this version and try again to see if there are any more pom problems?

**Comment by Bestle** [comment]
Same thing as before. Your repo seems to be returning error 500 for all of the dependencies.

Perhaps I am doing something wrong, I have included the full build log if it helps.

http://pastebin.com/PsTkAbHt

**Comment by alkarinv** [comment]
Ok, so it turns out that Vault changed their repository, which meant that a lot of things were timing out. So another pom update that you should get.

Try again please :)

**Comment by Bestle** [comment]
Still getting pretty much the same error :(

**Comment by alkarinv** [comment]
Ok, nearly 100% confident this is now fixed.  I cleared my maven folder and built from scratch.  I did find several versions that had to be changed.  Fixed pom is now in, and you should be good to go once you get the new changes!

**Comment by Bestle** [comment]
Perfect, thank you!

**Comment by alkarinv** [comment]
sounds like that works so I'm going to close this now.  

Happy coding!
