### ISSUE TITLE
Error with the latest build

### ISSUE THREAD

**Issue by rnoa** [alkarinv/BattleArena#252]
http://pastebin.com/fVdJ5Yng

Please help!

**Comment by alkarinv** [comment]
Could you get me the game config of that game?

Also I put up a possible fix here

 http://ci.battleplugins.com/

**Comment by rnoa** [comment]
Not sure which game it was... Downloaded your dev build now, thanks!

Den onsdag, 26 februari 2014 16:47 skrev alkarinv notifications@github.com:

Could you get me the game config of that game?
Also I put up a possible fix here
http://ci.battleplugins.com/

**Comment by alkarinv** [comment]
Yeah, that might "fix" the error but it was a dirty fix, still trying to figure out exactly what's behind it.

**Comment by alkarinv** [comment]
Ok, believe this is now fixed. Going to close it out, reopen if it's still happening with the most recent versions!
