### ISSUE TITLE
Two Semi-Major Issues

### ISSUE THREAD

**Issue by Masterofjumping** [alkarinv/BattleArena#253]
Hey,

I've started trying to use your plugins after a break and encountered two issues which I cant seem to solve.

The first is when the Spleef event finish's players are teleported out, but they still have the scoreboard present and are listed as still in the Spleef.

The second is that the BAS auto scheduler will only run the event once when triggered and will not run any events after the first.

If you need any specific info feel free to ask.

Thanks

**Comment by alkarinv** [comment]
Those seem very bizarre, which version of BattleArena do you have?
Anyway, the version at http://ci.battleplugins.com should fix because I haven't had other reports on the scoreboard.

The second sounds like a continuing bug.  I'll see if I can fix it.

**Comment by Masterofjumping** [comment]
Running on the latest Bukkit main version, so 3.9.6.7. Will give the Dev version a test now and reply with the results.

**Comment by alkarinv** [comment]
So, with the spleef players, does everyone have the scoreboards? or just the winners or the losers?

**Comment by alkarinv** [comment]
So after testing with the new versions I can't get this scoreboard bug to happen.  Still working on the scheduling though.

**Comment by Masterofjumping** [comment]
Have used the latest Spleef, Battlearena version and still having this scoreboard issue. Just to make it clear, this is not simply an issue with the scoreboard staying up. The commands disabled whilst in the arena are also still disabled when you complete, it pretty much acts like your still in the arena.

Everyone who joins the Spleef receives the scoreboard, since this is actually an issue of players not 'leaving' the game automatically.

**Comment by alkarinv** [comment]
What's your ip Masterofjumping? I've tried multiple ways of doing this and can't fix without being able to recreate it.  I'm sure if I can see and talk with you directly this can be fixed today.

apologies

**Comment by Masterofjumping** [comment]
It's play.runewars.org. Just hop on and I should be around to show you the problems.

**Comment by alkarinv** [comment]
Hey, so when are you on? or you can meet me on the irc channel I have linked on the BattleArena page and say mi name(that pops up a message for me).  I hopped on your server but wasn't sure exactly how to test.

**Comment by alkarinv** [comment]
Oh, nm.  Can just do /spleef join, and /spleef leave.  I did those and I got the scoreboard, then I got it removed when I left.  Then I played a game with someone, and again it got removed.

How do I recreate the problem on your server?

**Comment by alkarinv** [comment]
Also, scheduling should be fixed as of 3.9.7.1+

http://ci.battleplugins.com 

has my dev versions.

Reopen this if the spleef problem is still around, but it seems fixed to me from my jumping on your server.
