### ISSUE TITLE
Message parsing issues

### ISSUE THREAD

**Issue by Bestle** [alkarinv/BattleArena#254]
I am trying to change the server_victory message of a twoTeams match from

server_victory: '{prefix} {winnerlong}&e beat {loserlong}!'

to 

server_victory: '{prefix} {winnershort}&e beat {losershort}!'

The winnershort and losershort do not seem to get parsed correctly and it displays them literally.

I have checked over the code and "{winnershort}" and "{losershort}" definitely seem to exist.

**Comment by alkarinv** [comment]
That is strange, I'll check that out and fix.

**Comment by alkarinv** [comment]
So I can't replicate this. I changed up the messages.yml

<pre>
    teamshort: '&7{name}&e testshort[{ranking}]'
...
        server_victory: '{prefix} {winnershort}&e defeated {losershort}!'
</pre>

And I get this message

<pre>
[Arena] p1 testshort[1431] defeated p2 testshort[1127]!
</pre>

So this appears to be working.  Maybe you need to restart?

**Comment by Bestle** [comment]
It needed a complete server reboot, a BattleArena config reload causes it to break.

**Comment by alkarinv** [comment]
As long as it's working now!  I'll try to put something in the wiki about messages needing a full restart.
