### ISSUE TITLE
Tournaments bugged

### ISSUE THREAD

**Issue by Bestle** [alkarinv/BattleArena#255]
I created an auto tourney by using /tourney auto arena

Players could join fine and there were a total of 44 matches. 41/44 matches were completed however the last three never happened.

I noticed in chat '[Arena Tourney] Ended in a draw' came up a few times in chat but there was no indication as to why.

The last three matches never happened and the tourney never progressed into round 2.

I had to cancel the tourney.

**Comment by alkarinv** [comment]
Maybe if you could get me the log of the tournament it could help me debug it a bit.  I'll see what I can do.

**Comment by Bestle** [comment]
Here's what I have managed to grab from the current stuck tournament:

http://pastebin.com/QyMx2NXD

It's just stuck on 13/14 complete matches and the number of teams is dropping despite no matches taking place.

**Comment by alkarinv** [comment]
Thanks, that will help.  Looking at it now.

**Comment by alkarinv** [comment]
Version 3.9.7.1+ has the fix for tournaments. Would be appreciated if you could test it and make sure it's working properly. Open this back up if it doesn't work!

link to dev version
http://ci.battleplugins.com

**Comment by Bestle** [comment]
Tournament bugged again, though it made it past the first round this time which is an improvement!

http://pastebin.com/8BBTKXrp
