### ISSUE TITLE
Asynchronous Scoreboard Creation Error

### ISSUE THREAD

**Issue by tincopper2** [alkarinv/BattleArena#259]
Gives asynchronous scoreboard creation error when using WGCustomFlags, Commands to join arena by walking through portal.

**Comment by alkarinv** [comment]
As we talked about this isn't a BattleArena problem. WGCustomFlags is running the commands in a separate thread when it should be syncing it with the main server thread.  As 95+% of minecraft needs to be run in the server thread and commands are run through there as well, it's unreasonable to make workarounds for this potentiality. 

...unless it's just that one method in the scoreboard ;)
