### ISSUE TITLE
new ArenaSpleef Config won't work

### ISSUE THREAD

**Issue by Fchen48** [alkarinv/BattleArena#261]
Hey, I'v made a new config copied from the original one and changed some things. 
I used wiki and tried also your posted espleef.yml 
But both ones doens't work, when I type /ba version all I don't see the new gameType. 
Here is my own config: http://pastebin.com/YhXwnM6R

I hope someone can help me! 
br Fchen

**Comment by alkarinv** [comment]
I'll take a look at this hopefully by tomorrow.

**Comment by Gluxdator** [comment]
When you make a new config file for a custome game type, you need to add a new line of code inside the BattleArena.jar>plugin.yml file. Like so:

commands:
    (arena name):
        aliases: [aliase 1, aliase 2,...]
        description: The description blah blah
        usage: Problem loading plugin, please send errors on startup to alkarin_v

You will see others in there, so you can copy, paste, and edit. Then your commands for your new game type should work.
