### ISSUE TITLE
Minecraft 1.6.4 Version

### ISSUE THREAD

**Issue by rileym28** [alkarinv/BattleArena#262]
Do you know where I can download a version to run on Bukkit <1.6.4-b2918jnks>?

**Comment by alkarinv** [comment]
Not sure what you mean. But here are my release builds.

http://dev.bukkit.org/bukkit-plugins/battlearena

and 
http://ci.battleplugins.com

is my dev builds

**Comment by rileym28** [comment]
Do you have a release build for CraftBukkit 1.6.4-RO2.0 ?

**Comment by alkarinv** [comment]
All of my versions will work between 1.2.5, tekkit servers, and the most recent craftbukkit.  So just use the latest.

If you could please use this one

http://dev.bukkit.org/media/files/780/958/BattleArena.jar

I just uploaded it and would like to have some people test it out before it gets cleared by bukkit

**Comment by rileym28** [comment]
Okay, thank you.
