### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Benjozork** [alkarinv/BattleArena#264]
Hey,
I've tried to start my server with BA installed, but it freezes at 'Registering classes arrcher, monk etc.' This is pretty annoying because i need to setup my server quickly.
Thanks for your help.

**Comment by alkarinv** [comment]
That should never happen for sure.  Are there any errors of any sort on the console?

**Comment by Benjozork** [comment]
No, just this.

**Comment by alkarinv** [comment]
Can you pastebin your startup log for me please? 

And are you sure it's BattleArena? If you take BattleArena.jar out and restart does the server start normally?

**Comment by Benjozork** [comment]
Oh sorry, i just re-installed it and all works now ! :)
Thanks for your help!

And yes if i take BattleArena out it started normally.

**Comment by alkarinv** [comment]
What what! That is crazy... so it just works now? Well... I guess I'll close this then.  Please let me know if it happens again!!
