### ISSUE TITLE
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'NTE4'.

### ISSUE THREAD

**Issue by dem0niak** [alkarinv/BattleArena#265]
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 03/04/14 13:54
Description: Unexpected error

java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'NTE4'.
    at ayr.a(SourceFile:206)
    at biv.a(SourceFile:1129)
    at hr.a(SourceFile:99)
    at hr.a(SourceFile:13)
    at ef.a(SourceFile:164)
    at biy.e(SourceFile:212)
    at azd.o(Minecraft.java:1647)
    at azd.ad(Minecraft.java:997)
    at azd.e(Minecraft.java:913)
    at net.minecraft.client.main.Main.main(Main.java:123)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at ayr.a(SourceFile:206)
    at biv.a(SourceFile:1129)
    at hr.a(SourceFile:99)
    at hr.a(SourceFile:13)
    at ef.a(SourceFile:164)
    at biy.e(SourceFile:212)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [bje['dem0niak'/4386714, l='MpServer', x=55,84, y=91,12, z=0,54]]
    Chunk stats: MultiplayerChunkCache: 81, 81
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,90,0), Chunk: (at 0,5,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 72063014 game time, 70638458 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 37 total; [bje['dem0niak'/4386714, l='MpServer', x=55,84, y=91,12, z=0,54], rf['entity.ItemFrame.name'/1119, l='MpServer', x=27,50, y=105,50, z=-13,06], bld['filing'/4303732, l='MpServer', x=10,59, y=89,00, z=1,00], bld['Takix10'/4438722, l='MpServer', x=-2,00, y=90,00, z=5,94], rf['entity.ItemFrame.name'/1126, l='MpServer', x=26,50, y=105,50, z=-13,06], bld['Pikachu'/4155509, l='MpServer', x=14,53, y=79,00, z=11,38], rf['entity.ItemFrame.name'/1124, l='MpServer', x=26,50, y=103,50, z=-13,06], rf['entity.ItemFrame.name'/1125, l='MpServer', x=26,50, y=104,50, z=-13,06], rf['entity.ItemFrame.name'/1122, l='MpServer', x=27,50, y=102,50, z=-13,06], rf['entity.ItemFrame.name'/1123, l='MpServer', x=26,50, y=102,50, z=-13,06], rf['entity.ItemFrame.name'/1120, l='MpServer', x=27,50, y=104,50, z=-13,06], rf['entity.ItemFrame.name'/1121, l='MpServer', x=27,50, y=103,50, z=-13,06], bld['evochan'/4430007, l='MpServer', x=19,30, y=92,95, z=7,40], bld['Noke'/4432409, l='MpServer', x=-1,50, y=89,00, z=31,25], rf['entity.ItemFrame.name'/1166, l='MpServer', x=31,50, y=90,50, z=18,94], rf['entity.ItemFrame.name'/1191, l='MpServer', x=38,94, y=102,50, z=-26,50], rf['entity.ItemFrame.name'/1190, l='MpServer', x=38,94, y=103,50, z=-26,50], rf['entity.ItemFrame.name'/1189, l='MpServer', x=38,94, y=104,50, z=-26,50], rf['entity.ItemFrame.name'/1188, l='MpServer', x=38,94, y=105,50, z=-26,50], rf['entity.ItemFrame.name'/1195, l='MpServer', x=38,94, y=102,50, z=-23,50], rf['entity.ItemFrame.name'/1194, l='MpServer', x=38,94, y=103,50, z=-23,50], rf['entity.ItemFrame.name'/1193, l='MpServer', x=38,94, y=104,50, z=-23,50], rf['entity.ItemFrame.name'/1192, l='MpServer', x=38,94, y=105,50, z=-23,50], rf['entity.ItemFrame.name'/1199, l='MpServer', x=38,94, y=102,50, z=-20,50], rf['entity.ItemFrame.name'/1198, l='MpServer', x=38,94, y=103,50, z=-20,50], rf['entity.ItemFrame.name'/1197, l='MpServer', x=38,94, y=104,50, z=-20,50], rf['entity.ItemFrame.name'/1196, l='MpServer', x=38,94, y=105,50, z=-20,50], rf['entity.ItemFrame.name'/1202, l='MpServer', x=38,94, y=103,50, z=-18,50], rf['entity.ItemFrame.name'/1203, l='MpServer', x=38,94, y=102,50, z=-18,50], rf['entity.ItemFrame.name'/1200, l='MpServer', x=38,94, y=105,50, z=-18,50], rf['entity.ItemFrame.name'/1201, l='MpServer', x=38,94, y=104,50, z=-18,50], rf['entity.ItemFrame.name'/1206, l='MpServer', x=33,50, y=90,50, z=18,94], rf['entity.ItemFrame.name'/1204, l='MpServer', x=36,94, y=90,50, z=13,50], rf['entity.ItemFrame.name'/1205, l='MpServer', x=36,94, y=90,50, z=15,50], bld['Diamondorange'/4245262, l='MpServer', x=17,63, y=102,00, z=-28,69], bld['evochan'/4430007, l='MpServer', x=0,59, y=89,22, z=3,74], bld['Diamondorange'/4245262, l='MpServer', x=42,09, y=95,50, z=-25,16]]
    Retry entities: 0 total; []
    Server brand: CraftBukkit
    Server type: Non-integrated multiplayer server
Stacktrace:
    at biz.a(SourceFile:284)
    at azd.b(Minecraft.java:2595)
    at azd.e(Minecraft.java:942)
    at net.minecraft.client.main.Main.main(Main.java:123)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.7.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 39286112 bytes (37 MB) / 131457024 bytes (125 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 1 total; -Xmx1G
    AABB Pool Size: 165 (9240 bytes; 0 MB) allocated, 2 (112 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    Launched Version: 1.7.2
    LWJGL: 2.9.0
    OpenGL: ATI Mobility Radeon HD 5730   GL version 3.2.9236, ATI Technologies Inc.
    Is Modded: Very likely; Jar signature invalidated
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 118 (6608 bytes; 0 MB) allocated, 49 (2744 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)

i have this crash bug everty i try to start an arena /or the arene when we pvp,
its same for other member

**Comment by alkarinv** [comment]
Every time!? That is absolutely crazy. What is your ip? I'd like to hop on.  It looks like some sort of scoreboard problem, but I've never seen this before.

**Comment by dem0niak** [comment]
yeah , its like one game its work then 5 game bug

check my serv obsifight.fr (french serv) ask for dem0niak 
the arena isnt always open due to this bug 

i can post for the scoreboard for you

sometime it crash when we fight,sometime when we wait the countdown to start the game

**Comment by alkarinv** [comment]
I can't seem to get on. What version of craftbukkit are you running?

Could you post the scoreboard please. But also what other scoreboard plugin are you running.  I know I don't use teams such as "NTE4", so it's possible that just by my using the bukkit scoreboard this other plugin gets confused and is causing the crash.

**Comment by alkarinv** [comment]
Seems like this magically fixed itself on restart.  Please let me know if this happens again!

**Comment by dem0niak** [comment]
Still crash 
but i have InfoBoard plugin
i am gonna try on my new event serv
without info board

**Comment by alkarinv** [comment]
I looked through the InfoBoard plugin, they use the standard bukkit scoreboard like I do, which should be fine.  Some plugins modify the player scoreboard directly (which is very dangerous) and what I was worried about.  I also didn't see anything for "NTE4" so I'm not sure where that team name is coming from... is that a player name?

**Comment by dem0niak** [comment]
no some time its NTE1 NTE2 NTE3

i use bukkit and spigot is that a problem?

**Comment by dem0niak** [comment]
i will battlearena on an other server with less plugins

**Comment by alkarinv** [comment]
Bukkit and spigot is fine.  I just want to know which plugin is using those teams... it's not me, and that is the real cause of the problem I think.  I think with that plugin will crash ANY other plugin that uses scoreboards (factions, mcMMO, etc).  But, I can't know for certain until I can find out which plugin it is... so any ideas on that?

**Comment by dem0niak** [comment]
well i am building an event serv i reduce the plugin (faction/info-board, killstats,and other..)
i am uploading my map with the arena and i will try with 20 players,

i noticed that crash are more frequent with more player

**Comment by dem0niak** [comment]
take a look
http://image.noelshack.com/fichiers/2014/14/1396630427-2014-04-04-18-51-58.png
its my plugins 
i noticed that we cant see battlearena scoreboard some time too
and there is no coloured nickname (red or blue for exemple for red team and blue team) on our head before the first death

**Comment by alkarinv** [comment]
Yeah, it's definitely a conflict.  One of those plugins (not sure which one) is doing something dangerous with Scoreboards. That means it's probably taking over the scoreboard even during the games, which is why the colors etc aren't working.  I'll take a look when I can to figure out which of those is doing the dangerous operations.

**Comment by alkarinv** [comment]
Alright, that was easy.  I'm nearly 100% sure it's NameTagEdit, that plugin is VERY dangerous and will crash clients if ANY other plugin uses scoreboards. I gave a more complete description here.

https://github.com/alkarinv/BattleArena/issues/258

Look at my 3rd comment.

**Comment by dem0niak** [comment]
thx :3

**Comment by alphaalphaalpha2** [comment]
Name tag edit is causing the problem
