### ISSUE TITLE
Teams custom colors?

### ISSUE THREAD

**Issue by creptor** [alkarinv/BattleArena#273]
well I whanted to make sertain colors for teams... so i can have red, blue, green and yellow for the game, insted of the red, blue, black and white.

plz help

**Comment by TruDan** [comment]
plugins/BattleArena/teamConfig.yml

All in there, I believe it goes in order from top-bottom

**Comment by creptor** [comment]
Yea it was that. I posted this because a /ba reload doesn't update the teams
