### ISSUE TITLE
Per Class Permissions

### ISSUE THREAD

**Issue by murfthesmurf** [alkarinv/BattleArena#28]
It would be very helpful to me if you would please make a per class permissions system.  For example, if you had the class "Swordsman" I would like it if I could make it so only specific users could use that class with a permissions node something like this: "battlearena.classes.use.Swordsman"  Thank you for taking the time to read this. Keep up the good work! :)

**Comment by alkarinv** [comment]
I like this idea!
I don't think it is for everyone though, so I'll have to make a config option to turn it on.  but consider this to be on the list of enhancements!

**Comment by murfthesmurf** [comment]
Haha I was trying to change it to enhancements but I didn't know how to xD. Thanks for the response!

**Comment by alkarinv** [comment]
Now added in version 3.6.8.5.

I'll be releasing it to bukkit soon.
