### ISSUE TITLE
[!] There is something wrong with your chest loading code!

### ISSUE THREAD

**Issue by Dromantor** [alkarinv/BattleArena#286]
Yesterday i spent hours on configuring my arena and then i reloaded my server. All Items in the chest are gone! After dicking around 4 hours ingame where i tried to overwrite config file, reload config, re-register chests, etc. I was not able to fix this issue.
Today i took a look at the arena loading section of your code and found this:
![Error](https://cloud.githubusercontent.com/assets/1822013/3310454/6521ea12-f6b4-11e3-9311-06be24f178d3.png)
Now it seems very clear .... there can't be any items in the chest if your are reading the false (even not existing) config section. If i change items into giveItems in the config file manually everything works .... but after each ingame change i must fix the config file again.
Please fix!

**Comment by Europia79** [comment]
@godlessmind 

I got some free time and was looking over old issues. This is now fixed in the BattlePluginsDev fork.

Awesome bug report, btw ! Made it really easy to fix.

**Comment by Zach443** [comment]
This has been resolved in BattlePlugins/BattleArena@bdfa54f0b54fec362c673b750bd161ab8c94ce36
