### ISSUE TITLE
Plugin Load Error

### ISSUE THREAD

**Issue by FilipK-CZ** [alkarinv/BattleArena#308]
Plugin load bud show error message and all commands don't work :/
On use someone command plugin say "Problem loading plugin, please send errors on startup to alkarin_v"
pastebin.com/WvawimG4

**Comment by Europia79** [comment]
This has been fixed in BattleArena2

The source code for the fix is here:
https://github.com/Europia79/WorldEditUtil

The download is here:
http://dev.bukkit.org/bukkit-plugins/battlearena2/

**Comment by FilipK-CZ** [comment]
Thanks :)
