### ISSUE TITLE
Unable to let an arena allow visitors.

### ISSUE THREAD

**Issue by James76931** [alkarinv/BattleArena#312]
Hey,

When I try to watch a match, I am given a message saying "That arena does not allow visitors!" and I cannot seem to find a way to allow them.

This is probably me just not being able to find it on the wiki, but if it's not - that's the issue.
~ James

**Comment by Europia79** [comment]
@James76931 

what command(s) are you using ?

**Comment by Zach443** [comment]
If you are using /arena watch then it doesn't work. I've know about this for a while, but I have no clue what the problem is, nor have I had the time to look into it.
