### ISSUE TITLE
/aa showspawns [arena]

### ISSUE THREAD

**Issue by netherfoam** [alkarinv/BattleArena#41]
This is a suggestion,

When you do /aa showspawns, you're already displaying player spawns, but how about the item spawns and mob spawns as well?  Maybe in a different colour wool though

**Comment by netherfoam** [comment]
Another unrelated suggestion!
What're your thoughts on letting us use "unsafe" enchantments? E.g. sharpness on an axe.

**Comment by alkarinv** [comment]
Heh, I had forgotten that I still had /aa showspawns.  What I wanted to do is actually spawn all the items/mobs, but i kind of dropped it as I didn't think anyone was using it.  Maybe it's back on the table!

Unsafe enchantments, sure I can do that :)

**Comment by netherfoam** [comment]
And maybe just use player.sendBlockChange() instead of actually change the blocks to wool? this'd fake the block changing, but once the player leaves and forgets to /aa hidespawns [arena], they're still changed?

**Comment by alkarinv** [comment]
I didnt even know about sendBlockChange() !!!
I like this a lot better.  Yeah if you forget... you're hosed :(

**Comment by alkarinv** [comment]
Alright fixed in v3.6.9.8+ .  that sendBlockChange is amazing!

it now shows item and mob spawns as well.

Commands are now based on the selection so.

/aa sel <arena name>
/aa showSpawns
/aa hidespawns

**Comment by netherfoam** [comment]
:) awesome!

Can i make a suggestion with the aa select though? Can you make it more time, or make it check that your distance since where you selected it is within a certain limit? Eg.

Im next to my arena, do /aa sel, make some changes, eat lunch, come back, continue making changes.  When i leave the area and try to use aa without reselecting, it asks me to reselect the arena?

Just a thought.

**Comment by alkarinv** [comment]
how much time should it be by default? and I'll add an option for the timeout in the config

**Comment by netherfoam** [comment]
I think 2-3 minutes would be a bit more reasonable, as its a pain to figure out the damage values for some things and the enchants for me

**Comment by alkarinv** [comment]
alright just going to set the default to 5 minutes.  will be configurable too.  Btw thanks for helping me with all this stuff, much appreciated.
