### ISSUE TITLE
[Bug] Reselecting class when a default one is set

### ISSUE THREAD

**Issue by netherfoam** [alkarinv/BattleArena#43]
Thanks for fixing that freeze last upload :D

Now I'm having a problem though where players can select a class initially, and that's fine, but when they respawn they can't select another class.

I have a default class specified, which may be causing the issue.

If you need my configs i can send them to you, or you can look at the ones I linked on the devbukkit comment section :)

BA v3.6.9.8

Cheers again!
-Nether.

**Comment by netherfoam** [comment]
Oh, and classes are not persistant for us.

**Comment by alkarinv** [comment]
I guess I put in a bug when I put in the new respawnWithClass, fixed now in Version3.6.9.8.5+.

What do you mean classes are not persistent? like the choice doesn't stay between matches?

**Comment by netherfoam** [comment]
By that i meant we dont have respawnWithClass enabled

Thanks again!

**Comment by alkarinv** [comment]
ok! then I guess this is fixed :)
