### ISSUE TITLE
[Bug] RespawnWithClass not giving potion effects

### ISSUE THREAD

**Issue by netherfoam** [alkarinv/BattleArena#46]
BA 3.6.9.8.5
Bukkit b2399

Also, how can I allow users to change class after theyve selected one in a bg?

Config: http://pastebin.com/QnMcKQFm

**Comment by alkarinv** [comment]
So respawnWithClass is not giving out the potion effects.. and they also can't change class after they've selected?

It's like a bug spawned a bug.

**Comment by alkarinv** [comment]
I don't see anything wrong with your config, so it must be on my end.

**Comment by alkarinv** [comment]
Both problems fixed in 3.6.9.9+
