### ISSUE TITLE
single arenas (no rotation)

### ISSUE THREAD

**Issue by zippa713** [alkarinv/BattleArena#49]
Instead of making multiple arenas and cycling through them, being able to chose the arena you want ot play would be nice option. but keep the rotation option too.

so say you have arena A B and C-
currently:
You type /skirmish join; then you play the arena A, next group plays a different arena B. (you really wanted to play arena B)

purposed change:
you type /skirmish join arenaB; you now play arena B and not whats on cycle.

idea-
Just que for the arena you want to play as well as que for the cycle
both  "/skirmish join" and  "/skirmish join arenaB"

**Comment by alkarinv** [comment]
It's already in :) You can choose which arena you want to join.
if you have skirmish arenas A, B, C

/skirmish join B

**Comment by zippa713** [comment]
let me ask you this... the spleef and paintball add-ons, they can do it? like on my server I have spleef and spleef2 as arenas... if i use /spleef join spleef2, i still que for spleef and not spleef2...does it only work for battle arena itself?

**Comment by alkarinv** [comment]
really?

if you can't it's a bug. let me check it out.

**Comment by zippa713** [comment]
if you want you can join my server... play.fakemc.com and ill show you

**Comment by alkarinv** [comment]
Verified as a bug, I'll see if I can fix it sometime today.

**Comment by zippa713** [comment]
no rush... I just didnt know it was implicated in battle arena since I mainly use spleef and paintball because of battle tracker!

**Comment by alkarinv** [comment]
Because of BattleTracker ? confused as they all use BattleTracker if you have it.

**Comment by zippa713** [comment]
im saying i like to use your mods since they all play nice and have battle tracker!

**Comment by alkarinv** [comment]
Oh cool!  Yeah I think BattleTracker and the ranking system adds a lot to combat.  A bit surprised more people don't use it. (it's very easy to hook into)

**Comment by alkarinv** [comment]
Bug fixed in 3.6.9.9.1+

**Comment by zippa713** [comment]
was it a BA bug or a Spleef bug? what needs updated?

**Comment by alkarinv** [comment]
It was a battlearena bug.  I think bukkit is swamped so I'll release a version here on github for you.

**Comment by zippa713** [comment]
were you able to post the bug fix for me?

**Comment by alkarinv** [comment]
Here you go.

https://github.com/downloads/alkarinv/BattleArena/BattleArena.jar
