### ISSUE TITLE
Arena Waitroom

### ISSUE THREAD

**Issue by lvvipervvi** [alkarinv/BattleArena#52]
Every time I join my arena it doesn't send me to the Arena Waiting room.  I have Multiworld plugin installed on my server and this is on a different world than the main world. Here is my files.

http://pastebin.com/d8DshifF   <-----Config File

http://pastebin.com/hJadJYiG   <-----Arena File

**Comment by alkarinv** [comment]
This isn't explained well but for normal matches like battleGround,  you should add the teleportWaitRoom into the onPrestart section (add it if it's not there)

try that out and see what happens

**Comment by alkarinv** [comment]
I'm going to assume that it works, reopen if you are still having trouble!
