### ISSUE TITLE
[Feature request] More heroes support :D

### ISSUE THREAD

**Issue by kahlilnc** [alkarinv/BattleArena#54]
how bout being over a certain level? Since players on my server can't pvp with ppl below level 10 :( For balance related reasons

**Comment by alkarinv** [comment]
Yep, i'll definitely do this.  But first... I need to fix events so that people can start them by clicking a sign.

**Comment by kahlilnc** [comment]
Awesome, and I wanted to ask if you remembered about the configurable time for events starting after one ended? :D

**Comment by alkarinv** [comment]
check your config.

there should be an option called timeBetweenScheduledEvents: 30

you can change it there! :)

**Comment by kahlilnc** [comment]
oh had to regen config to get that. :O

**Comment by alkarinv** [comment]
Should be added in v 3.7.0+!
