### ISSUE TITLE
/team create 

### ISSUE THREAD

**Issue by freakyy85** [alkarinv/BattleArena#55]
Hi. 
1. After doing /team create <player>, and after that player accepts the team invite, I get with /team list
   # Players 0 and with /team info - you are in no team. Dueling another player works - me in team with <player> against that player.
2. Doing /team disband gives me a help message. Writing /team disband <otherplayer> gives a message "Team disbanded by <otherplayer> means, that otherplayer gets a message "Team disbanded by himself" even though it was me?

**Comment by alkarinv** [comment]
Odd, that is definitely not correct.  I'll check it out.  I'll try to fix it along with other issues tonight!

**Comment by alkarinv** [comment]
Fixed in 3.7.0.6+
