### ISSUE TITLE
/duel in teams & changing arena options!

### ISSUE THREAD

**Issue by freakyy85** [alkarinv/BattleArena#58]
I created a team with 3 people. Then I did /pb duel <nick1> <nick2> <nick3> --> from then on the arena was set to require 6 players to start! This happened to all my arenas which were default to play 1vs1 games.

**Comment by freakyy85** [comment]
well i mean /pb duel player1 player2 player3

**Comment by freakyy85** [comment]
oh i now know im still in a team lol.

**Comment by alkarinv** [comment]
Yeah, if you join a team of 3 people.  It assumes you want to fight as a team of 3.  I'll try to make that clearer from the message though.  It should say something like "You joined the arena as a team of 3!"
