### ISSUE TITLE
Spleef & Layer regeneration

### ISSUE THREAD

**Issue by freakyy85** [alkarinv/BattleArena#59]
Hey ;D

I just tried to do: /spleef setLayer spleef1 1 45
The thing is, the layer doesnt regenerate. The layer was already set before. I selected it again, did the above but the layer doesnt regenerate.

**Comment by alkarinv** [comment]
herm... you are finding all sorts of good bugs!

I can't make this bug work though.  I'll have to talk to you tomorrow when you are on.

**Comment by alkarinv** [comment]
Fixed in 3.7.0.6+
