### ISSUE TITLE
Instant teleportOut onDeath

### ISSUE THREAD

**Issue by bgb** [alkarinv/BattleArena#64]
hello, is it possible to make this option available? Because i set up simple arena 1v1 like this:

onDeath:
        options: [respawn, teleportOut, clearInventory]
onComplete:
        options: [teleportOut, deEnchant, clearInventory]

and when one of players die, he has to push respawn button, then he appears at respawn place (not on arena) and after this he is teleported back to place where he was before joining arena. Could u add option: 'respawn on death straight to te position before joining arena'? or maybe remove death at all? I think another plugin called mobarena is teleporting u out of arena when u would die normally (but im not sure about this). This would also solve the problem with -power on faction plugin.

**Comment by alkarinv** [comment]
so actually what you are asking for is default.  so get rid of the teleportOut inside of OnDeath, and get rid of the respawn.  and make sure you don't have victoryCondition: highestkills

**Comment by bgb** [comment]
Doesnt seem to work. I set it like below but on death while on arena I still need to click respawn button and it sends me to respawn place far away from arena.

arena:
    enabled: true
    type: versus
    database: arena
    rated: true
    prefix: "&6[Arena]&e"
    onJoin:
        options: [pvpOff]
    preReqs:
        options: [clearInventory]
    onPrestart:
        options: [pvpOff, teleportWaitroom]
    secondsTillMatch: 30
    onStart:
        options: [teleportIn, pvpOn,blockBreakOff]
    onSpawn:
        options: [deEnchant, hunger=20, health=20]
        #giveClass:
            #default: gladiator
        items: # ignored if options doesnt have "giveItems"
            - bread: 5
    onDeath:
        options: [clearInventory]
    onComplete:
        options: [teleportOut, deEnchant, clearInventory]
    winner:
        options: [health=20, hunger=20, giveItems]
        items: # ignored if options doesnt have "giveItems"
            - bread: 5

**Comment by alkarinv** [comment]
So when they click respawn, they go to the world respawn? and not back to where they joined from?

If that is the case give me your plugin list, b/c it sounds like some other plugin is making that happen.  If it is I can write a workaround for that plugin.

**Comment by bgb** [comment]
Yes, indeed its teleporting players to world respawn point. 

Plugins i use:
-Essentials
-Shopkeepers
-BattleArena

So would it be essentials which makes the conflict? Oh, and i remember i set world respawn point with McEdit when i was editing my map.. so maybe thats the case...

**Comment by alkarinv** [comment]
Just setting the respawn point shouldnt cause it.  B/c I override the normal respawn point when they respawn and set it their join location.  But maybe McEdit is overriding my changes... I'll check.

Also give me your ip so I can check it out

**Comment by bgb** [comment]
oww:D my "server" is running on my desktop pc and there is mostly 2 players online (me and my buddy), We r planning to buy dedicated server in the future but atm we r preparing plugins and setting everything up.
I also have dynamic IP so if u wanna login u can do it now, i will be online: 178.43.31.89:25565 (btw its 1.3.2)

**Comment by bgb** [comment]
thanks for helping and solving my problem:) Last version of plugin and everything works perfect...

**Comment by alkarinv** [comment]
excellent!
