### ISSUE TITLE
Arena duels do not add players as member to worldguard regions.

### ISSUE THREAD

**Issue by darrenstraight** [alkarinv/BattleArena#65]
Hello,

Thought id have a go at the latest build 3.7.2.0

It seems that duels do not add the players as a member to arena worldguard region, or at least thats what I beileve is happening.

I have my arena setup to have a world guard region which in turn has a flag of "entry: deny". 

Yesterday on 3.7.1.7 it worked fine, players could do /arena duel and they would be members of that region and match would work all ok, them being able to move.

But now they do /arena duel and once the match starts they are inside and cant move, no permission message from worldguard so they have to /arena leave or eventually get kicked for flying which puts them back in the waiting room on reconnect.

Whats interesting though is that /arena join works fine when all players are in, players can move around as they should be able to, with spectators still not being able to enter while game is on or off.

Hope that makes some sense?

Thanks,
Darren

**Comment by alkarinv** [comment]
It does, I'll see if I can verify locally and fix it.

**Comment by alkarinv** [comment]
Ok, turns out that bukkit is loading the worlds a little later than it used to.  This is probably just a temporary bukkit bug, but I have a workaround now.  So this will be fixed in 3.7.2.1+!

Sorry about this, and thanks for letting me know.

**Comment by darrenstraight** [comment]
No, thank you! :)
