### ISSUE TITLE
Multiworld - Switching inventories

### ISSUE THREAD

**Issue by ondrajz** [alkarinv/BattleArena#67]
I use this plugin for my PvP world. I have 3 different worlds on my server, survival, creative and pvp.

In PvP I only have these arenas. Bug: when I join arena (which can be done only in the world PvP, due permissionsex and also your sameWorld flag), but if I just join for queue and leave the world it will still count me in queue and when it starts and it teleports me to that world it somehow collides with other plugin Multiverse-Inventories and that one gives me the items just moment later after arena does so I am stuck with those items.

**Comment by alkarinv** [comment]
Alright so the bug is.
1) join in world1
2) go to world2
3) get teleported into world1 by the arena
4) collision and badness?

**Comment by ondrajz** [comment]
Yes, as you said. My suggestion would be (now I am not sure how the bukkit events works so I am just guessing) that you would detect when someone leaves the world and cancel him out of queue or duel or anything else that might teleport him to the other world.

**Comment by alkarinv** [comment]
Alright, so now with sameWorld, players will leave the queue.  It also checks for the sameWorld flag when they are about to get teleported in.. so this should be completely resolved.

Fix is in 3.7.4.1+
