### ISSUE TITLE
New type of arena/event

### ISSUE THREAD

**Issue by ondrajz** [alkarinv/BattleArena#68]
My friend came up with an idea for new type of arena/event.

I will try to explain:

There are two bases, rails go from one to another, onStart the cart will spawn in middle and first team that pushes the card into their base (where it will go over detector rail or whatever) will win and you respawn at you base when you die.

**Comment by darrenstraight** [comment]
Sounds a bit like TF2 Payload to me ;-)

http://wiki.teamfortress.com/wiki/Payload

**Comment by ondrajz** [comment]
Might be, friend plays TF2 I don't. So he probably took it from there. Is this possible to do via your API?

**Comment by alkarinv** [comment]
It's definitely possible.  I'll see if I can make it sometime in the next week or so.  Though I might get busy so no guarantees! but I would like this match type in BattleArena.

**Comment by ondrajz** [comment]
Thank you!
