### ISSUE TITLE
Top players - sign

### ISSUE THREAD

**Issue by ondrajz** [alkarinv/BattleArena#70]
Is it possible to make a feature like this; I would put a sign write there [Top Arena] and the rest 3 lines would be filled (and updated) with the top 3 players. 

I know there is a /arena top command but not many player know that so if this would be near every type of arena it would be seen by every player passing by and maybe even encourage them to play.

**Comment by alkarinv** [comment]
That's already planned.  But it will be part of BattleTracker.  So it's on the todo list, just a matter of time.

**Comment by ondrajz** [comment]
I should really get into Java maybe I could help with some forks, since you welcome that.

**Comment by ondrajz** [comment]
Would this be difficult to do for queues as well? I could then make a wall of all arenas and display how many people are currently waiting in queue.

**Comment by alkarinv** [comment]
Again it's something I want to do.. but my next priority is to make a voting system to start events w/o the maximum number of players

It's not really that difficult though.  It just needs a way to store the signs in a yaml file/db, restore them. and update the signs based on the queue.

**Comment by alkarinv** [comment]
Oh, thought of a complication.  What happens if 2 or 3 of the same event is open at the same time?

Which sign would display what?

**Comment by ondrajz** [comment]
Are there queues in the events? I thought only matches had queues. Anyway the signs would be bound to different instance of event/arena for each sign, I guess.

**Comment by alkarinv** [comment]
There aren't queues for events.  But multiple FFA's can be happening at once.

I guess it could be by arena though... there would only be 1 ffa in one arena...

**Comment by ondrajz** [comment]
For events it could also be used for displaying countdown. So when players are in the waitroom they see how much time is remaining till the start.
