### ISSUE TITLE
Incorrect message after using /bg leave

### ISSUE THREAD

**Issue by netherfoam** [alkarinv/BattleArena#72]
BattleArena v3.7.4.5
#1 Use /bg join to successfully join the queue
#2 Use /bg leave to leave the queue.  You're sent a message ('You're not in any queues') and you leave the queue as expected.  The message should be 'You've left the queue' or something instead.

**Comment by alkarinv** [comment]
Your message is SO LOUD! and BIG. :)

But thanks, that is definitely not the right message to send them.  I'll fix and put it in the next release.

**Comment by netherfoam** [comment]
Lol, sorry, I couldn't remember how to format lists in github :/

**Comment by ondrajz** [comment]
Same for other types, arena too for sure.

**Comment by alkarinv** [comment]
If you get the version up on github now it should fix this display bug
