### ISSUE TITLE
Make messages for the arena's as a setting to be local or global

### ISSUE THREAD

**Issue by titen96** [alkarinv/BattleArena#74]
Well I've used this plugin along with the arena paintball plugin, I'm not sure if it was the paintball plugin that was send the messages or the actual API that it uses, but the problem is that the messages whether a player has won or not, or when a match starts tends to spam the chat, is it possible to make these messages only to people who have joined an arena?

**Comment by alkarinv** [comment]
There is, check this out.  Basically you go into BattleArena/config.yml and change the message options there.

https://github.com/alkarinv/BattleArena/wiki/Configsetup#wiki-Message_Options

if that doesn't make sense let me know!
