### ISSUE TITLE
Multiworld bug

### ISSUE THREAD

**Issue by Adondriel** [alkarinv/BattleArena#75]
This is going to get rather confusing so i'll explain the world setup first.
We have Chaos and creative available for everyone and pvp, pve, and other challenge maps available for those that apply.(each of these are worlds)

Now to the issue.
Someone goes into creative world, gives themselves a stack of diamond blocks.
He goes back to spawn(different world) because i have joining the arena from creative disabled(forthis reason).
Once at spawn he tells someone to join the arena, spleef or paintball. 
once the 6 seconds starts he jumps back into the portal to creative world.
He then gets TPd into the arena, and i was told you have to lose(i have not tested winning)
once he loses he gets teleported back to spawn and has creative mode and creative inventory.

**Comment by alkarinv** [comment]
Sure sounds like a bug, which version do you have?

Anyway, I think the quick fix is this.  inside preReqs: put the option "sameWorld" so that they can only join an arena from the same world.

<pre>
    preReqs:
        options: [sameWorld]
</pre>

**Comment by Adondriel** [comment]
Thanks. I'll test that out.

**Comment by alkarinv** [comment]
What version are you running? it would be nice to find the bug.

**Comment by Adondriel** [comment]
Where can i find the version?

**Comment by Adondriel** [comment]
Let me see, for some reason i keep ending up with two of the jars in my folder.

**Comment by Adondriel** [comment]
the one plugin.yml says, 3.7.4.8.2 the other is 3.5.something

**Comment by alkarinv** [comment]
both are old....

https://github.com/downloads/alkarinv/BattleArena/BattleArena.jar

try that one

**Comment by Adondriel** [comment]
Ill install it tomorrow. Gotta go for the night.

**Comment by Adondriel** [comment]
I'm testing the newest version now

**Comment by alkarinv** [comment]
Cool, hopefully things go smoothly!
