### ISSUE TITLE
Problem with health getting to 1 hearts

### ISSUE THREAD

**Issue by owengraven** [alkarinv/BattleArena#76]
Everytime a player joins a arena pvp match his health drops to 1 hearts, the arena's (3) are set in a world called arena and managed by multiverse!

I thaught it was mutliverse that didnt load enough, but even if i set the world to be loaded at all times they still get dropped.

Strange, it doesnt happen for paintball.

Also my /arena duel cmd doesnt work, it sends and tells but never goes on after /arena accept.

Cb 1.4.5 0.2. / pex / griefprevention (but not set in that world) / multiverse core / inventories / battlearena / battletracker / paintballarena
Thx for any help.

**Comment by alkarinv** [comment]
Can you pastebin me your PaintballConfig.yml?  Also what version of BattleArena are you using?

I'll check things out when i know!

**Comment by owengraven** [comment]
Pastebin for paintballconfig? My problem is on the normal arena pvp, thats where it drops to one heart.
I'll pastebin my 2 configs for them once i'm home meanwhile battlearena version is: 3.7.5.1
Paintball arena: 1.0.7

But normally my configs are untouched, i just dropped the jars, installed it and tadaa.  It's perfect out of the box for me.

**Comment by alkarinv** [comment]
Yeah, im just wondering if i accidentally put in "health=1".

I bet I did, so just change that to 20 and you are probably good!

**Comment by owengraven** [comment]
Checked and indeed was set to 2, instead of 20.

Thank you very much for your fast help, your great!

**Comment by owengraven** [comment]
Ah idea for /duel cmd? Forgot that out of happyness

**Comment by alkarinv** [comment]
I bet if you upgrade to the newest BattleArena that will work... not completely sure though.

**Comment by owengraven** [comment]
I'll tryit out when i upgrade my things, and keep informed .)

Thx

**Comment by alkarinv** [comment]
Can you try this one for the duel fix? tell me if it works

http://dev.bukkit.org/media/files/656/51/BattleArena.jar

**Comment by owengraven** [comment]
Works great, thank you very very much.

Really, i've had hard time asking support from some developers, i'm happy there are still good ones like you.
