### ISSUE TITLE
duel error

### ISSUE THREAD

**Issue by mheiden** [alkarinv/BattleArena#78]
When people want to play duel and invite with /arena duel [name]
The other user gets a invitation but when they type /arena accept

The following error is coming up in the console and the duel invitation is cleared.
Error:  
http://pastebin.com/ZMs51ibg

Config file BattleArena:
http://pastebin.com/hb3pYqLr

What to do to solve this problem?

**Comment by alkarinv** [comment]
Thank you, i'll try and fix that today and get you a link!

**Comment by mheiden** [comment]
Thanks in advance ^^

**Comment by alkarinv** [comment]
Can you try this one and let me know if it work!

http://dev.bukkit.org/media/files/656/51/BattleArena.jar

**Comment by mheiden** [comment]
You are awesome, it works!
Many many thanks :p
