### ISSUE TITLE
BattleArena plugin, don't work

### ISSUE THREAD

**Issue by lorenzreweghs** [alkarinv/BattleArena#80]
Hello,
I have mad an arena and you can join it very well, PVP is enabled on the world, but not everyone can do PVP and nobody can use potions or something, they got no permission.
But I use Groupmanager and I have give them in that world the arena.arena.join permission and the arena.arena.use.\* and the worldguard.\* perm, but they have no permission.
So, what is the problem, for example if they wanna use a potion this is in the chat: Not allowed to use potion. I am OP and I can do PVP and everything but they not.

Greetz,
Lorenz

**Comment by alkarinv** [comment]
Hey Lorenz, so Can you pastebin me your BattleArena/config.yml?

Can they not hit each other?

I also don't have any permissions for potions, so that would be another plugin stopping that. Look through the plugin list and Im sure you'll see which one.  Once you find it let me know.. It's probably also stopping pvp.

Let me know!

**Comment by stevewall85** [comment]
i have the same issue with group manage and cb 1.4.5 i have the same perms set for the usage of signs and they cannnot use the signs here is the config:
http://pastebin.com/p8CksyFw

**Comment by alkarinv** [comment]
That is very odd, did you give them
- arena.class.use.*

That should allow them to use all class signs

**Comment by stevewall85** [comment]
Newbie:
    default: true
    permissions:
    - -towny.nation.new
    - -towny.town.new
    - -mobarena.classes.Knight
    - -mobarena.classes.Ranger
    - arena.arena.join
    - arena.class.use.*

just like so in essentials

**Comment by alkarinv** [comment]
Hmm, maybe the \* perm isn't working right.

how about
- arena.class.use.gladiator

try using explicit class names?

**Comment by stevewall85** [comment]
```
- arena.class.use.gladiator
- arena.class.use.monk
- arena.class.use.archer   
```

 i added like so and it seems to work for the moment.  thanks for the help

**Comment by alkarinv** [comment]
Well it seems like the GroupManager  doesnt like the \* perms... :(

**Comment by lorenzreweghs** [comment]
Everything works now for me but I got 1 question: /arena top doesn't work
there comes in the chat: "There is no tracking for a Arena"
What does this means? What do I need to do?

Greetz, Lorenz

2012/12/18 alkarinv notifications@github.com

> Well it seems like the GroupManager doesnt like the \* perms... :(
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/alkarinv/BattleArena/issues/80#issuecomment-11474220.

## 

# 

(Dit is mijn handtekening, dat staat automatisch onder mijn berichten.)
Ik ben terug van zee, was heel leuk !!

.=[Ik speel DarkOrbit,Qpang,Dofus,Aruarose,Crossfire]=.

Bedankt om je tijd te verspillen aan deze rode zin haha =P

_[Ik ben al level 13]_

**Comment by alkarinv** [comment]
You will need to use one of my other plugins

http://dev.bukkit.org/server-mods/battletracker/

It does all the tracking and rankings.  I will also be trying to put top signs and other features in it.
