### ISSUE TITLE
Resetting Spawn positions on "World-not-load"

### ISSUE THREAD

**Issue by scrayos** [alkarinv/BattleArena#82]
Hey, if Multiverse does not load the World where Arena-Spawns are in, all of them gettin' resetted. Could you just don't let them be activated, until the World is loaded again and the Plugin is reloaded? - Cuz it's really annoyin' to set them over and over again, if Multiverse encounters an Error.

**Comment by alkarinv** [comment]
That is really annoying, I'll see what I can do about that.  I've had a couple of people lose their arenas like this.

**Comment by alkarinv** [comment]
Should be fixed in most recent version 3.7.9+
