### ISSUE TITLE
PVP Not working

### ISSUE THREAD

**Issue by creptor** [alkarinv/BattleArena#83]
I had installed this plugin, but when I try to battle with my friends we couldn`t hit each other.

Please Help

**Comment by alkarinv** [comment]
give me your ip and I'll come on to find out whats happening.

**Comment by creptor** [comment]
Ip = 190.91.151.122:25565

**Comment by alkarinv** [comment]
Yep. pvp needs to be enabled in server.properties and plugins like Multiverse.
