### ISSUE TITLE
ForceStart failing when nTeams = 1

### ISSUE THREAD

**Issue by netherfoam** [alkarinv/BattleArena#86]
ForceStart fails stating that:
"MobBattle does not have enough teams queued"
when using /mobbattle forcestart, while 1-3 players are queued for the match using:
/mobbattle join

Clearly it should just start a match with one person on the team.

Cheers again! :) And merry christmas.

Config:

<pre>
MobBattle:
    enabled: true
    type: MobBattle
    database: MobBattle
    matchTime: 600
    rated: true
    prefix: "&a[MobBattle]&e"
    victoryCondition: NoTeamsLeft
    nTeams: 1
    teamSize: 4+
    onJoin:
        options: [pvpOff]
    preReqs:
        options: []
    onEnter:
        options: [storeAll]
    onLeave:
        options: [restoreAll]
    onPrestart:
        options: []
    onStart:
        options: [teleportIn, pvpOff]
    onSpawn:
        options: [deEnchant, hunger=20, health=20, giveItems]
        items: # ignored if options doesnt have "giveItems"
            - iron_sword: 1
            - bow: 1 
            - arrow: 6
            - leather_chest: 1
            - leather_leggings: 1
    onDeath:
        options: [clearInventory, teleportOut]
    onVictory:
        options: []
    onComplete:
        options: [teleportOut, clearInventory, clearRegion]
    winner:
        options: [health=20, hunger=20]
</pre>

**Comment by alkarinv** [comment]
It should indeed! I'll check it out

**Comment by alkarinv** [comment]
Should be fixed in 3.9.9.4+

**Comment by netherfoam** [comment]
Woot! Thanks.
