### ISSUE TITLE
[Feature] Allow container access transition option?

### ISSUE THREAD

**Issue by netherfoam** [alkarinv/BattleArena#87]
I'm pretty confident it is BattleArena stopping this, so here's the request:

It would be great if we could have a transition option or something to allow players to open containers! (Such as a brewing stand, furnace, dispenser, maybe even chests)

Thanks again :)

**Comment by alkarinv** [comment]
Woot!! this one isnt me :)

So I don't change any inventory click or interact event unless specified in the config.  And only then I think for dropping items :)

**Comment by alkarinv** [comment]
But, it could be the worldguard region... so what is the worldguard flag for inventory access?

**Comment by netherfoam** [comment]
Hmm that is interesting!

Players can open a brewing stand inside the arena region after a match, but not during (Granted it was a different brewing stand each time)..

That is strange.  Thanks anyway!

**Comment by netherfoam** [comment]
Found it!

It's WorldGuard... Players can't open Brewing Stands because they're not allowed to build (Go figure?)
