### ISSUE TITLE
[Feature] Reloading arenas.yml, messages.yml

### ISSUE THREAD

**Issue by netherfoam** [alkarinv/BattleArena#88]
Hi again,

You talked about reloading arenas.yml, but it would also be nice if you could reload messages.yml, and give us a method to override such as Arena.onReload() or Arena.reload() in the API to be called whenever the arena gets reloaded!

Also,
Currently there is an ArenaCreateEvent and no ArenaDeleteEvent.  Instead, there is Arena.delete() to override.  For consistency sake, should it not be:
- Arena.delete() and Arena.create() to override, and remove ArenaCreateEvent
- ...Or remove Arena.delete() and add ArenaDeleteEvent

I'm voting for the first one.

Cheerio!

**Comment by alkarinv** [comment]
hmm... I actually like both.. there is already an ArenaDeleteEvent, I guess its just not being called.

**Comment by alkarinv** [comment]
No, it is being called.  

```
@MCCommand(cmds={"delete"}, admin=true, usage="delete <arena name>")
public boolean arenaDelete(CommandSender sender, Arena arena) {
    new ArenaDeleteEvent(arena).callEvent();
    ac.deleteArena(arena);
    BattleArena.saveArenas();
    return sendMessage(sender,ChatColor.GREEN+ "You have deleted the arena &6" + arena.getName());
}
```

and oh... i see the problem... really this event should be being called inside the arena delete itself.. otherwise your arena will never get it unless it is using @EventHandler.

**Comment by netherfoam** [comment]
Ohh, I didn't realise it was there (Never went looking for it, I could just use delete())

**Comment by alkarinv** [comment]
Ok... I'm thinking that for your arena code.. @Override delete().  You are subclassing an Arena and deserve to know what is happening to your arena.

But.. for other plugins that are listening for BattleArena events, they should get to know about it too. So ArenaDeleteEvent should definitely stay..

So the only question is who calls the ArenaDeleteEvent...

**Comment by alkarinv** [comment]
Ok, so the ArenaDeleteEvent should be called before the delete is even started.  That way in the case that it should be cancellable, that people can cancel it before any method actually starts deleting.  So it stays where it is!

**Comment by netherfoam** [comment]
Hmm, I hadn't thought about things listening for arena changes except arenas themselves. You make a good point.

**Comment by netherfoam** [comment]
So... you're just moving it in the method, and @MatchEventHandler will work as intended?

**Comment by netherfoam** [comment]
Still vote for arena.create() too

> :)

**Comment by alkarinv** [comment]
but isnt that the constructor? or init()?

**Comment by alkarinv** [comment]
So as far as the reload.. I do 

<pre>
            ac.removeAllArenas(mp.getType());
            ConfigSerializer.reloadConfig(plugin, mp.getType());
            MessageSerializer.reloadConfig(mp.getName());
            ArenaSerializer.loadAllArenas(plugin, mp.getType());
</pre>

so I am trying to reload the messages as well... insdie of the reloadConfig it looks like I do it right... are you sure that doesn't work??

As far as the reload... How do I get you that information... usually I would say make an interface or abstract class ArenaPlugin? then that could have reload()... can you think of a better way though?  maybe another register method? where you can pass in function to be called for things like reload?

**Comment by netherfoam** [comment]
init() is called every time the arena is loaded, like the server boots, and every time the arena is created.

If we're trying to set defaults etc, we don't really want to do it on init() I think? Instead we want to know that the arena is brand new and needs defaults set.  I guess you could use init() to do both with a few extra lines

EDIT:  Uh, that code looks like init() is being called on reload? That's actually a pretty smart idea...  The rest isn't necessary then! :)

For the reload, I was just thinking, just do it exactly like Arena.onStart(), so

<pre>
public class Arena{
....
protected void reload(){}
...
}
========
public class MyArena extends Arena{
@Override
public void reload(){
this.someValue = plugin.getConfig().getInt(this.getName() + ".someValue");
this.someValue1 = plugin.getConfig().getInt(this.getName() + ".someValue1");
this.someValue2 = plugin.getConfig().getInt(this.getName() + ".someValue2");
}
</pre>

**Comment by alkarinv** [comment]
Ok, you convinced me.  Arena.create() is coming, but for a reload in arena.. that is strange.

When someone does a /reload, all arenas get reloaded too.. which means they all get created again, and initted again...

So what what the Arena.reload() give you that can't be done inside of one of those.

**Comment by netherfoam** [comment]
Not sure if github shows edits in realtime, but I edited after seeing your post :P
EDIT: Uh, that code looks like init() is being called on reload? That's actually a pretty smart idea... The rest isn't necessary then! :)

**Comment by alkarinv** [comment]
http://dl.dropbox.com/u/38069770/jars/BattleArena.jar

Has Arena.create()

Though what do you think about this.. this would still be backwards compatible.. but changing the default to be overriding the Match/Event directly.  You could still do everything in an Arena.. but I was thinking.. why are we overriding arenas, and not the matches

**Comment by netherfoam** [comment]
I don't quite understand what you mean by that :|

**Comment by alkarinv** [comment]
well... public class SpleefGame extends Match{

}

That way it would get constructed on every Match.  Arenas persist a lot longer.. from when the plugin loads till it dies (unless its altered)

**Comment by netherfoam** [comment]
What can I override in a match that I can't override in an arena?

**Comment by alkarinv** [comment]
Nothing....

Its more of a conceptual change.  Then I guess you could have things that only related to the arenas (like stopping people from entering that region between matches) inside of Arena.. and things that related to the Match, inside of that.

Thats why it would in some sense be backward compatible..

**Comment by netherfoam** [comment]
Well that's up to you, I'm fine overriding arena methods because an arena can only have one match at any given time :)

**Comment by alkarinv** [comment]
true... just wondering if in the future it would make more sense for others... but I'm not super invested either way.

**Comment by netherfoam** [comment]
Hmm, can you possibly make arena.create() be called immediately before arena.init()? (Or at some time when Arena has it's basic variables set) - but before arena.init?

It makes more sense that way, and makes it easier if creating/generating/copying config data on first creation
