### ISSUE TITLE
PermissionsEX Ain't working! - Paintball Arena!

### ISSUE THREAD

**Issue by Arcoz** [alkarinv/BattleArena#91]
![Untitled-1](https://f.cloud.github.com/assets/3137403/33238/a271697a-5074-11e2-808d-e5adc8d8b8ba.png)
As said on your dev.bukkit topic, the arena.paintball.join aint working for me

So I thought maybe u answered faster here!

Anyways the problem is that the players can't join even with the permissions above, only OPs can join.
pasteBin: http://pastebin.com/5cgreiy6

The name of the arena is Bobby

So yeah hope u can help me out with this!

**Comment by alkarinv** [comment]
hey, so what is your ip?

**Comment by Arcoz** [comment]
For the server : 198.12.126.196

**Comment by alkarinv** [comment]
Yep, well I think we identified pex as the problem.  So going to close this one :)
