### ISSUE TITLE
[Unconfirmed] Still in an arena

### ISSUE THREAD

**Issue by netherfoam** [alkarinv/BattleArena#92]
Hi, I'm just checking here, but I think that when I'm a member of two or more arena teams, and I get killed/kicked/removed from the one i'm playing, I think i'm not being removed from it when I do /<arena> join again.  So...
- Join an arena
- Die, get removed from the game, but the game should still be running
- Join another arena
- Repeat step 2
- Try to join another arena - Will fail because I'm 'already in an arena', it says in yellow. I can safely leave using the command though.

Can you double check this for me?  I think this is what is causing the issue.   It might me something as simple as
<code>
for(int i = 0; i < getArenas().size; i++){
  if(getArenas().get(i).contains(player){
    getArenas().remove(i);
    break; //Issue if i'm in another team?
  }
}
</code>

But that's just a guess in the dark.

Notably, I'm getting messages for both arenas (I know you had an idea for fixing this? while playing the second arena.)

Thanks again, alk

BA 3.7.8.6, Spigot 1.4.6 R0.2

**Comment by alkarinv** [comment]
Yep, I'll double check that.  Sounds like a bug.

**Comment by alkarinv** [comment]
I believe this is now fixed, reopen if its still an issue.
