### ISSUE TITLE
Arenaspleef auto snowblocks refill?

### ISSUE THREAD

**Issue by lorenzreweghs** [alkarinv/BattleArena#93]
Hello,
I use your plugin ArenaSpleef, but what do I need to do that the snow blocks layer automaticaly regenerate after they have do a spleef battle with /spleef join? I have try /spleef setRegen 30 but that don't really works and I just want to that it after every spleef battle refill auto.

Greetz,
Lorenz

**Comment by lorenzreweghs** [comment]
It works for me now :)

**Comment by alkarinv** [comment]
woot!  closed issue :)
