### ISSUE TITLE
Tournament Join Message dosn't appear when people join the tournament

### ISSUE THREAD

**Issue by sekwah41** [alkarinv/BattleArena#98]
When players type /tourney join it doesn't say anything, can u make it so that it does please becaus people on our server think they haven't joined, is there any way i can change this in one of the files or does it need updating, it happens on the 24 7 server and my private one

people still join and if they type it again it says u are in one type /arena leave and every 2 players that join it announces that but still it doesn't mention at all from what i can tell on my servers that they have joined, everything else seems to be fine.

**Comment by alkarinv** [comment]
yeah, I will definitely add this in... surprised no one mentioned it before.

**Comment by sekwah41** [comment]
thanks for replying so fast, i'm surprised no one noticed it either, also is it ok if i edit the plugin just for my server i wanna change a few things and also add a exam(works like a tournament + would be really good for the server) i just don't wanna use it and get in trouble for anything, i'm not gonna upload it or anything or say i made it, its just that it would be cool. thanks also, ill keep an eye out for the update

**Comment by alkarinv** [comment]
so if you don't mind dev builds.

http://dl.dropbox.com/u/38069770/jars/BattleArena.jar

That will give you the messages.

What is the exam?? if it's cool and you don't mind sharing you should make a pull request!

The project is open source and up on github for a reason.. tweak to your hearts delight.
