### ISSUE TITLE
Floor not resetting after match?

### ISSUE THREAD

**Issue by Maukk** [alkarinv/BattleArena#99]
Hey there, 

I have a little issue, everything is working fine except when a game is over the spleef floor does not reset. I love the plugin great job on it! please tell me how I can fix this problem! (:
Thanks alot

**Comment by alkarinv** [comment]
The spleef floor should regenerate automatically.  If it isn't it's because 1) the region is set wrong, 2) the region got lost 3) I didnt load worldguard correctly with spleef.

Try just selecting the spleef floor again with the worldedit wand and redoing the command
- spleef setlayer <arena name> 1

That might just fix the problem

**Comment by Maukk** [comment]
Thank you very much, I did the whole spleef over. It works again :)
Do you have an idea why it stopped resetting though?

**Comment by alkarinv** [comment]
So there are a couple of things that might do it, if the world wasn't there (like multiverse didnt load properly one time) that would cause it.  Or if someone deleted a bunch of world guard regions and the spleef region was in it.  Or if for some reason the plugin loaded strangely..

If any of those sound familiar then let me know and I'll try to make the saving and loading more robust!

**Comment by Maukk** [comment]
I do use MultiVerse, and I have had one issue with that. WorldGuards, haven't removed any recently.
Not sure whether the plugin loaded strangely, never had problems with it besides the floor.

**Comment by Maukk** [comment]
Also, I have another side-question, is it possible to make it like. ''spleef will start in 1 minute'' and within that minute people can join. so it can be from 1 vs 1 to like 20 people?

**Comment by alkarinv** [comment]
So technically that is called "Event" spleef, where there is an open phase where anyone can join for the specified time. /espleef

I'm trying to get rid of the distinction though and make everything the same command, but just have different ways of joining.. but it probably won't be done for a week or so.

**Comment by Maukk** [comment]
Thanks alot! :dancer:

**Comment by Maukk** [comment]
Okay, so I figured out what the cause is. 
After every server crash, I need to set the arena all over again. If there's a way you could fix this. That would be much appreciated. :)

**Comment by alkarinv** [comment]
Having a hard time reproducing this.. so just make a spleef arena then "crash" and it loses the floor?

what version of BattleArena are you using?

**Comment by Maukk** [comment]
I'm using version 3.7.9.3
To my knowledge the latest version.

**Comment by alkarinv** [comment]
Damn, figured ;)

inside of your Worldedit/schematics folder do you see regions named like ba-spleef-<arena>-0.schematic?

**Comment by Maukk** [comment]
I see 4 :o

**Comment by alkarinv** [comment]
4! Alright, well I think I know the issue, let me get you the spleef.  Just to make sure why don't you delete all of those old ba-spleef-.... layers inside of WorldEdit, then remake it (hopefully for the last time).

http://dl.dropbox.com/u/38069770/jars/ArenaSpleef.jar

**Comment by Maukk** [comment]
Works perfect!
Thank you so much for your effort. Best help I've ever had.
thanks thanks thanks! :D

**Comment by alkarinv** [comment]
woot!

Glad that worked.. what an annoying issue :)
